### ISSUE TITLE
Update Email Notification Language

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#1002]
"To receive an email notification when there is a new nomination, enter a comma separated list of email notification recipients. If left blank, no notifications will be sent."

**Comment by lcrossley** [comment]
Could it resemble the other ones (like Show item_author as source or Source statement position) and say "Email notifications for nominations." on the line next to the box, then "To receive an email notification when there is a new nomination, enter a comma separated list of email notification recipients. If left blank, no notifications will be sent." on the line below the box.
