### ISSUE TITLE
Reader View UI improvements: button text, position of next/previous links

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#1003]
There are some changes that can be made to make this more intuitive. 

1.) Change the 'submit response' button to say 'submit comment'
2.) The 'previous' / 'next' navigation buttons would make more sense in a traditional setup where 'read previous post' would appear on the top and/or bottom left of the screen and 'read next post' would appear on the top and/or bottom of the right side of the screen.

**Comment by boonebgorges** [comment]
I've made the change to the comment button text.

Moving the navigation links would mean a broader redesign of the single-item Reader interface. Currently, the Next/Previous links contain the entire item title, along with an excerpt. To put the "Previous" item on the left, in this same format, would mean introducing something like a three-column view, which would introduce a lot more problems. I'm going to mark this ticket as complete, but this kind of navigation will certainly be one of the considerations in any future redesign.
