### ISSUE TITLE
Default comment allowed role doesn't match between settings and comments.php

### ISSUE THREAD

**Issue by boonebgorges** [PressForward/pressforward#1012]
The default 'pf_feature_comments_access' role is 'contributor', according to the settings panel. But the default role described throughout comments.php is 'editor'. So, until settings have been saved, there's a mismatch.

For my purposes, Contributor would be a much more convenient default, but I'll leave it to the wisdom of the team to decide which role to settle on :-D

**Comment by AramZS** [comment]
Debug bar commands to test. 
`var_dump(get_option('pf_feature_comments_access'));` = `edit_posts`
`var_dump(delete_option('pf_feature_comments_access'));` = `true`
`var_dump(get_option('pf_feature_comments_access'));` = `false`
