### ISSUE TITLE
Fatal error on activating PressForward 5.1.1

### ISSUE THREAD

**Issue by alexlancaster** [PressForward/pressforward#1019]
When I attempt to activate PressForward 5.1.1. on a WordPress 4.9.8 installation I get the following:

     Plugin could not be activated because it triggered a fatal error.

     Warning: require(/home/darwin6/public_html/ronininstitute.org/wp-content/plugins/pressforward/Controllers/stdClass.php) [function.require]: failed to open stream: No such file or directory in /home/darwin6/public_html/ronininstitute.org/wp-content/plugins/pressforward/class-SplClassLoader.php on line 159`

Is there some known issues with those versions?

**Comment by AramZS** [comment]
@alexlancaster This appears to be an issue due to PHP version, I'm running a test on a patch now, but for reference can you tell me what version of PHP you're running?

**Comment by alexlancaster** [comment]
> @alexlancaster This appears to be an issue due to PHP version, I'm running a test on a patch now, but for reference can you tell me what version of PHP you're running?

According to the Display PHP Version plugin, it's version: 5.3.29

**Comment by AramZS** [comment]
@alexlancaster We have a back-compat error on 5.3 looks like. I've found the issue in unit testing and will have a patch soon.

**Comment by AramZS** [comment]
@alexlancaster Worth noting that while we do intend to support 5.3+ you should likely update your version of PHP, as 5.3.x PHP is long past it's active and security support period and represents may have vulnerabilities that leave your site open to attack.

**Comment by AramZS** [comment]
@alexlancaster yup! It will be in the next release.
