### ISSUE TITLE
Add item_link to PF Posted endpoint

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#1024]

**Comment by AramZS** [comment]
@mAAdhaTTah Since this was a feature you requested, could you confirm that this patch does what you need?

**Comment by mAAdhaTTah** [comment]
`item_link` does what I needed, thanks. The `pf_posted` url took a while to load though.

**Comment by lcrossley** [comment]
If item_link is just a link to the original post's url, then it's working for me
