### ISSUE TITLE
Assure Headers are set on pf_posted endpoint

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#1028]
The pf_posted endpoint should have headers on its response that look like this with Total indicating total number of posts on the endpoint and Totalpages indicating the total pagination possible (?page=x) on the endpoint. 
```
X-Wp-Total →12434
X-Wp-Totalpages →1244
```

**Comment by AramZS** [comment]
Do we need `<https://www.chronoto.pe/wp-json/wp/v2/posts?page=2>; rel="next"` ? (Self note)

**Comment by lcrossley** [comment]
This failed for me. WP version 4.8.7, and debug bar gives the php version as: 7.0.27-1+ubuntu14.04.1+deb.sury.org+1

**Comment by lcrossley** [comment]
After changing permalink settings, now I'm getting the total number of posts and the total pagination
