### ISSUE TITLE
Sort by "Date nominated" not working as expected in Nominated

### ISSUE THREAD

**Issue by lcrossley** [PressForward/pressforward#1031]
On my setup (WordPress version 4.9.8), when I nominate something using the bookmarklet, and I go to the Nominated panel, that item does not show up at the top. It still does not show up at the top when I click Sort > Date nominated. I can only get it to show up at the top by clicking Sort > Date retrieved. Items nominated from All Content do show up at the top of Nominated right away. On Alyssa's setup (WordPress version 4.8.7), when I nominate something with the bookmarklet and I go to Nominated, it shows up at the top. When I sort by date nominated, it's still at the top. Sorting by date retrieved doesn't change anything. A couple things to note: When I check the time retrieved for a post in All Content, nominate that post, then check the metadata, the time retrieved changes--it becomes the same as the nominated time (on both setups). Also, on Alyssa's setup, the date and time listed on the right side of the screen for each post is the Nominated/Retrieved time. On my setup, the date and time listed there is the Posted time.

**Comment by boonebgorges** [comment]
The implementation for 'Date nominated' sort has been rewritten. See #1156.
