### ISSUE TITLE
Use actual meta boxes for Nominate This interface

### ISSUE THREAD

**Issue by boonebgorges** [PressForward/pressforward#1037]
The Nominate This interface (nominate-this-core.php) hardcodes the publishing-actions box, along with the 'category' and 'post_tag' interfaces. I'm doing a project where I need to customize this interface a fair amount, including removing some taxonomies and adding others. Currently, this is difficult to do because everything is hardcoded (albeit with a couple of actions). It would be much easier if the interface were built by calling `do_meta_boxes()`.

As a side note, this change would also fix some existing bugs related to taxonomy capabilities in Nominate This. To wit, users without `assign_terms` shouldn't see the interfaces; users without `edit_terms` shouldn't be able to add.

Would you accept a PR along these lines? It looks to be relatively straightforward, but I wanted to gauge your interest before doing the work.

**Comment by AramZS** [comment]
@boonebgorges I would totally accept a PR along those lines, just be aware that we are in the process of developing a replacement Chrome Plugin that does not extend existing WordPress interfaces at all. However, if you can put together the pull request we might be able to extend the functionality you push to Nominate This to control for the same issues or pull from an API end point the meta boxes.

**Comment by boonebgorges** [comment]
Thanks, @AramZS - this is good to know.

When you say "replacement", I hope this doesn't mean that you'll be removing the old Nominate This altogether - just deemphasizing it or something. A Chrome tool (aside from being tied to Chrome, which is not ideal for some users) is likely not to be extensible in the same way as the WP-based nomination interface, which will make it a poor fit for projects like mine where we need the customizability. Please leave the old code in there but off by default, or at least move it into a plugin so that we can upgrade at some point seamlessly.

I'll work on a PR in the upcoming weeks.

**Comment by AramZS** [comment]
Yes, we are only making an additional tool available, we won't be removing the old Nominate This, but creating an alternative for sites where the DOM is not accessible via server to server request. All the old nominate this tools will remain in place.
