### ISSUE TITLE
Nominated to posts logging runs out of memory

### ISSUE THREAD

**Issue by stakats** [PressForward/pressforward#1039]
`$ntp_args = array( 'posts_per_page' => -1, 'meta_key' => 'item_link' );` in `debugger.php` seems to be generating this error on Digital Humanities now:
`PHP Fatal error:  Allowed memory size of XXXXX bytes exhausted`

**Comment by AramZS** [comment]
Hi, this should only crash in the debugger page and we intended to replace it with the overall stats page, which can handle paginated queries better.

**Comment by boonebgorges** [comment]
I did the above, and also put the log contents inside of a separately-scrollable window:

![Screenshot_2024-03-04_12-06-57](https://github.com/PressForward/pressforward/assets/246627/aeb57486-6c4a-44b6-8e89-beb05f976411)
