### ISSUE TITLE
Canonical URL set by Yoast SEO plugin is overwritten with Post guid

### ISSUE THREAD

**Issue by zlove** [PressForward/pressforward#1043]
When using the Yoast SEO plugin, if the PressForward plugin is activated, the canonical URLs set by Yoast SEO have no effect. Instead, the canonical URL (in the `<link rel="canonical" ...>` tag) is set to the GUID of the Post. 

I did not investigate to see where / how PressForward might be effecting the canonical URL. In any case, setting it to the Post guid (if that is what PressForward is doing), is often incorrect - for instance if you setup a Wordpress site in a local or staging environment, those guid's often include domains that do not match the production site.

- PressForward version 5.1.1
- Yoast SEO version 10.1.3
- Wordpress version 5.1.1

**Comment by AramZS** [comment]
Hi @zlove The canonical url is only set to the source URL in cases where `pf_forward_to_origin` meta on the post is set to true (the forward to origin option). In that case the system will forward users who arrive on the post to the original post URL. In that situation all documentation of the canonical tag indicates that in that situation the canonical tag should be set to the page that the user is being forwarded to. In this case, the behavior is both expected and appropriate.
