### ISSUE TITLE
Email notification when a new comment is written

### ISSUE THREAD

**Issue by yoannspace** [PressForward/pressforward#1044]
In the same way that #987 is sending emails for new nominations, we would like to be able to send out emails for each new comments.
Would you be ok to have this in? I have started testing this.
Thanks,
Yoann

**Comment by boonebgorges** [comment]
I've added this feature. Here's a screenshot of the email:

![Screenshot_2024-07-26_11-34-25(1)](https://github.com/user-attachments/assets/8abeee05-5ba2-466e-80f9-8f86c5e5aac2)

I've used the language 'interacted with' to indicate that emails are sent on comments (a) on nominations or other items I've created, or (b) on items where I've previously left a comment.

There's a user-specific setting to toggle these emails on and off. I've integrated these settings into those used in #1105, which use global defaults at Dashboard > PressForward > Preferences > Site Options. All of these options default to 'Disabled'.
