### ISSUE TITLE
Gutenberg support? Block for citation/credits

### ISSUE THREAD

**Issue by lordmatt** [PressForward/pressforward#1052]
I have been delighted with my local test install of this plugin. It might be one of the best plugins I have explored this year. One question, though. Do you plan to add Gutenberg support?

**Comment by AramZS** [comment]
@lordmatt I've actually been exploring Gutenberg support, do you have any particular ideas as to blocks that would make sense to add in, or just do you mean decomposing the text into Gutenberg blocks on save, where Gutenberg is running?

**Comment by lordmatt** [comment]
A little of both. One obvious block would be a citation/credits block.

**Comment by boonebgorges** [comment]
I've written an initial implementation of a Credits block. It includes two bits of info that we have ready at hand, and which are also shown in the 'Nomination Info' inspector control: the "author on source" value, and the source link. Here's a brief video showing how it works. The design and configuration behavior are intentionally similar to what you see in the Nominators block #1104.

![Peek 2024-07-23 14-52](https://github.com/user-attachments/assets/1b335cb8-138e-48fc-878f-f583e60a6aab)
