### ISSUE TITLE
Pressing the image button on the book marklet leads to an error on the console and nothing happening

### ISSUE THREAD

**Issue by mrbm** [PressForward/pressforward#1074]
Pressing the Add: (image icon)

Which I assume would attempt to grab a "featured image" via the og:image meta tag or something, but then it just shows the text: Loading...

And then does nothing. Opening the inspector console reveals 2 errors:

[Error] SyntaxError: Unexpected token '<'
	appendChild (edit.php:1:851)
	b (load-scripts.php:2:851)
	globalEval (load-scripts.php:2:2880)
	text script (load-scripts.php:2:82990)
	(anonymous function) (load-scripts.php:2:79371)
	l (load-scripts.php:2:79487)
	(anonymous function) (load-scripts.php:2:82256)
[Error] SyntaxError: Unexpected token '<'
	eval (edit.php:145)
	success (edit.php:145)
	c (load-scripts.php:2:28300)
	fireWith (load-scripts.php:2:29041)
	l (load-scripts.php:2:79812)
	(anonymous function) (load-scripts.php:2:82256)

**Comment by boonebgorges** [comment]
We now use the block editor for Nominate This, so I'm going to close this as wontfix. Thanks for the report.

**Comment by mrbm** [comment]
@boonebgorges i am confused, what is "Nominate This" did the plugin change names? It's been a while since i attempted using this.

**Comment by boonebgorges** [comment]
'Nominate This' is our internal name for the tool that pops up when you click on the bookmarklet.
