### ISSUE TITLE
Revisit 'No HTTPS allowed' language on OPML import panel

### ISSUE THREAD

**Issue by boonebgorges** [PressForward/pressforward#1173]
As in other places in PF, this likely dates from a time when HTTPS support on the WP server couldn't be as easily assumed.

Regardless, the specific case of the 'No HTTPS' on the OPML URL field appears to be inaccurate - it's perfectly possible to import using HTTPS URLs.

**Comment by AramZS** [comment]
I agree, this was back when the vast majority of WP installs were not HTTPS and we expected users to not be on HTTPS when interacting with the field. It could likely be rephrased significantly better in respect to the current footprint of WP installs.
