### ISSUE TITLE
Allow users to add Twitter users as feeds

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#139]
We can query the API, find tweets and pull links from tweets into the All Feed as stories (link, title, story, retrieved from HEAD maybe?) and allow the admin to set a threshold of retweets or replies before they are parsed into the system. 

After entered as posts into the All Feed area, they can be treated as normal in the workflow.

**Comment by lordmatt** [comment]
At the slight risk of overstepping my bounds, might this not be best handled by an add-on plugin? Something that handles Twitter and only Twitter and can be maintained separately? I've not explored how modules work yet but at a guess... Take that all with a pinch of salt, I'm just thinking out loud.
