### ISSUE TITLE
Is there a way to make the source of published content more obvious?

### ISSUE THREAD

**Issue by hollybik** [PressForward/pressforward#236]
Hi, we've been playing around with PressForward at UC Davis, and one thing we've been worried about is attribution for the original source of nominated/published content. Although there is a "Source" tag added at the bottom of published posts, it does not mention the name of the original blog or author (both of which we think are important). This "Source" tag might also be better at the top of the posts (and/or somehow listing the original blog/author in the "author" tagline of the post header). With the current layout, site visitors may assume that nominated content from PressForward is original content on the blog (versus material that is actually re-shared/re-posted); in addition, blog authors may not be happy if their content is not obviously attributed on sites using PressForward.

**Comment by devinbalkind** [comment]
Can you post a link to documentation that explains how to "make the source of published content more obvious?"
