### ISSUE TITLE
Extend source links with the mset attribute

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#255]
See for how: http://berkmancenter.github.io/cache-link/mset-attribute.html
See for why: https://www.newschallenge.org/challenge/2014/refinement/404-no-more-fix-missing-links-forever

Potential expansion? Allowing users to see a readable-ized version of the text should the origin disappear.

**Comment by boonebgorges** [comment]
A brief web search suggests that this never got any traction. So, while I think it's a good idea, I don't think it's worth implementing.
