### ISSUE TITLE
Create a template tag to reveal internal comments on an aggregated post

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#290]
Suggested at http://blogs.law.harvard.edu/doc/2014/05/18/lets-pull-news-out-of-its-hole/comment-page-1

I think it is a pretty cool idea.

**Comment by AramZS** [comment]
No styling provided, but list can now be output

**Comment by AramZS** [comment]
`the_pf_comments` is a function now ready to be included in themes. To test this, Add it to a theme and it should show the PressForward comments in the front end.

**Comment by regan008** [comment]
hmmm -- it looks like this is pulling in the navigation from posts from wired rather than the comments. Will do some more investigating once you fix the retrieval process so I can add some different feeds.

**Comment by regan008** [comment]
@AramZS This is working!
