### ISSUE TITLE
Optimize the posts delete query

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#321]
https://github.com/PressForward/pressforward/blob/master/includes/feed-items.php#L369 
It only needs IDs

**Comment by AramZS** [comment]
Please test the deletion and clearing of feed items, as well as their expiration.

**Comment by regan008** [comment]
@AramZS can you elaborate on what I should be looking for in regards to expiration? Am I looking to ensure that it is deleting old items at the proper cut off date? (60 days right?)

**Comment by AramZS** [comment]
@regan008 Yup, basically it should be deleting feed items that are older than 60 days

**Comment by AramZS** [comment]
Or earlier or later depending on the settings. 2 months is just the default.

**Comment by regan008** [comment]
testing this on dev.dhnow.org to ensure it is working.

**Comment by regan008** [comment]
Wait, sorry its actually dev.digitalhumanitiesnow.org. I'll check the db tomorrow to ensure this is indeed working.

**Comment by regan008** [comment]
Ok, I believe this is working
