### ISSUE TITLE
Hook a feed retrieval progress bar to the Heartbeat API

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#335]
Show current feed and overall progress. 

Store current feed in an option, display it there.

**Comment by AramZS** [comment]
Still looking for thoughts on what pages this should go on and thoughts on styling.

**Comment by regan008** [comment]
Hey @stakats this was a feature you had requested at our kickoff meeting last November right? Its live in pftesting.chnm.org if you want to take a look. I will send you a login right now. It should appear on both the All Content and Nominated pages at the moment.  Do you have any thoughts as to where this should be located or how it should be styled?

@lmrhody and I briefly discussed it on Monday.  My impulse is to remove it from Nominated all together and have some sort of button in All Content that says "Show Feed Retrieval Process." When clicked the button would drop down and show the loading bar and progress message.  What are your thoughts on this Sean and Aram? Would that be possible @AramZS ?

**Comment by AramZS** [comment]
@regan008 That would be possible, yes.

**Comment by stakats** [comment]
@regan008 Agree that the progress bar does not need to be available everywhere. If we're going to show feed retrieval process like the way you describe, it might make sense to have a single place where you see when feeds were last retrieved, when they'll next be retrieved, and progress if they're currently being retrieved. I can also imagine that having a button right there that manually kicks off retrieval (which we can already do elsewhere) would make sense. If this all sounds complicated, just take a look at Zotero's sync icon for an idea how it could work.

**Comment by AramZS** [comment]
@stakats Ok, do we have a preference on where that location should be?

**Comment by AramZS** [comment]
Note: Do not fire on the Tools page. It is currently firing on the Tools page. Unless we want to move this to the Tools page?

**Comment by regan008** [comment]
@AramZS Just installed 3.7 on a fresh install and before I added any feeds the heartbeat loading bar showed up in All Content showing that 1 of 0 feeds was being checked. 
![screenshot 2015-10-27 16 03 42](https://cloud.githubusercontent.com/assets/4553057/10770948/6a89ad0e-7cc4-11e5-800a-1666768861fb.png)

**Comment by AramZS** [comment]
Move this to tools for now.

**Comment by regan008** [comment]
Looks good
