### ISSUE TITLE
Bug testing protocol

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#375]
Below are our two under-development test forms. @AramZS Can you look these over to see 
a.) are we missing something;
b.) should we be capturing different information;
c.) what would be the best way to synthesize and to redirect the information back to you? 

The first link is to test contributor-level roles. This user should not be able to see "under review," "add feeds" and should not be able to delete feeds or archive posts. 
contributor: http://dhnow.chnm.org/testing-form-contributor/ 

The second link is to administrator-level roles.  This user should have the ability to see under review, send items to draft, delete posts, and add/delete feeds. 
admin: http://dhnow.chnm.org/testing-forms/

**Comment by regan008** [comment]
I'm going to close this, I think we need to go back and revisit the testing forms regardless since so much has changed over the last year.
