### ISSUE TITLE
Filter by date in All Content

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#376]
It would be great if users could log into the All Content panel and then have the option to use a calendar interface to select a particular date or date range within the past calendar month and display only the feeds that were posted on those days.  I can imagine that there would be a graphic interface that says: Sort by date, and when you hover over it, a calendar pops up.  The user could click on the desired dates, and then click "search" and the response would be that items originally posted on that particular date would be listed in the All Content panel from most recent to least recent. By clicking "Show all," the user would return to the default content list.

**Comment by boonebgorges** [comment]
I've built this feature. I added a small 'All Dates' button with a calendar icon to the Nominated  Items and Feed Items interfaces. When you click, a small interface opens up to select start and end dates. The button text changes according to your selections. See gif:

![Peek 2024-11-01 11-31](https://github.com/user-attachments/assets/91061b3a-78bc-4d05-a908-a0720a79f989)
