### ISSUE TITLE
Refresh button is not showing responses outside of DEBUG mode

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#391]
We should probably also have it be un-clickable until that response is received.

**Comment by regan008** [comment]
@AramZS Are you referring to the PressForward debug module or to wp-debug?

**Comment by AramZS** [comment]
@regan008 both of them should be off on a normal production site but the button should display a response.

**Comment by AramZS** [comment]
@regan008 Though, it isn't showing a response even with them on.

**Comment by regan008** [comment]
This seems to be fixed -- it is showing responses when debug is both on and off
