### ISSUE TITLE
We need to separate the archive action between All Content and Under Review

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#406]
The code attempts to check the item id for the same original item in both contexts, but for archiving it should check the nomination ID.

**Comment by AramZS** [comment]
Dupes #541

**Comment by regan008** [comment]
@AramZS There isn't an archive button in All content right? Are you referring to hide in all content and archive in nominated?

**Comment by regan008** [comment]
@AramZS So I think this is half working (assuming I am understanding this issue correctly). The hide functionality in All Content is still causing items to archive in Nominated but only for Administrators. For contributors it works as expected. Hiding an item does not archive it in Nominated. I think this is just a user permissions bug -- hiding an item in all content shouldn't ever archive the item in Nominated. 

It does work the other way around though. Archiving an item in Nominated does not hide the item in All Content.

**Comment by regan008** [comment]
@AramZS This appears to be working in some contexts however I am encountering issues when I try to unarchive an item. Here is a breakdown:
* archiving an item in Nominated removes (hides? archives? not sure which) the same item from All Content
*However, according to commit `ddca4c5` it should work in the reverse too.  When an item in unarchived not only does it not reappear in all content, it completely disappears and never returns to nominated. It also is removed from archived in Nominated.

**Comment by AramZS** [comment]
@regan008 Are you trying to unarchive from the context of Under Review?

**Comment by regan008** [comment]
@AramZS Yes -- that was where I was unarchiving from.

**Comment by bschnei6** [comment]
I've run some tests and my results are:
1) Some pieces cease to appear in nominated when archived, but do not appear under nominated.
2) Unarchiving items removes them from the archive, but does not restore them in nominated.
3) Items archived by one user no longer appear for other users, either in nominated or in the archive.
4) Items archived in nominated are hidden in all content.
5) Items hidden in all content remain visible in nominated.

**Comment by AramZS** [comment]
I cannot duplicate these results at all, can you check the network tab for the ajax response on each button press? @regan008 @bschnei6 

I'm confused what's 'the archive' referring to in 2 and 3? @bschnei6 

4), 5) are anticipated behaviors.

**Comment by regan008** [comment]
@AramZS I think for 2 & 3 @bschnei6 is referring to the "show archived" filter view

**Comment by AramZS** [comment]
Wait, but that filters in, not out. It shows either Archived and Unarchived, or Unarchived. @bschnei6 - So unarchiving an object disappears it from the page?

**Comment by regan008** [comment]
@AramZS Sorry I used the wrong terminology -- I meant the show "only archived" filter. Unarching an object makes it disappear from that view however it never reappears in nominated

**Comment by regan008** [comment]
So to clarify the bug I'm seeing is not that unarchiving an item makes it disappear from the "only archived" filter but that when an item is unarchived it never reappears when you go back to the default nominated view.

**Comment by AramZS** [comment]
Should now be resolved.

**Comment by regan008** [comment]
This is working now
