### ISSUE TITLE
Make URL of feed changable from Quick Edit.

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#416]

**Comment by AramZS** [comment]
@boonebgorges Just pinging you to see if you can get to this in the next week or so?

**Comment by boonebgorges** [comment]
Thanks for the ping about this - I'm just coming back from newborn baby duties, and this had gotten lost in the shuffle. I've introduced the Quick Edit functionality in cc07875. Let me know how it looks.

**Comment by AramZS** [comment]
@boonebgorges Looks great! This is resolved.
