### ISSUE TITLE
All content and nominated pages taking a long time to load

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#455]
During testing, the all content and nomination pages are taking an extra long time to load. The page may appear to be fully loaded as the content will appear; however, in the browser, you can see that the page is continuing to load.  During the loading process, users cannot nominate or comment on items.  Seems like there's a delay in the javascript. You can see this, for example, in the Nominated page, because the content will load with the PF menu buttons on the left, then only after the whole page is loaded, the buttons move to the right. 

The issue can be recreated in pfsample.chnm.org

**Comment by AramZS** [comment]
Needs check to see if the temp solution currently in place is sufficient.

**Comment by regan008** [comment]
@AramZS This seems to be a bit better.  The All Content and Nominated pages are still lagging a little bit. If the page isn't fully loaded and you try to use an action button it doesn't work.  Overall though I think it is loading faster than it was in December.

**Comment by AramZS** [comment]
Errr.... it shouldn't let you see anything until the page is fully loaded. You were using 3.4.x? Perhaps the code isn't working as expected.

**Comment by regan008** [comment]
I'm pretty sure I installed 3.4.x.  I'll give it a shot one more time in a
few minutes just to be sure.

**Comment by AramZS** [comment]
@regan008 I've made some adjustments. Give it another try.

**Comment by regan008** [comment]
@AramZS Seems to have fixed it--the panels now have a loading bar and nothing appears until the page has been loaded.  Everything works immediately once it appears now.
