### ISSUE TITLE
No way to show hidden in Under Review

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#457]
In Under Review there isn't a show hidden button. Should hidden even be on the Nominated page since we have archive?

**Comment by AramZS** [comment]
Ok, I'm thinking that perhaps hidden shouldn't be in the Nominated page, it duplicates functionality pretty heavily and making a change to make them both work is a pretty big change.

**Comment by AramZS** [comment]
Closing this now with the change in the comment above.
