### ISSUE TITLE
Nominate This doesn't always detect existing versions. 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#459]

**Comment by AramZS** [comment]
The problem is that the title tag on a site and the title in an RSS feed is not always the same, and the process to check for duplicates requires both Title and URL to be identical.

**Comment by AramZS** [comment]
Instead, check for possible duplicates and ask if those items are duplicates. If user says yes, nominate one of those instead of building a new item.

**Comment by AramZS** [comment]
Confirmed that no version of duplicates is ever checked for.

**Comment by AramZS** [comment]
Probably related to #578

**Comment by regan008** [comment]
@AramZS Do you happen to have an example of a site where this is a problem? I'm testing but haven't been able to duplicate it.

**Comment by AramZS** [comment]
Pre 3.8.x you would get an empty post when you clicked edit or view after a success on the second time using Nominate This on the same article. Afterwords you should be able to use nominate this many times on the same article and always get sent back to the same post ID to edit or URL to view.

**Comment by regan008** [comment]
@AramZS Ahhh, ok, I misunderstood the issue. Let me test that then

**Comment by regan008** [comment]
Ok, I see a couple issues so far. 
1. If the post was nominated (but not drafted) multiple times using the bookmarklet the "Edit" or "View" Post option takes you to either a blank post or to a browser page with an error. 
2. When a post is drafted and you nominate the same one using the bookmarklet and click edit or view it generate an error in the browser that says "too many redirects"

It seems to me that, upon success of nominating an item the edit/view link shouldn't be visible. Those options should only appear when drafting a post.  Unless of course the item has previously been drafted but that seems like a much more complicated issue? 

Also, and I'm not sure this is related to this issue but at some point I think a bug was introduced that allows items to be drafted more than once. Every time I'm clicking draft in Nominated its generating a new post.

**Comment by AramZS** [comment]
This is happening with Nominations Bookmarklet to Nomination

**Comment by AramZS** [comment]
This is no longer happening with Nominations to Draft

**Comment by regan008** [comment]
@AramZS Ok, so I think this is mostly fixed but I do see one new issue that I think is related.

The nomination count doesn't appear to be increasing for additional nominations of the same post (by different users) with the bookmarklet. I nominated an item from a contributor account and then nominated the same item with my admin account and the count never progressed past 1. 

However, when nominating the same item multiple times from the same account it seemed to work as expected.

**Comment by regan008** [comment]
tested and confirmed that this is working as expected now!
