### ISSUE TITLE
glitched out tile at the bottom of All Content

### ISSUE THREAD

**Issue by kaichi** [PressForward/pressforward#466]
![bunched-up](http://i.imgur.com/WRQHWGA.png)

I see this every once in a while on a few different WP instances that I've been playing with PF. A random tile will get bunched up at the bottom of both the Infinite Scroll and Pagination. The only way I can get rid of this as an end-user is to X out the tile... Which essentially removes it from content pulled into PressForward.

I am not sure what is causing it with the feeds I have coming in. I see this bug quite often.

If I create another administrative user on my WP instance and gave it to **AramZS** he may be able to go in, look at the DOM and figure out what's causing the bug.

**Comment by AramZS** [comment]
@kaichi This is now resolved. Readability was not properly closing one of the HTML tags, leading to the messy presentation. Tag 3.4.5 should have this fully resolved.
