### ISSUE TITLE
What other aggregation services mask URLs?

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#471]
We now have a way for the system to force resolution of URLs when they are provided by known aggregation services that mask the URL in a may that may cause an issue.

We could resolve all URLs, but that takes extra time I don't want to add to the process. 

So, other than Google Alerts are there any other aggregation services we know of that people might subscribe to that mask the URL in a similar way?

Related: do we want to add the additional work of forcing a resolution of the URL to the readability process regardless of the URL's source? 9 out of 10 times the system should be able to resolve this itself, only some URL forwards are problematic.

**Comment by AramZS** [comment]
Bringing in @slwestcott

**Comment by lmrhody** [comment]
@slwestcott Have we received OPML files from partners? This might help us to suss out what other URLs may have similar issues.

**Comment by AramZS** [comment]
Should add The Twitter Times to this list.
