### ISSUE TITLE
Article pages with multiple articles (infinite scroll types) are baffling Readability

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#477]
Ex: http://www.niemanlab.org/2015/01/gawker-medias-independent-kinja-posts-apparently-arent-generating-a-ton-of-traffic/

**Comment by AramZS** [comment]
But only with the Nominate this bookmarklet, which continues to intermittently have problems with splitting lines, a-links not properly showing up, and inconsistent readability processes. Not sure why.

**Comment by boonebgorges** [comment]
That specific example no longer uses infinite-scroll pagination. Let's close until we can get reproducible examples. See also #592.
