### ISSUE TITLE
Allow users to redirect to original posts on a per-post basis. 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#479]

**Comment by AramZS** [comment]
Needs testing

**Comment by regan008** [comment]
Hey @AramZS Could you elaborate on what this means? I'm not sure where to look for it or what the expected behavior should be.

**Comment by regan008** [comment]
@AramZS any update on this?

**Comment by regan008** [comment]
@bschnei6 Here are the expected actions to test on this issue: 
1. When the site redirect preference is turned on, is the checkbox in a PressForward draft also checked?
2. When the site redirect preference is turned off, is the checkbox in a PressForward post draft unchecked?
3. When the site redirect preference is turned on, does unchecking the the checkbox inside a PressForward draft stop the published post from redirecting to the original source?
4. When the site redirect is turned off, does checking the checkbox inside a PressForward cause the published post redirect to the original source?

**Comment by bschnei6** [comment]
1. When preference is on, checkbox IS NOT checked.
2. When preference is off, checkbox IS NOT checked.
3. When the site redirect preference is turned on, unchecking the the checkbox inside a PressForward draft stops the published post from redirecting to the original source.
4.When the site redirect is turned off, checking the checkbox inside a PressForward  does not cause the published post redirect to the original source.

**Comment by regan008** [comment]
So @AramZS I think the issue still active here is that when the redirect preference is turned on the checkbox inside the post doesn't become active and the posts don't get forwarded.  The checkbox ends up having to be manually checked.

**Comment by AramZS** [comment]
@regan008 it won't become checked if you have previously saved a post unchecked, does that make sense?

**Comment by regan008** [comment]
@AramZS yes it does -- but it seems like its doing it for all posts. Even for posts that I've drafted after I turned the redirect setting on in preferences.

**Comment by AramZS** [comment]
But drafted and then edited it @regan008

**Comment by regan008** [comment]
@AramZS  Maybe I'm misunderstanding the expected action here, but I can't seem to get it to ever redirect without manually checking the box when redirect is on. Whether I edit the post or not.

**Comment by AramZS** [comment]
@regan008 Ok, here is the expected behavior set:
* Site Redirect Setting X 
  - Edit Draft/Post first time
  - Post Redirect Shows X
  - Save Post
  - Post Redirect Setting Saved to X
  - Post Redirects according to X
  - Post Redirect Setting Saved to Y
  - Save Post
  - Post Redirects According to Y

* Site Redirect Setting Y
  - Edit Draft/Post first time
  - Post Redirect Shows Y
  - Save Post
  - Post Redirect Setting Saved to Y
  - Post Redirects According to Y
  - Site Redirect Setting to X
  - Post Redirects According to Y
  - Edit Post
  - Post Setting Shows Y
  - Post Redirect Setting Saved to X
  - Save Post
  - Post Redirects According to X
  - Site Redirect Setting to Y
  - Post Redirects According to X

The state of the Redirect is set in stone in the Post regardless of changes in the Site Setting the first time you open up a post or draft and hit the Save/Publish/Update button. Once that is done no Site Setting changes will change the state of that post.

Does that make sense? Is that the behavior you are seeing?

**Comment by regan008** [comment]
@AramZS Yes that does but that is not what I'm seeing. When I have post redirect on and go to edit a new post draft the Post Redirect does not reflect the site setting.

**Comment by AramZS** [comment]
Will dig in.

**Comment by regan008** [comment]
@AramZS The redirect preference now matches what the site preference is. However, now when the site redirect preference is on and I turn redirect off within the post the post still redirects when published.

**Comment by regan008** [comment]
Confirmed. This is working now
