### ISSUE TITLE
Tags are not being passed thorough to draft from the nominations process.

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#499]

**Comment by AramZS** [comment]
Also: Create a user option to pass Folders through as either Tags or Categories

**Comment by regan008** [comment]
Seems like this is still not working.  The tags appear in the "item_tags" custom field but not in the actual Wordpress tags area.

![screen shot 2015-06-15 at 12 12 56 pm](https://cloud.githubusercontent.com/assets/4553057/8164591/fec7c3b0-1357-11e5-938d-3a16a90eb530.png)

**Comment by AramZS** [comment]
I think the problem is when sending directly to nomination.
