### ISSUE TITLE
Views list - toggle and add pagination

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#502]
So list would show:
List/Grid
Paginate/Infinite Scroll

**Comment by regan008** [comment]
@AramZS everytime I try to switch to paginate from all content I get this error: 

"The page at pfsample says:
PressForward has lost its connection to your server. Reload page and try again."

I'm assuming this is probably plugin related and not server related?

![screen shot 2015-02-17 at 10 08 40 am](https://cloud.githubusercontent.com/assets/4553057/6230345/fcfe489c-b68c-11e4-8bf7-346bfb1e3bfe.png)

I'm on chrome 40.0.2214.111 (64-bit) and Yosemite.

**Comment by regan008** [comment]
This seems to be happening sometimes, but not always.  Could it be an issue with our servers?

**Comment by lmrhody** [comment]
I'm having a different issue. When I select "list view" then select "infinite scroll" the view resets to grid. 
(Chrome, administrator role, Mac OS, pftesting install)

**Comment by lmrhody** [comment]
List view switches back to grid view after filtering (for example by starred).

**Comment by AramZS** [comment]
@regan008 Are you seeing this on any other set up? I'm thinking it may be a time out on this particular server, because I can't duplicate the bug.

**Comment by regan008** [comment]
@AramZS I just tested it locally and I can't replicate it.  It was happening on both pfsample and pftesting but those are on the same server. So maybe its just a server issue?

**Comment by AramZS** [comment]
@regan008 Very possibly. The error is caused when an AJAX message is submitted and the server doesn't respond (or responds with a false return). But when I looked into it, it seemed to save everything ok, even after throwing the error, a good sign that it is a server error. I'm trying to duplicate the error to double check.

**Comment by AramZS** [comment]
This seems to be a problem with a time out on the particular testing server. I'm taking the issue out of the milestone.

**Comment by regan008** [comment]
@AramZS I'm testing locally using a Wordpress install I set up on MAMP and I just got this error message again in firefox. 
![screen shot 2015-02-24 at 11 09 26 am](https://cloud.githubusercontent.com/assets/4553057/6353317/a1775c18-bc16-11e4-8dfd-f858dba30b87.png)
