### ISSUE TITLE
Amplify button not visible in List view. 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#508]

**Comment by regan008** [comment]
This looks like it is still an issue.  In list view, the popover drops down but is behind the next item and is only partially visible.

![screen shot 2015-02-17 at 10 35 44 am](https://cloud.githubusercontent.com/assets/4553057/6230886/1555a1b6-b691-11e4-8817-365a8d19b347.png)

**Comment by AramZS** [comment]
Confirmed, taking a look at this now.

**Comment by AramZS** [comment]
Freaking overflow property is the issue, this is an immense pain. Trying ways around it.

**Comment by AramZS** [comment]
Part 1 68dee812b36b44df85966df53df6870276e268d8
