### ISSUE TITLE
In-modal comments in Nominated page are not working. 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#511]

**Comment by AramZS** [comment]
@lmrhody I can't seem to duplicate this. What version of WordPress are you using? Can you duplicate the error?

**Comment by lmrhody** [comment]
It's on pfsample.chnm.org, which has 3.5.x from Monday installed. Check basecamp for login info.

**Comment by AramZS** [comment]
@lmrhody I just logged on to the site and it is working perfectly. If you are still seeing this problem, please list browser data, user, user level and send me a screenshot. Until then I'm removing from the milestone.
