### ISSUE TITLE
Nominate and draft buttons not turning green when clicked in reader view

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#517]
In the reader view in all content the nominate button can be clicked but it does not turn green.  However, upon returning to grid/list view the button is green and the item does show up in Under Review. 

Same thing in Under Review with the Draft button.  In reader view it can be clicked but does not turn green but once you return to list view the button is green and the item does appear in drafts. 

![screen shot 2015-02-17 at 11 07 46 am](https://cloud.githubusercontent.com/assets/4553057/6231738/91d54fa8-b695-11e4-8141-e14a05400da3.png)
![screen shot 2015-02-17 at 11 08 00 am](https://cloud.githubusercontent.com/assets/4553057/6231744/972c2ce2-b695-11e4-9a51-b8f5449c992f.png)
![screen shot 2015-02-17 at 11 08 08 am](https://cloud.githubusercontent.com/assets/4553057/6231746/9937d9aa-b695-11e4-9a54-acb613cb434d.png)

**Comment by lmrhody** [comment]
same problem here: using Chrome, Mac OSX, Administrator, pftesting install

**Comment by lmrhody** [comment]
Oh, but if you nominate in list view then go to reader view, the green does stick.

**Comment by AramZS** [comment]
Got it, the attribute is not being checked universally. I think I know the issue.

**Comment by AramZS** [comment]
Ok, I've created a  new methodology for making schema actions visible that is much cleaner from a code perspective. I think this will be a better way to go and it should solve all of these problems now and going forward. Definitely test all these schema actions, action buttons, etc...
