### ISSUE TITLE
'Add Comment' Button should disappear when Commenting Module is turned off

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#518]
When the commenting module is turned off in Preferences the "Add Comment" button should disappear. 
The button appears whether there are existing comments (from when the module was on) or not. It just appears to be a dead button.
![screen shot 2015-02-17 at 11 14 22 am](https://cloud.githubusercontent.com/assets/4553057/6231850/29183790-b696-11e4-8c66-d6e13797b41e.png)
![screen shot 2015-02-17 at 11 14 01 am](https://cloud.githubusercontent.com/assets/4553057/6231851/291863f0-b696-11e4-99f8-56bb7ba1b871.png)

**Comment by AramZS** [comment]
Resolved with f15d6e4ec0ccfcd5f66b46bdb57fd29871aff6b0
