### ISSUE TITLE
"Nominate This can not find your WP-Admin directory" when hosted on OpenShift Online

### ISSUE THREAD

**Issue by holmja** [PressForward/pressforward#522]
PressForward's "Nominate This" button opens a pop-up window with the error "Nominate This can not find your WP-Admin directory" when I try to use it with an installation of WordPress hosted on [OpenShift Online](https://www.openshift.com/). I have no idea why it can't find the WP-Admin directory, so please let me know what I can do/what information I can provide to help figure out why Nominate This doesn't work with an OpenShift hosted WordPress.

**Comment by lmrhody** [comment]
Hi Holmja, Thanks for letting us know that you were having trouble. Some additional information would help us to figure out what's going on for you.  Could you let us know some of the following information: 

Which version of WordPress are you using? 
Which version of the plugin do you have installed? 
Did you install the plugin from the WordPress plugin directory or from github? 
If you installed the PressForward plugin from github, did you move it from your OpenShift data directory on the gear ($OPENSHIFT_DATA_DIR) to the php/wp-content/plugins directory? There are some instructions on how to do this here: https://github.com/openshift/wordpress-example in case you haven't checked it into the proper directory. 

If moving the plugin to the plugins directory doesn't work, please let us know the answers to the other questions, and we'll look into it further. Thanks!

**Comment by holmja** [comment]
My current setup uses WordPress 4.1.1 and PressFoward 3.4.5 installed from WordPress's plugin directory, but I've been poking at this on my own for a while, so I've experienced this for a few versions of WordPress and PressFoward. The site is just so I can research PressForward for an article about it for Opensource.com, so the only other plugin installed is "jonradio Private Site". Other than changing WordPress's Permalink Settings to "Day and name" and enabling "Discourage search engines from indexing this site," the settings are unchanged from WordPress's defaults. It also doesn't seem to make any difference if I install PressForward via the plugin directory or clone the PressForward git repo.

I have an (almost) identical WordPress installation on my local testing virtual machine, which is a more traditional setup (Apache 2.4, MariaDB 5.5 and php 5.4 on CentOS 7) instead of OpenShift, and "Nominate This" works exactly as expected. The only real difference between the two is OpenShift's peculiarities, which the "Nominate This" feature can't seem to handle. Something about what OpenShift does to WP-Admin and PressForward's code for detecting WP-Admin aren't working together. Every other feature of PressForward works on my OpenShift installation.

**Comment by AramZS** [comment]
@holmja Hi, do you know if your WordPress configuration places the plugins directory any where outside of wp-content?

**Comment by AramZS** [comment]
Hi @holmja It looks like the folder configuration is a little non-standard, and that's what is causing the issue. I've issued a patch to cover more server configurations. You can download and re-install it from here - https://github.com/PressForward/pressforward/releases/tag/3.4.6

**Comment by holmja** [comment]
Thanks so much. Works like a charm now.
