### ISSUE TITLE
Last time feed checked option doesn't show unchecked feeds when sorted by. 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#525]

**Comment by AramZS** [comment]
@boonebgorges I duplicated your code for this, trying to do it the same way you did with last retrieved, but for some reason it seems to be leaving out the items without a date. I thought that by covering it with the OR meta_query I'd be find, but I've got to be missing something. https://github.com/PressForward/pressforward/blob/3.5.x/includes/admin.php#L1853

**Comment by boonebgorges** [comment]
Whoops, it looks like I broke this in WordPress: https://core.trac.wordpress.org/changeset/29964

Strictly speaking, what was working before in PF was kind of a hack. That WP changeset fixes it the way it probably should be. I believe the proper fix is to remove the 'meta_key' param - check out the commit I'm about to push up.

Side note: improved  orderby meta support is coming in 4.2. See https://core.trac.wordpress.org/ticket/31045
