### ISSUE TITLE
Changing sort options or folder filter option while in full screen drops you out of full screen

### ISSUE THREAD

**Issue by asmorton** [PressForward/pressforward#530]

**Comment by AramZS** [comment]
Oy. Need to save the fullscreen state as a URL variable I guess. Can we move this to next milestone? That's a big deal to code.

**Comment by AramZS** [comment]
After some investigation and testing I have determined this is technically impossible to solve in a UX satisfactory way. We will solve for this issue in the next full rebuild of the UI
