### ISSUE TITLE
Delete button sits on top of Nominate This helper text in list view

### ISSUE THREAD

**Issue by asmorton** [PressForward/pressforward#531]

**Comment by asmorton** [comment]
![screen shot 2015-02-23 at 12 28 53 pm](https://cloud.githubusercontent.com/assets/3477432/6332998/887724e2-bb57-11e4-8c6f-ca348ac0cbff.png)

**Comment by AramZS** [comment]
.list { .box-controls: { margin-top: -10px; } article { padding-top: 16px; }  }

**Comment by AramZS** [comment]
ff64ca13a6c36c6f2b0892a0762db0f897b6ddc2
