### ISSUE TITLE
Cannot move past page 2 in paginated view

### ISSUE THREAD

**Issue by asmorton** [PressForward/pressforward#532]

**Comment by AramZS** [comment]
Page title isn't changing either.

**Comment by AramZS** [comment]
(next page link doesn't output proper link)

**Comment by AramZS** [comment]
See: wp-admin/admin.php?page=pf-menu&pc=3

**Comment by lmrhody** [comment]
Another related issue is that when in paginate, the breadcrumb never advances beyond All Content > Page 1, even if you're on page 2.
