### ISSUE TITLE
The Info dropdown box appears offset from info button

### ISSUE THREAD

**Issue by jfbratt** [PressForward/pressforward#538]
The first time you click the info button, the dropdown "appears" to come from the star button. 
![screen shot 2015-02-23 at 1 25 50 pm](https://cloud.githubusercontent.com/assets/8570883/6334027/d7ef00fa-bb5f-11e4-8d08-0c58bf87e253.png)
If the user closes and reopens the info dropdown, it appears correctly.
![screen shot 2015-02-23 at 1 28 39 pm](https://cloud.githubusercontent.com/assets/8570883/6334037/e9376dca-bb5f-11e4-86e6-43034ea9ae2a.png)

**Comment by AramZS** [comment]
Resolved with e76fd7bcd720251d2a60a916fdc9c91b8eab3fdd
