### ISSUE TITLE
Unnominated Items still appear in 'Nominated'

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#547]
When an item is nominated in all content and then un-nominated by the same user the item never disappears from 'Nominated'.  If the nomination count is 0 it should disappear from 'Nominated'--right?

Here's a screenshot of the item showing up with 0 nominations in 'Nominated'

![screen shot 2015-02-24 at 10 53 47 am](https://cloud.githubusercontent.com/assets/4553057/6352904/f708c52a-bc13-11e4-94a1-7707a0bf3c7c.png)

**Comment by AramZS** [comment]
I'm going to resolve this, but I don't think that revoking all nominations should also remove posts created from that nomination, (so if it is already sent to draft, it will stay there even if the nomination disappears). Does that makes sense @regan008 ?

**Comment by regan008** [comment]
@AramZS I think that makes complete sense!
