### ISSUE TITLE
PC: Sorting window stays open and highlighted after selection

### ISSUE THREAD

**Issue by jfbratt** [PressForward/pressforward#549]
After selecting a sorting option in the all content, the drop down window remains open and the option selected. If I mouse over the drop down, the unselected options are highlighted when moused over. Occurs in all three major browsers.
![issue1](https://cloud.githubusercontent.com/assets/8570883/6353377/f682d250-bc16-11e4-810a-c9ee1a7ffaf1.png)

**Comment by AramZS** [comment]
Resolved.
