### ISSUE TITLE
Readability on Nominate This works differently for contributor vs. administrator

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#551]
So, on Firefox, I used the Nominate This bookmarklet to nominate a page from the web using a contributor-role account. Then I nominated the exact same page discovered the exact same way with the Nominate This bookmarklet with the administrator-role account.  I've pasted the results below.  It looks like the Nominate This for contributors is using an old readability methodology compared to the Nominate This script for administrative roles? Maybe? Done on pfsample

Nominate this screen as administrator:
![screen shot 2015-02-24 at 11 26 50 am](https://cloud.githubusercontent.com/assets/1395793/6353628/711fb3e2-bc18-11e4-9e0c-4cb8a3fcfdf2.png)

Nominate this as contributor: 
![screen shot 2015-02-24 at 11 26 23 am](https://cloud.githubusercontent.com/assets/1395793/6353635/80243700-bc18-11e4-92e9-78a3da8f3815.png)

**Comment by AramZS** [comment]
This should be resolved, please test.

**Comment by regan008** [comment]
Confirmed.
