### ISSUE TITLE
Info button not working in full screen

### ISSUE THREAD

**Issue by jfbratt** [PressForward/pressforward#554]
User can select the info button but the drop down does not appear. If the user exits the full screen after only selecting the info box once, the drop down appears to be "underneath" the full screen
![issue1](https://cloud.githubusercontent.com/assets/8570883/6354308/8e3b9aaa-bc1c-11e4-9f47-3b092a5e622e.png)

**Comment by regan008** [comment]
@AramZS I cannot get the info button to work at all now in full screen. It won't generate a pop up at all in both chrome and firefox.

**Comment by AramZS** [comment]
I'm dropping fixing this to 4.3 then, as dealing with the full-screen interactions is complex and I'd rather not have it delay the release.

**Comment by boonebgorges** [comment]
Works for me, maybe from recent Bootstrap updates.
