### ISSUE TITLE
PC Firefox: Read View and All Content became unresponsive

### ISSUE THREAD

**Issue by jfbratt** [PressForward/pressforward#556]
When opening Read View under the All Content page in Firefox on a PC, the page becomes unresponsive. Cannot close the view using either the "X" at the top or the close button. Also cannot scroll the page or leave a comment. Does allow the user to star or nominate. By clicking on the previous articles link, I was dropped out of Read View onto the All Content page. Links were unresponsive, could not scroll on through the posts or switch to any other pages. 
![issue1](https://cloud.githubusercontent.com/assets/8570883/6355344/5868d526-bc23-11e4-8676-18c32208112c.png)

**Comment by AramZS** [comment]
Please re-test and copy in the AJAX response, see instructions at https://github.com/PressForward/pressforward/wiki/testing-tools

**Comment by lmrhody** [comment]
I was unable to duplicate this issue. Just checked in with jfbratt and he's going to retest before we meet today.
