### ISSUE TITLE
Nominate This doesn't drag and drop w/ touch interface on Windows 8 in Firefox

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#557]
Using Firefox with Windows 8 on a Surface doesn't allow users to use touch to drag the Nominate This bookmarklet up onto the bookmarks bar.

**Comment by AramZS** [comment]
Test with Press This as well.

**Comment by AramZS** [comment]
I actually believe this was resolved in a recent Firefox release. Please retest.

**Comment by regan008** [comment]
@AramZS I don't think we have anyone here who has a surface anymore so I'm not sure we can test this

**Comment by AramZS** [comment]
@regan008 Ok. It worked on my Surface with Firefox so I'm calling this closed.
