### ISSUE TITLE
Same items showing double in List View in All Content

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#558]
This is happening on both Mac and PC on Firefox and Chrome, I'm seeing duplicates of some, but not all feeds.  For example, Washington Post and Wired are the most common offenders.  The items list 2 times rather than 1 in the All Content feed items list as below: 
![capture](https://cloud.githubusercontent.com/assets/1395793/6368785/0c4ddcfa-bcae-11e4-9484-f3bb500ee872.PNG)

**Comment by AramZS** [comment]
I cannot duplicate this. Try and patch to the latest and see if it still occurs. It might have been a scroll problem.

**Comment by AramZS** [comment]
@lmrhody I wanted to check in on this again, as I think it is related to the infinite scroll/pagination issues that I fixed. Is this still happening?

**Comment by lmrhody** [comment]
I have not been able to duplicate today. I agree that it's related to the infinite scroll/pagination issue.
