### ISSUE TITLE
Send to draft from Amplify button not working on All Content in Windows 8 Firefox

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#559]
When I'm sending an item to draft from the Amplify button -- both in reader view and from list/grid view -- the item never actually sends to draft. It just sits with the spinning scroll bar.  I've stopped it, clicked into the posts list to see if it's just spinning and moving the item, but it's not. 
![sendtodrafrt](https://cloud.githubusercontent.com/assets/1395793/6368953/9c2627b4-bcaf-11e4-99b6-a88815aecc9b.PNG)

**Comment by lmrhody** [comment]
Same item did send by using nominate button, then sending to draft from Nomination menu.

**Comment by AramZS** [comment]
Please re-test and copy in the AJAX response, see instructions at https://github.com/PressForward/pressforward/wiki/testing-tools

**Comment by lmrhody** [comment]
Retested and there were no issues.
