### ISSUE TITLE
Toggle Visibility of Archived filter not working for me on Firefox Windows 8

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#560]
The filter > toggle visibility of archived does not reveal archived items when clicked the first time. I'm finding this filter really difficult to understand from a user perspective. Maybe the options in this would be clearer if they read: View: All / Active / Archived (where Active means items that have not been archived). Since Archived is site-wide, the next iteration of this feature would be View >  All / Active / Archived / Hidden.  In this case, there'd be the extra feature of viewing all the hidden items, but there wouldn't be a need for "unhidden" because that would just be handled by the "active" option...

**Comment by AramZS** [comment]
Please re-test and copy in the AJAX response, see instructions at https://github.com/PressForward/pressforward/wiki/testing-tools

**Comment by lmrhody** [comment]
There are no actions in firebug when I select "toggle visibility of archived" from "Filter" in Nominated. Nothing when I select "toggle visibility of archived" happens in Firebug, so I have nothing to cut and copy here.  What do you think about my suggestions for changing the filter labeling a bit? I'm finding the wording in the menu confusing.

**Comment by AramZS** [comment]
@lmrhody That button actually doesn't trigger an AJAX anything now that I look at it. Turns out I was just watching it in JS the wrong way. Fixed now. 

How would you want the wording changed?
