### ISSUE TITLE
In Contributor role nomination causes constant scrolling progress bar in Firefox Windows 8 

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#561]
When nominating an item as a contributor in Firefox Windows 8 the progress appears and spins as if the nomination is in progress, but the bar never disappears to indicate that the nomination was successfully received.  The item does appear in the "Nominated" content area for the administrator, though.  This may cause frustration for users who want the gratification of seeing the progress bar disappear. 
![bingewatching](https://cloud.githubusercontent.com/assets/1395793/6369752/222da5ce-bcb7-11e4-9570-894d45242ca6.PNG)

**Comment by AramZS** [comment]
I cannot duplicate this, what are the menu settings?

**Comment by AramZS** [comment]
Please re-test and copy in the AJAX response, see instructions at https://github.com/PressForward/pressforward/wiki/testing-tools

**Comment by lmrhody** [comment]
Retested and no hang-up.
