### ISSUE TITLE
Scroll location reset when opening Comments from list/grid view

### ISSUE THREAD

**Issue by jfbratt** [PressForward/pressforward#563]
In both Safari and Chrome: when the user opens the comments pop up box from the list or grid view, the page/scroll location is shifted up.

**Comment by AramZS** [comment]
@lmrhody There's a whole set of problems that have to be solved to deal with the auto scroll problems, if there's no objection, I'd like to move this to the next milestone.

**Comment by lmrhody** [comment]
No objections. So agreed ;-)

**Comment by AramZS** [comment]
Same as #444 - I think it is resolved.

**Comment by regan008** [comment]
This is resolved.
