### ISSUE TITLE
'Save Inactive' in edit feed page saves feeds as 'Pending' 

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#564]
![screen shot 2015-02-25 at 12 15 58 pm](https://cloud.githubusercontent.com/assets/4553057/6375944/8aa3ef74-bce8-11e4-8a66-503259dab9be.png)
Once 'Save Inactive' is clicked within the edit feed screen it briefly displays as 'saving pending':
![screen shot 2015-02-25 at 12 16 14 pm](https://cloud.githubusercontent.com/assets/4553057/6375947/8f845998-bce8-11e4-9ffa-45ed7cf51140.png)
The feed then shows up as pending:
![screen shot 2015-02-25 at 12 16 40 pm](https://cloud.githubusercontent.com/assets/4553057/6375966/b1cdb59e-bce8-11e4-997d-24f36c56ca93.png)

See screen recording here: https://drive.google.com/file/d/0B9QreyVkdrH1Rm5yck43X2FReUU/view?usp=sharing

**Comment by AramZS** [comment]
Need to change Pending to Inactive in all situations.
