### ISSUE TITLE
Feed expand off the screen in Folders Pane because it doesn't scroll

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#565]
In All Content the folders pane doesn't scroll if there are more listings than fit on the screen. The feeds/folders expand off the screen and there is no way to scroll to the bottom of the list.

For example, in this screenshot the last feed shown is Open Culture but there should be about six more that don't show up here. Scrolling down just moves the All Content page--there is no way to scroll down the list of folder.
![screen shot 2015-03-02 at 11 22 26 am](https://cloud.githubusercontent.com/assets/4553057/6444956/028499c8-c0cf-11e4-90c1-bbed100372c0.png)

**Comment by AramZS** [comment]
@regan008 That pane scrolls separately from the main one. If you are on a Mac laptop and Safari it doesn't show any of the scroll bars by default. You should be able to move your mouse and use the scroll motion on that pane.

**Comment by asmorton** [comment]
We tested this a little more, and found that when the page is re-sized, the last item on the list changes. There's an additional item listed when the width of the page is around 1074px: 
![screen shot 2015-03-02 at 12 30 08 pm](https://cloud.githubusercontent.com/assets/3477432/6446299/21c382b4-c0d8-11e4-82fa-7d25dba305b7.png)
vs
![screen shot 2015-03-02 at 12 30 18 pm](https://cloud.githubusercontent.com/assets/3477432/6446302/25536610-c0d8-11e4-92b7-7d1bb201b23f.png)

**Comment by AramZS** [comment]
Yeah, I'm seeing that too, it looks like some of the items are just falling off the page. Taking a look at best way to fix it now.

**Comment by regan008** [comment]
@AramZS  This solved the feeds changing based on window size but it still gets slightly cut off.  We think it might just need padding on the bottom  Increasing padding-bottom from 30 to 75 works in my browser.

![screenshot 2015-03-02 13 17 54](https://cloud.githubusercontent.com/assets/4553057/6447293/28563598-c0df-11e4-8dee-9eb753f12547.png)
