### ISSUE TITLE
PC: All content Infinite Scroll in List view moves the panel of buttons to the left on loading

### ISSUE THREAD

**Issue by jfbratt** [PressForward/pressforward#566]
This occurs on a PC in all three browsers. When viewing All Content in List view and with Infinite Scroll selected, when the user reaches the bottom and the next "page" is loaded, the panel of buttons (star, Info, Nominate etc.) is moved to the left side of the item. 
![issue1](https://cloud.githubusercontent.com/assets/8570883/6446922/76cc22bc-c0dc-11e4-9b49-8031d4a3d906.png)

**Comment by AramZS** [comment]
Also duplicates occur when the feeds in query move down (check to insure the action bar doesn't already exist in the unit)
