### ISSUE TITLE
Add feeds error handling

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#572]
I tried (knowing it would fail) to add an opml link using the Add Feed field on the Add Feeds panel.  The page proceeded to allow me to submit and I got the following message: 
![screen shot 2015-03-03 at 11 25 38 am](https://cloud.githubusercontent.com/assets/1395793/6466806/4126a38c-c198-11e4-9abc-b031e0a3f16a.png)

I think that the broken feed message needs to state very clearly: Add feed failed. The feed link that you have submitted is not working. Please check that you have entered it correctly. 

The second thing is that it seems to still add the feed to the feed list.  My question is, should it? If the first time you add a feed and the feed throws an error, shouldn't it, by default, not be added to the list?

**Comment by AramZS** [comment]
Yes, but we need to add Edit Feed message for broken feeds on Add action. Also the option to delete it from the response message.
