### ISSUE TITLE
Comment box disappearing in Nominate > Reader View

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#575]
When opening items in Reader View from the Nominated page, items that don't already have comments do not have comment boxes appearing in them. I discovered this logged in as an administrator on pfsample. This happened while testing the release candidate.

**Comment by lmrhody** [comment]
chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js Failed to load resource: net::ERR_FAILED
http://feeds.washingtonpost.com///www.washingtonpost.com/wp-apps/imrs.php?s…ngtonPost/2015/02/09/Education/Images/Testing_5_Things-083da-279.jpg&w=480 Failed to load resource: the server responded with a status of 404 (Not Found)
http://feeds.washingtonpost.com///www.washingtonpost.com/wp-apps/imrs.php?s…gtonpost.com/news/local/wp-content/uploads/sites/2/2015/02/black.jpg&w=480 Failed to load resource: the server responded with a status of 404 (Not Found)
chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED
http://feeds.washingtonpost.com///www.washingtonpost.com/wp-apps/imrs.php?s…post.com/news/local/wp-content/uploads/sites/2/2015/02/hispanic1.jpg&w=480 Failed to load resource: the server responded with a status of 404 (Not Found)
http://feeds.washingtonpost.com///www.washingtonpost.com/wp-apps/imrs.php?s…post.com/news/local/wp-content/uploads/sites/2/2015/02/hispanic2.jpg&w=480 Failed to load resource: the server responded with a status of 404 (Not Found)
http://feeds.washingtonpost.com///www.washingtonpost.com/wp-apps/imrs.php?s…e_908w/2010-2019/Wires/Images/2015-02-23/AP/Caught_Tanking-03182.jpg&w=480 Failed to load resource: the server responded with a status of 404 (Not Found)
chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://hfaagokkkhdbgiakmmlclaapfelnkoah/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js Failed to load resource: net::ERR_FAILED
chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js Failed to load resource: net::ERR_FAILED
views.js:462 Load complete.

**Comment by lmrhody** [comment]
sorry, here's the item: http://feeds.plos.org/~r/plosone/PLoSONE/~3/bghBNq9P0IE/info%3Adoi%2F10.1371%2Fjournal.pone.0118314

**Comment by AramZS** [comment]
@lmrhody I can't duplicate this error and judging by the info, it appears that the ChromeCast plugin is failing and that is what is causing this error. Give it a try on another browser and if you are still seeing the issue we'll re-open this.
