### ISSUE TITLE
Archiving a nomination causes the read view to crash. 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#576]

**Comment by AramZS** [comment]
In Opera, on Mac

**Comment by AramZS** [comment]
This should be resolved with the latest release. Can you double check before I close this?

**Comment by regan008** [comment]
@AramZS It appears that reader view isn't working at all in Opera on Mac in the latest release.

**Comment by AramZS** [comment]
@regan008 More details needed. You mean the model? In which view? I use Opera on Mac a lot and didn't see this. Is there a console error?

**Comment by regan008** [comment]
Gah, upon further testing it seems this is yet another bug with the user management plugin causing a conflict. Not sure why but I'll look into it.

However, archiving a nomination still does cause read view to act oddly see screenshot
![screen shot 2016-01-14 at 9 52 36 am](https://cloud.githubusercontent.com/assets/4553057/12327444/95d5c9e8-baa4-11e5-8eca-76db6bc7bc21.png)
 below.
