### ISSUE TITLE
Allow Feeds to have an Author

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#582]
and set that author as feed item author when the feed item author is not available.

**Comment by boonebgorges** [comment]
I like this idea. Let's bundle with #1187.

**Comment by boonebgorges** [comment]
I've built the tool. It looks like this:

![Screenshot_2024-12-11_19-01-39](https://github.com/user-attachments/assets/b26dfd96-d7a7-4551-9db7-618a6e038bfc)

The initial value is populated at the time of feed subscription. Feeds don't always (or even usually) have an author, but SimplePie uses a heuristic to sniff one out where available. See https://github.com/WordPress/wordpress-develop/blob/9104190b6d36c2959f652e0b65bf5bb7af42ffcc/src/wp-includes/SimplePie/src/SimplePie.php#L2432-L2492. If a value is found, the 'name' property is saved with the feed object. This value is then editable when editing the feed - see the screenshot above. When a feed item is ingested, if that item doesn't have an associated author, then the feed's author is used as a fallback.
