### ISSUE TITLE
Set feed to ignore all alerts and never go inactive

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#583]

**Comment by AramZS** [comment]
On an individual feed.

**Comment by AramZS** [comment]
Add to Quick Actions.

**Comment by regan008** [comment]
Testing this now, I'll get back to you @AramZS

**Comment by regan008** [comment]
This appears to be working. @AramZS Did you intend for this option to be visible in Quick Actions as well? Its not showing up there but does seem to be working.

**Comment by AramZS** [comment]
@regan008 The original spec said to put it in there, but I realized that we have a LOT going on in there already and this seemed to be such an edge case I wasn't sure it made sense. Should it go into quick actions as well?

**Comment by regan008** [comment]
@AramZS Yeah, I think you're probably right. There is a lot in that panel already. Lets leave it out and then if we change our mind down the road we can add it back in.

**Comment by regan008** [comment]
So I'll go ahead and close this as it appears to be working.
