### ISSUE TITLE
pfsample.chnm.org logs show possible looping issues. 

### ISSUE THREAD

**Issue by rsanc77** [PressForward/pressforward#586]
On the logs for this site the following keeps popping up. at least 1500 per day. If this is an issue with the server please help me resolve it. Thanks you 
 "GET /?press=forward&nonce=fdb34a69ff05ecd0972bdd84d0f4905a HTTP/1.0" 200 - "-" "WordPress/4.1.1; http://pfsample.chnm.org"
129.174.10.22 - - [25/Mar/2015:03:25:28 -0400] "GET /?press=forward&nonce=575f4f1ddd4ea7d849eba441c91f63ff HTTP/1.0" 200 - "-" "WordPress/4.1.1; http://pfsample.chnm.org"
129.174.10.22 - - [25/Mar/2015:03:25:41 -0400] "GET /?press=forward&nonce=b9e5515e7b3dce229b17e6f7ffe886a0 HTTP/1.0" 200 - "-" "WordPress/4.1.1; http://pfsample.chnm.org"
129.174.10.22 - - [25/Mar/2015:03:25:36 -0400] "GET /?press=forward&nonce=c07885c6efd7e8355b8881c92df26924 HTTP/1.0" 200 - "-" "WordPress/4.1.1; http://pfsample.chnm.org"

**Comment by AramZS** [comment]
Expected behavior
