### ISSUE TITLE
"Nominated by" Usernames Repeat 

### ISSUE THREAD

**Issue by asmorton** [PressForward/pressforward#587]
We've only had this happen once, and on a piece that came through the bookmarklet. Other items coming through the bookmarklet aren't having the same problem. 
![screen shot 2015-03-30 at 1 48 48 pm](https://cloud.githubusercontent.com/assets/3477432/6902780/fbdea48a-d6e3-11e4-82fd-d61dd58a483e.png)

**Comment by AramZS** [comment]
@asmorton On the latest version? It shouldn't allow that, I'll look into it.
