### ISSUE TITLE
Nominate This doesn't work with PSMag

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#588]
Example: http://www.psmag.com/nature-and-technology/your-sock-company-is-ridiculous-just-give-up-now

**Comment by AramZS** [comment]
This should be resolved, please test.

**Comment by AramZS** [comment]
This is still not resolved. Not sure why. Needs to be fixed.

**Comment by mAAdhaTTah** [comment]
FWIW, Pocket also has problems with PSMag.

**Comment by AramZS** [comment]
Huh. Weird.

**Comment by jccatalano** [comment]
Issue is resolved with the latest version of PF.
