### ISSUE TITLE
Document item_added_date

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#593]
Date item was added to the parent feed (not always date published)

**Comment by regan008** [comment]
Hey @AramZS I'm in the process of writing the change log. Could you expand on what this issue refers to?

**Comment by AramZS** [comment]
@regan008 Oh, this was just reminding me to add something to the Wiki devbook

**Comment by regan008** [comment]
Ah ok -- I'll take it out of the changelog list then!
