### ISSUE TITLE
‘Load more items’ not working

### ISSUE THREAD

**Issue by coblezc** [PressForward/pressforward#597]
In the Nominated tab, when you scroll down to the bottom of the page, it won’t load more items. This problem appeared after we updated to Wordpress 4.2.1.

**Comment by lmrhody** [comment]
Thanks for letting us know!

**Comment by AramZS** [comment]
@coblezc After significant testing I cannot duplicate this problem. Is any response occurring? Is the loading icon appearing? Is it going away or just staying there? Can you see an error appearing in the console? https://developer.chrome.com/devtools/docs/console

**Comment by AramZS** [comment]
@regan008 Can you investigate this? Thanks

**Comment by coblezc** [comment]
Thank you, @AramZS, for investigating. The issues has recently resolved itself, but we'll let you know if it comes back.

**Comment by regan008** [comment]
@AramZS I wasn't able to replicate the issue either so I think this is closed unless the issue reappears.
