### ISSUE TITLE
Items from feeds in OPML Subscriptions aren't generating correct metadata

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#602]
When a OPML file is subscribed to PF is generating items that don't have the correct metadata.  Rather than listing the post title, author, and feed name, the plugin is listing the title of the feed as the title of an item and then listing the source as "OPML Subscription at http://www.inoreader.com/reader/subscriptions/export/user/1005688124/label/Programming". The content of the item, however, seems to be from a post in the feed but the title and other metadata just isn't correct.
 
It seems like maybe the feed metadata isn't being parsed correctly? 

Here are a few screenshots: 

![screen shot 2015-06-01 at 3 56 26 pm](https://cloud.githubusercontent.com/assets/4553057/7921932/ea4ac54a-0876-11e5-92eb-3c2618240f1d.png)
![screen shot 2015-06-01 at 3 49 49 pm](https://cloud.githubusercontent.com/assets/4553057/7921933/ea4ccb42-0876-11e5-9902-80ab2f6413db.png)
![screen shot 2015-06-01 at 3 56 36 pm](https://cloud.githubusercontent.com/assets/4553057/7921934/ee29e0a6-0876-11e5-967a-b34dd50f62d4.png)
![screen shot 2015-06-01 at 3 56 48 pm](https://cloud.githubusercontent.com/assets/4553057/7921936/f2b89fea-0876-11e5-9781-1e0e00bc5dce.png)

**Comment by regan008** [comment]
Actually, it does seem like the posts are being pulled in properly except for a few. It looks like for each item in an opml one item is being generated that has the feed name as the title and incorrect metadata but real post content. These all have actual post content but the metadata isn't correct. 
![screen shot 2015-06-01 at 4 06 23 pm](https://cloud.githubusercontent.com/assets/4553057/7922138/2de9af22-0878-11e5-8769-2b0c04acce8e.png)
![screen shot 2015-06-01 at 4 10 17 pm](https://cloud.githubusercontent.com/assets/4553057/7922211/bd06a67e-0878-11e5-8e17-75ae870ee384.png)

**Comment by AramZS** [comment]
This is actually expected behavior, the addition of a feed to the OPML file should create a Feed Item saying that an RSS feed has been added to subscriptions. The main problem is that it is making it readable when it should be marked already readable. That should now be resolved. 

There is another issue which is that these created posts should be totally eliminated when the OPML feed is deleted. I'll have to look into that.

**Comment by AramZS** [comment]
This should now be resolved with the upgrade to complete deletion for OPML feeds.

**Comment by AramZS** [comment]
Err, last commit was for #620
