### ISSUE TITLE
Feeds in an OPML Subscription are duplicated in Folder List

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#603]
Feeds from an OPML are showing up twice in the folder structure.  When clicked, the content only appears for one of the two folders.
![screen shot 2015-06-02 at 12 32 47 pm](https://cloud.githubusercontent.com/assets/4553057/7941282/311bfff4-0924-11e5-8228-d3619718f7ac.png)
![screen shot 2015-06-02 at 12 37 26 pm](https://cloud.githubusercontent.com/assets/4553057/7941281/311bcc50-0924-11e5-81c6-4fb52ffb0c0b.png)
![screen shot 2015-06-02 at 12 36 30 pm](https://cloud.githubusercontent.com/assets/4553057/7941283/311dba4c-0924-11e5-98bf-cb8dfcc6a945.png)

**Comment by AramZS** [comment]
Do those feeds show up twice in the subscription area?

**Comment by regan008** [comment]
No they don't. They only duplicate in the folder listing

**Comment by regan008** [comment]
The folder list in the folders panel also shows twice the number of feeds a folder should have. The travel folder should only have 4 feeds and the programming folder should only have 6 feeds. 
![screen shot 2015-06-02 at 1 59 19 pm](https://cloud.githubusercontent.com/assets/4553057/7942966/99dac38a-092f-11e5-836f-5009768eea7a.png)

**Comment by AramZS** [comment]
Can you double check the Subscribed Feeds area to see if they show up and if they have the same value in the feedsURL meta?

The problem with relying on the count is that it seems to count items in the Trash, which may screw with these numbers if you are testing by adding and deleting items.

**Comment by regan008** [comment]
They are just showing up once in the subscribed feeds area.

I've only deleted one subscribed feed so far and I'm seeing this for all
the feeds regardless of whether or not they've been deleted so that doesn't
seem to be the issue.

**Comment by AramZS** [comment]
I think this may be resolved with the latest patch. Be aware that I think Feeds stay in that area until they are removed from the trash.

**Comment by AramZS** [comment]
And also, a Feed can be 'duplicated' if it exists in the Trash, as there can be a version in the Trash and one not in the trash.

**Comment by AramZS** [comment]
I think this may also be related to #606

**Comment by AramZS** [comment]
I believe this will be resolved when merging OPML subscribe with branch with the 3.6.x branch.
