### ISSUE TITLE
Outbound OPML doesn't display

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#610]
When the link to the OPML subscription list is clicked, the page that appears is blank except for a "1".  The OPML list only appears if you view the page source. Shouldn't it be displaying the code without having to view the page source?

![screen shot 2015-06-15 at 11 13 38 am](https://cloud.githubusercontent.com/assets/4553057/8163181/a6c14608-134f-11e5-83b0-b6df9bd97fde.png)
![screen shot 2015-06-15 at 11 13 47 am](https://cloud.githubusercontent.com/assets/4553057/8163186/a8470b8e-134f-11e5-8894-443e7b462cb8.png)

**Comment by regan008** [comment]
Also, it appears that other feed readers are not able to find the feed with the link generated in Tools.

**Comment by AramZS** [comment]
What other feedreaders are you using? So I can debug.

**Comment by regan008** [comment]
So it isn't working in Inoreader but it does seem to be working in Feedly. I'm not sure why it would work in one and not the other.  It seems like inoreader isn't recognizing that it is a feed. Here are screenshots:
![screen shot 2015-06-15 at 2 09 02 pm](https://cloud.githubusercontent.com/assets/4553057/8166805/36330a3e-1368-11e5-8550-51e70e88d4e9.png)
![screen shot 2015-06-15 at 2 08 37 pm](https://cloud.githubusercontent.com/assets/4553057/8166806/36332780-1368-11e5-81c7-5d0efa746821.png)

**Comment by regan008** [comment]
Is there another feed reader you would suggest I test with?
