### ISSUE TITLE
Parent Folders in Nominated don't display nominated items from child folders

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#611]
When filtering using folders in "nominated," the parent folder does not display content from child folders that is nominated. 

![screen shot 2015-06-15 at 11 56 42 am](https://cloud.githubusercontent.com/assets/4553057/8164253/d54424fe-1355-11e5-9411-e753e2adc207.png)
![screen shot 2015-06-15 at 11 56 57 am](https://cloud.githubusercontent.com/assets/4553057/8164254/d54970c6-1355-11e5-81f4-c4e41aabc8a0.png)

**Comment by AramZS** [comment]
You mean child feeds, right?

**Comment by AramZS** [comment]
Huh, this is def with the latest version?

**Comment by regan008** [comment]
Yes child feeds.  And yeah its the latest version -- I pulled it around 11 this morning.

**Comment by AramZS** [comment]
This should be resolved with the meta-fix. I can not duplicate after the fix.
