### ISSUE TITLE
Deleting an OPML subscription does not delete the folder created on import

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#612]
When deleting an OPML subscription the folder that is created on import does not get deleted. Related to #604

**Comment by AramZS** [comment]
It is not set up to do that right now. I don't think it should be, after creating a folder through OPML it might be used on feeds you add later outside of the OPML. Proposed wontfix.

**Comment by AramZS** [comment]
On OPML folder delete check for empty folders, delete those folders.

**Comment by AramZS** [comment]
Testing this will require new nominations.
