### ISSUE TITLE
Nominate This styling broken

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#613]
The styling of the Nominate This bookmarklet is broken.  Right now, the bookmarklet page opens with no left margin, margins internal to the page are also off (none on left sometimes, too much on right). Page that the user is directed to upon submission only has the title of the site as a link, not the previous message of: "Thank you. Your nomination has been successfully submitted to <name of site>."

**Comment by AramZS** [comment]
add margins

**Comment by AramZS** [comment]
I think this is resolved @lmrhody ?

**Comment by lmrhody** [comment]
When you get a moment this week, could you check the new Nominate This bookmarklet styling and make sure that it's in keeping with partners' expectations? You can find it on the pftesting site. 
Thanks!

**Comment by slwestcott** [comment]
Sure!

On Mon, Oct 12, 2015 at 2:32 PM, Lisa Rhody <notifications@github.com>
wrote:

> When you get a moment this week, could you check the new Nominate This
> bookmarklet styling and make sure that it's in keeping with partners'
> expectations? You can find it on the pftesting site.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PressForward/pressforward/issues/613#issuecomment-147485064>
> .
>



-- 
Stephanie Westcott, Ph.D.
Research Assistant Professor
Co-Project Director, PressForward Project
Managing Editor, *Journal of Digital Humanities*
<http://journalofdigitalhumanities.org/>, *Digital Humanities Now*
<http://digitalhumanitiesnow.org/>
Roy Rosenzweig Center for History and New Media
George Mason University
4400 University Drive
Fairfax, VA 22030
westcott.chnm@gmail.com

**Comment by slwestcott** [comment]
Looks great - love the options and I think it's all clear and easy to find.
