### ISSUE TITLE
Tools page layout

### ISSUE THREAD

**Issue by lmrhody** [PressForward/pressforward#616]
We'd like to switch the Tools page to the same tabbed layout and styling as the Preferences page. 

There should be 3 sections: Nominate This / Refresh / Outbound OPML

**Comment by AramZS** [comment]
Trying this with some alternate better looking titles, but we can switch back.

**Comment by AramZS** [comment]
Assigned out for approval of new titles.

**Comment by lmrhody** [comment]
It looks AWESOME!!!!
