### ISSUE TITLE
Feeds in Folders Showing up Multiple Times in All Content

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#618]
The feeds in are showing up multiple times in the Folders panel of All Content. The feed isn't in there twice and only one of the two links has content.  Is it possible that some reference to this feed isn't getting deleted in the database? I'm not sure why it is doing this for some but not all the feeds. Might be related to #617

**Comment by AramZS** [comment]
Which OPML are you seeing this on?

**Comment by regan008** [comment]
@AramZS  It was doing it consistently for every opml I added last week. Here are two examples: 
http://www.inoreader.com/reader/subscriptions/export/user/1005688124/label/Gizmos
http://www.inoreader.com/reader/subscriptions/export/user/1005688124/label/Programming

You can see it in pftesting -- I think you have a login for that site. If not I can create you one if it would help.

**Comment by AramZS** [comment]
Folders are showing posts which are created when new Feeds are added.

**Comment by AramZS** [comment]
I believe this to be patched, but I think an old version of the plugin that we are testing had this broken and so there are a bunch of feeds that were incorrectly created. Let's try wiping out the feeds and feed items in the site where this is happening and rebuild some feeds and see if the problem comes back.

**Comment by regan008** [comment]
@AramZS Testing it right now on my local server and on pftesting. It doesn't seem to be duplicating now on my local install but there are no items showing up when I try to filter even though they do appear in All Content. 
![screenshot 2015-07-01 08 55 49](https://cloud.githubusercontent.com/assets/4553057/8454952/08e104b4-1fcf-11e5-881f-03d81916f819.png)

**Comment by AramZS** [comment]
It could be that something remains there, yes. That might be the problem. If I made a particularly bad error in one of the previous things to test it could be still in there. 

I'm not sure why they wouldn't show up in filtering. What's the query attached to the end of the URL, after the `?` ? What are you trying to filter by? You can't filter by OPML feed right now, I don't think, only by folder and feed.

**Comment by AramZS** [comment]
Please test this, it should be resolved.

**Comment by regan008** [comment]
@AramZS It seems to be working now!

**Comment by AramZS** [comment]
Awesome!
