### ISSUE TITLE
Confirm that manipulating post type and status in the options area works both together and independently

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#628]
We have added the ability to assign the default next step from Nominations to different post types and statuses ( #512 ).

Components: Settings -> Site Options -> 2x Option Pulldowns. 
Tasks: 
A:
 - Setting to a different post type (example: page)
 - Send nomination to next step 
B:
 - Setting to a different post status (example: publish)
 - Send nomination to next step
C: 
 - Setting to a different post status
 - Setting to a different post type
 - Send nomination to next step. 
Expected Results:
A: A post of the full nomination and nomination metadata with the new post type
B: A post of the full nomination and nomination metadata with the new post status
C: A post of the full nomination and nomination metadata with the new post type and status

**Comment by regan008** [comment]
@AramZS These all seem to work. Tried every combination and found no problems.

**Comment by AramZS** [comment]
Awesome. I've added to the documentation and given @douglaslinsmeyer the appropriate props in the drafted release.
