### ISSUE TITLE
Fatal Error After Installation

### ISSUE THREAD

**Issue by eolson3** [PressForward/pressforward#633]
From a PressForward user:

"In the first press forward installation, i had some problems with the theme installed.

So i uninstalled pressforward, changed theme, and reinstalled press forward,

After that i started receiving the below error, when trying to activate the plugin

"Fatal error: Cannot redeclare dump_html_tree() (previously declared in /home/…./wp-content/plugins/lfjmonetizeme/inc/simple_html_dom.php:0) in /home/…./wp-content/plugins/pressforward/lib/pf_simple_html_dom.php on line 108”

for privacy reasons, the path was shortened."

----------
Any thoughts?

Thanks,

Eric

**Comment by AramZS** [comment]
Added a patch to resolve this in upcoming 3.6.x release.

**Comment by eolson3** [comment]
Thanks, Aram.
