### ISSUE TITLE
Large Number of Feeds causes fatal error in All Content and Subscribed Feeds

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#637]
I'm getting a fatal error on PFTesting. This is the install that has at least 7-900 feeds (or more) that we were using to test the delete functionality in #604. The error is appearing on the Subscribed feeds and the All Content panels but is referencing different WordPress files. It isn't happening on any of the other pages so I'm guessing it probably has something to do with the large number of feeds in the site? 

* Subscribed Feeds Page: "Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in /websites/pftesting/www/wp-includes/meta.php on line 824"
* All Content: Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes) in /websites/pftesting/www/wp-includes/wp-db.php on line 2223

**Comment by AramZS** [comment]
I'm not able to duplicate this. Can you see anything in the log?

**Comment by regan008** [comment]
There isn't a log for this test site apparently. I'll add one right now and check back on it in a bit.

**Comment by regan008** [comment]
I'm going to close this as I think its probably not a big deal.
