### ISSUE TITLE
trouble with Nominate Feeds from Bookmarklet

### ISSUE THREAD

**Issue by kelle** [PressForward/pressforward#640]
None of these feeds were successfully added as drafts when nominated via the bookmarklet:
astrobites.org
http://www.bdnyc.org
http://hoggresearch.blogspot.com/
http://astrofrog.github.io/
https://astrocompute.wordpress.com/
http://www.astro.gla.ac.uk/~matthew/blog/
@regan008

**Comment by jccatalano** [comment]
These issues are resolved for the feeds with public RSS feeds. Of note, when you add a feed it will only retrieve posts dating back two months. Older posts will not be retrieved.
