### ISSUE TITLE
Transients for feeds should include the ID to avoid potential add/remove/re-add problems 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#644]

**Comment by AramZS** [comment]
Now resolved. Please test via full OPML interactivity, add OPML, assure it populates, remove OPML, re-add same OPML and assure it works properly.

This change touches the system's pull of the OPML file and processing of it.

**Comment by regan008** [comment]
@AramZS I'm seeing numerous issues when I try to add an opml but I'm not sure if they are related to this issue or to the progress on #335. 

I added an OPML but the counts appear to be off in the subscribed feeds panel. The active feeds label at the top shows 7 feeds but only 4 appear. One of the feeds that isn't appearing is AppleInsider, however those feed items **do** appear in All Content. 

Similarly, and this may or may not be related, the wired feed in this image is showing that there are 0 items associated with the feed but numerous items appear in All Content.  The folder associated with the feed also fails to filter the content and returns 0 items. 

The count in the progress bar message (see the last screenshot) is matching the count in subscribed feeds.  Over the last 20 minutes I've had 3 feeds disappear from Subscribed feeds even though it apparently did retrieve content from them and they did at one point show up in subscribed feeds. 

![screenshot 2015-10-19 12 12 18](https://cloud.githubusercontent.com/assets/4553057/10583446/051c350a-765b-11e5-8c9d-91863ddcce19.png)
![screenshot 2015-10-19 12 18 18](https://cloud.githubusercontent.com/assets/4553057/10583800/192f0a66-765d-11e5-8504-c423e4e3070b.png)

![screenshot 2015-10-19 12 20 47](https://cloud.githubusercontent.com/assets/4553057/10583853/54304300-765d-11e5-9a3e-a5ba1daec134.png)

**Comment by AramZS** [comment]
Seems to only happen on OPML subscribes

**Comment by AramZS** [comment]
Issue here should now be resolved.

**Comment by regan008** [comment]
This is resolved.
