### ISSUE TITLE
Reader View on DHNow including multiple posts and pf toolbar inside post

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#645]
I've never seen anything quite like this. It looks like when reader view is opened several of the most recent posts from this feed are being displayed (along with the pressforward toolbar) inside the body of the post. It might just be something odd in their html but I wanted to add it as an issue and document it. 

![screen shot 2015-08-18 at 9 27 21 am](https://cloud.githubusercontent.com/assets/4553057/9331127/9d94c906-458b-11e5-9de0-9b10ab6959f2.png)
![screen shot 2015-08-18 at 9 27 13 am](https://cloud.githubusercontent.com/assets/4553057/9331126/9d9280d8-458b-11e5-854f-9e8c7f51e940.png)

**Comment by AramZS** [comment]
Can you tell me what RSS feed @regan008 ?

**Comment by regan008** [comment]
@AramZS After some investigation I actually think this was caused because somebody nominated a post category rather than a single post using the bookmarklet. It looks like it was this url: http://fromstonetoscreen.com/category/digital-classics/

I don't actually think this is a bug so I'll go ahead and close it.
