### ISSUE TITLE
Site retaining all content items beyond 2 months? 

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#650]
@AramZS I noticed today that on DHNow when I used the search in All Content it was pulling up items from as far back as January. Is it possible that something is broken and it isn't deleting old feed items? Our site has been super slow lately. We have the "Months to retrieve and retain feed items" set to 2 and I tried to check out log but it appears to be broken. It just generates a blank screen.

**Comment by AramZS** [comment]
This should have been resolved for sure with the latest version. I will look into it.

**Comment by regan008** [comment]
From what I can tell this is resolved.
