### ISSUE TITLE
Manual clean up button

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#651]
Should trigger `disassemble_feed_items`

**Comment by regan008** [comment]
@AramZS Can you explain what this warning message means: "You can press this button to manually iniate the process of selecting feed items more than 2 months old. Be careful, there is a chance of iniating this process simultaniously with a process triggered automatically every 30 minutes."? We're a little confused about what exactly that means. 

Also, can clicking this button generate some form of feedback? Either a dialogue box or an alert window. Its hard to know if the clean up process has started

**Comment by AramZS** [comment]
Add HR tags between elements on this page.

**Comment by regan008** [comment]
@AramZS I'm still having problems getting a response when I click this button in my local install (which runs php 5.5). I can't get it to do anything and I've tried several different browsers. I don't know if this means anything but I do see an error in the network section of the console.  See the screenshot below. Any idea what might be going on?

![screenshot 2015-10-27 12 16 54](https://cloud.githubusercontent.com/assets/4553057/10764475/d4ba5b4e-7ca4-11e5-873c-c0a49dddde1a.png)

**Comment by AramZS** [comment]
@regan008 This appears to be the same issue as the comments issue, caused I think you said by another plugin?

**Comment by regan008** [comment]
yeah let me look into it a little bit this afternoon. I'm trying to figure
out what the difference between the 3 test sites is.  I might set up a
clean install and retest these issues from there. I'll get back to you

**Comment by regan008** [comment]
@AramZS Confirmed, this is working when the other plugin is deactivated.
