### ISSUE TITLE
Times Opinion Page grabs sidebar

### ISSUE THREAD

**Issue by mAAdhaTTah** [PressForward/pressforward#652]
I think it's the Opinion pages generally, but it at least failed here:

http://publiceditor.blogs.nytimes.com/2015/09/09/has-the-times-dismissed-bernie-sanders/?smid=tw-share&_r=0

**Comment by AramZS** [comment]
This should be resolved, can you confirm @mAAdhaTTah ?

**Comment by regan008** [comment]
Confirmed -- this appears to be resolved.
