### ISSUE TITLE
Feeds subscribed to through OPML subscriptions seem to be duplicating

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#654]

**Comment by AramZS** [comment]
Some posts have the post_status of `closed`, they are duplicated. This may be causing a problem here or with #655

**Comment by AramZS** [comment]
This is causing the All count to go up in Subscribed Feeds when it only shows less than that number.

**Comment by AramZS** [comment]
ooop. Never mind, read wrong thing

**Comment by AramZS** [comment]
now system is removing post parent

**Comment by AramZS** [comment]
Only when items have been retrieved on it though

**Comment by AramZS** [comment]
Nope, will happen even if no items collected.

**Comment by AramZS** [comment]
This should no longer occur

**Comment by regan008** [comment]
Haven't been able to replicate this so I'm going to close it. I think its fixed.
