### ISSUE TITLE
Feeds going draft for no apparent reason

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#655]

**Comment by AramZS** [comment]
The system should have resolved this now.

**Comment by regan008** [comment]
@AramZS Is this issue just referring to the duplication of feeds when an opml is added? Or is there another context in which feeds were added as drafts unexpectedly?

**Comment by AramZS** [comment]
@regan008 No, this is a different context. This was just Feed posts were going to Draft for no apparent reason.

**Comment by regan008** [comment]
@AramZS Ok, I haven't been able to replicate this so I'm going to close it.
