### ISSUE TITLE
If RSS-Quick update fails, the process freezes 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#656]

**Comment by AramZS** [comment]
Particularly when the feed retrieval attempt times out

**Comment by AramZS** [comment]
I believe this to be resolved. Please test by adding feeds into the system with OPML files and verifying that the process of adding titles to them no longer crashes the system.

**Comment by regan008** [comment]
This appears to be fixed.

**Comment by AramZS** [comment]
Had to revert this, should re-approach

**Comment by AramZS** [comment]
See: d873fe0b76d86bdad88c686c549296d5684c3ad3

**Comment by regan008** [comment]
@AramZS is this assigned to you so you can test it? If not could you elaborate on what exactly this means and what would be the best way for us to test it?

**Comment by AramZS** [comment]
@regan008 I had to revert the code that resolved this ticket. So I have to rebuild it now, so there's nothing to test yet.

**Comment by AramZS** [comment]
Passing this to the next milestone. It was a problem before, so it will continue being a problem for now.

**Comment by regan008** [comment]
@AramZS How should I test this? I think you said you have some rss feeds that you know it fails with right?

**Comment by AramZS** [comment]
@regan008 Oh yes, we should. Yes, one sec...

**Comment by AramZS** [comment]
@regan008 Test with these:
http://173.13.167.171/scobleizer/rss.xml
http://173.13.167.171/10000words/rsstop.xml
http://173.13.167.171/greglinch/rsstop.xml
http://173.13.167.171/joeybaker/rsstop.xml
http://173.13.167.171/samplereality/rsstop.xml
http://www.publish2.com/network/greg-linch/links.rss
http://www.publish2.com/newsgroups/copress-network.rss
http://www.jlittau.net/?feed=rss

**Comment by regan008** [comment]
@AramZS I should make an opml out of them right?

**Comment by AramZS** [comment]
Oh, yes, that's right, you should, so they get added as rss-quick.

**Comment by AramZS** [comment]
@regan008 But also include some valid RSS in the site, so we can make sure they know how to continue on to the valid RSS.

**Comment by regan008** [comment]
@AramZS Gotcha. Will test right now

**Comment by regan008** [comment]
@AramZS I think this is working now. The system added all the feeds and then moved on to retrieve content from the valid feeds.  Is there anything else I should be looking for?

**Comment by AramZS** [comment]
@regan008 Nope, that resolves it.
