### ISSUE TITLE
Success/failure message when nominating a feed with Nominate This

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#657]
@AramZS Related to #581 would it be possible to include a line in the success message in Nominate this that indicates whether or not the plugin was able to find a feed and submit a feed based on the nominated post? When testing I nominated about 5 different feeds associated with different items and only 1 got added to subscribed feeds. If I was a contributor I'd have no idea whether or not submission was successful. Would that be difficult to build in at some point? 

I think we may have discussed this before but I can't seem to find an issue on it.

**Comment by AramZS** [comment]
I've added the results to this process to the logging process but not in a response yet. It looks quite complicated to implement.

**Comment by regan008** [comment]
@AramZS  It seems that when the same feed is nominated multiple times through Nominate This that it is being duplicated inside of subscribed feeds.

Also, can we adjust the success and failure messages that appear when a feed is nominated.  We think there should probably be 3 different alerts: 
1. Red alert -- "PressForward was unable to identify a feed associated with this site. Please contact the site administrator or add the feed manually in the "Add Feeds" panel."
2. Red alert -- "There is a problem with the feed associated with this post. The feed could not be verified."
3. Green alert -- "The feed has been nominated successfully." 

Also, the alert box is appearing green even when there is an error message.

**Comment by AramZS** [comment]
@regan008 The new message has two modes that can now be active. If WP_DEBUG is set to false or if the user doesn't have permission to publish posts, they should see a simplified error message. Otherwise Editor level and higher users, or all users when WP_DEBUG is on, will see a more complex error message with details to aid in debugging. Give it a try and tell me if it works.

**Comment by regan008** [comment]
@AramZS This looks great!
