### ISSUE TITLE
Refresh Button Broken

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#660]
When clicked, the refresh button is generating a yellow bordered box with the word undefined. Possibly related to #391 and #651

![screenshot 2015-10-26 12 40 06](https://cloud.githubusercontent.com/assets/4553057/10735506/be95bc94-7bde-11e5-9894-c8e2b90aa15f.png)

**Comment by regan008** [comment]
@AramZS This is working now!  Would it be possible to get rid of the yellow border though?

**Comment by regan008** [comment]
@AramZS as of this morning with the newest branch I'm getting undefined again -- did the fix get lost somewhere along the way with the most recent edits?

**Comment by AramZS** [comment]
@regan008 I'll get rid of the yellow border. I can't duplicate the problem, last time it happened it was a plugin acting up, is it possible that is occurring again?
