### ISSUE TITLE
Saving a feed generates a success message and broken link

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#661]
In the edit feed page, when a feed is saves the success message that is generated references a post and creates an "edit post" link that is broken. 

The success message should say something along the lines of "The feed was saved successfully." and there probably shouldn't be an edit link.
![screenshot 2015-10-26 13 21 03](https://cloud.githubusercontent.com/assets/4553057/10736628/6db4fc1c-7be4-11e5-8a79-99e0ab19ff50.png)

**Comment by AramZS** [comment]
@regan008 Is this new?

**Comment by regan008** [comment]
@AramZS I'm not sure, I think so but it might be older. I just noticed it when testing things on the subscribed feeds page.

**Comment by regan008** [comment]
Looks good
