### ISSUE TITLE
In Quick Edit, the feed status options in the dropdown reflect post statuses not the feed statuses 

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#666]
In Quick Edit the feed status dropdown contains: Published, Draft, and Pending Review when they should be Active and Inactive. 

![screenshot 2015-10-26 13 30 14](https://cloud.githubusercontent.com/assets/4553057/10736894/b62b6854-7be5-11e5-8d9d-a603409c3355.png)

**Comment by AramZS** [comment]
👻

**Comment by regan008** [comment]
@AramZS For some reason the statuses are reflecting active in the quick edit dropdown even if the feed is alerted.  An alerted feed's status should be inactive right? That is how it appears inside of the edit feed screen. See below: 
![screenshot 2015-11-15 10 33 06](https://cloud.githubusercontent.com/assets/4553057/11169405/9efb415a-8b84-11e5-98da-f9ed87e863bc.png)
![screenshot 2015-11-15 10 32 57](https://cloud.githubusercontent.com/assets/4553057/11169404/9ef82844-8b84-11e5-9df3-72d531c8922a.png)

**Comment by AramZS** [comment]
@regan008 This reflects the future post status, when it removes the alert, altering this might take a while. Do we want to fix this in 3.7 or can it wait until 3.8?

**Comment by regan008** [comment]
@AramZS Oh I see, yeah lets move it to 3.8
