### ISSUE TITLE
OPML import doesn't get titles from feedly OPML

### ISSUE THREAD

**Issue by avishayil** [PressForward/pressforward#668]
Hi,
I'm trying to import the following OPML:
http://www.geektime.com/feedly.opml.xml

It subscribes, but displays the URL of the feeds in the Title column on PressForward, instead of the actual title from the OPML parameters.

Anyone knows how to solve this issue?

**Comment by eolson3** [comment]
Unfortunately, you'll have to change them manually.  PressForward is pulling the title from the feed itself, which hasn't been set to something elegant.  To change them, go to the "Subscribed Feeds" panel.  You'll be able to edit each feed title there.

Is that the barrier you're running into?

**Comment by AramZS** [comment]
If you wait, all functioning feeds will eventually be refreshed with their titles when the system retrieves content from them. Other than that, the OPML file would need to include titles. Yours seems too, I'm not sure why titles are not being added in that case. I'll take a look
