### ISSUE TITLE
Feeds are not being retrieved at all and almost all being marked as alerted

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#669]
@AramZS Last week we noticed that the newest version of 3.7 wasn't retrieving content at all.  I've verified today that this is still the case. pftesting hasn't pulled new content since Oct 28th and is marking almost everything as alerted.  Is it possible something broke in one of your commits around that time?

**Comment by AramZS** [comment]
This appears to be resolved with https://github.com/PressForward/pressforward/commit/d873fe0b76d86bdad88c686c549296d5684c3ad3 please test.

**Comment by regan008** [comment]
This appears to be fixed
