### ISSUE TITLE
Add option to place Source Title/Link at top of post instead of bottom

### ISSUE THREAD

**Issue by devinbalkind** [PressForward/pressforward#673]
This would give more attention to the creator of the content.

**Comment by AramZS** [comment]
Thanks for this suggestion, we'll add an option

**Comment by AramZS** [comment]
@devinbalkind Thank you again for this idea, the feature is now slated to come out in the next release.

**Comment by devinbalkind** [comment]
Awesome. When is that going to be available?

**Comment by regan008** [comment]
@AramZS I'm still having trouble getting this to work.  Will retest after you push the nomination-related issues tonight.

**Comment by regan008** [comment]
Confirmed this is now working -- This is a cool option!  @devinbalkind Should be available with the 3.8 release in the next few days.
