### ISSUE TITLE
API Endpoint to Trigger Readability on an item

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#693]

**Comment by AramZS** [comment]
Add permission check.

**Comment by boonebgorges** [comment]
The endpoint exists but was disabled in https://github.com/PressForward/pressforward/commit/20cb52979c1abf7d7bfe93459f6a0788da59a26d

As a rule, client software should use its own implementation of Readability. This is what Nominate This now does #1097. But if there comes a time when we have a native use case for a REST endpoint, we'll consider reopening this ticket.
