### ISSUE TITLE
RSS feed for the Verge and Polygon do not work

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#696]
They always appear as alerted

**Comment by AramZS** [comment]
Vox Media sites, oy.

**Comment by AramZS** [comment]
@regan008 I think this is resolved in the latest release. Can you check?

**Comment by regan008** [comment]
When I try to add the verge rss feed I get the following as an alert at the top of the add feeds screen: 
```
You have submitted a feed. Edit. The feed was not found.
```

Here is the rss feed I was using: https://www.theverge.com/rss/group/features/index.xml

**Comment by AramZS** [comment]
Ready to test.

**Comment by AramZS** [comment]
Fix is in, we can put it into the next release.

**Comment by regan008** [comment]
@AramZS I'm still getting the same error

**Comment by AramZS** [comment]
@regan008 what URL are you putting in?

**Comment by regan008** [comment]
The link listed above:  https://www.theverge.com/rss/group/features/index.xml

**Comment by jccatalano** [comment]
I am not having an issue with this. Might be a local install issue.
