### ISSUE TITLE
Subscribe to Twitter Users as Feed

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#698]

**Comment by AramZS** [comment]
Attach Tweet URL as Post Meta
Render Tweet through oEmbed in the Feed Item for people to see.

**Comment by AramZS** [comment]
Archive Tweet (possibly through Media Library)

**Comment by AramZS** [comment]
Only pull tweets with links, video, and audio attached.

**Comment by AramZS** [comment]
Have default folder for Twitter feeds

**Comment by AramZS** [comment]
Have a filter for Twitter feeds on/off (user option for default)

**Comment by AramZS** [comment]
Also lists!

**Comment by boonebgorges** [comment]
See https://github.com/PressForward/pressforward/issues/139#issuecomment-2303096191
