### ISSUE TITLE
Nominate This crashes on Gothamist 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#714]
Catchable fatal error: Object of class WP_Error could not be converted to string in /home/arazuc/chronoto.pe/wp-content/plugins/pressforward/includes/functions.php on line 775

**Comment by AramZS** [comment]
Test by attempting to use nominate this on a number of Gothamist articles

**Comment by regan008** [comment]
Assigning this to @bschnei6 since I'm out of the office this coming week.

**Comment by AramZS** [comment]
Confirmed URL to test on is http://gothamist.com/2015/11/20/l_o_hell.php

**Comment by bschnei6** [comment]
I've tested about a dozen articles in addition to the above URL. None have gone through to the nominated page.

**Comment by AramZS** [comment]
@bschnei6 on 3.8.x?

**Comment by bschnei6** [comment]
Mandy says she doesn't think the test site has been updated to 3.8 yet. We'll update it and I'll run the test again.

**Comment by AramZS** [comment]
@bschnei6 thanks!

**Comment by bschnei6** [comment]
Gothamist sites are nominating, but are giving errors in the plugin and in the nominated page. Error text is:

Notice: Undefined index: simple in /websites/pftesting/www/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php on line 816 

This error doesn't seem to have any effect on the text of the Gothamist page displaying correctly in Nominated, nor does it prevent the "Read Original" from linking back to the correct source.

**Comment by regan008** [comment]
@AramZS Is this Notice something that is appearing because we have debug on or will it not appear for users with debug off?

**Comment by AramZS** [comment]
The notice only shows because debug is on, but it should still be resolved.
