### ISSUE TITLE
Youtube RSS should pull in URL for oEmbed

### ISSUE THREAD

**Issue by wykydtronik** [PressForward/pressforward#716]
Hello,

Testing PressForward with Youtube RSS feeds.

Example,
https://www.youtube.com/feeds/videos.xml?user=noriyaro

More feeds like this can be generated according to Youtube documentation
https://www.youtube.com/feeds/videos.xml?channel_id=CHANNELID
https://www.youtube.com/feeds/videos.xml?user=USERNAME
https://www.youtube.com/feeds/videos.xml?playlist_id=YOUR_YOUTUBE_PLAYLIST_NUMBER

Goal is to make Youtube and Vimeo videos easier to digest as a blogger. Be able to have multiple RSS feeds from Youtube and Vimeo pulled into PressForwards dashboard. When new content is posted, have PressForward place the URL at the top of the content Draft for oEmbed.

**Comment by AramZS** [comment]
Oh, I didn't even know that YouTube generated RSS feeds. We will definitely put this in the workflow.

**Comment by slwestcott** [comment]
One of the partners is interested in this, as well - PressForward will pull in the title, etc of the youtube video but not the embed code. Would be great if we could eventually (not immediately, but soonish) make this possible.

**Comment by AramZS** [comment]
Should be done with a79f70de687a569c532aa8f692756fb8d049d80a

**Comment by regan008** [comment]
This is working (very cool!)
