### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by nicheprof** [PressForward/pressforward#718]
I have the Nominate This PressForward Bookmarklet installed on the Bookmarks bar, however, when I attempt to push the button to add an article or site with this method I get a 404 Page Not Found Error in the pop-up window.

I have no issues with adding RSS Feeds through the WP Admin Area and completing the aggregating, nominating and posting through that process.

What am I missing?

Thanks in advance, Rpn

**Comment by AramZS** [comment]
@nicheprof Do you have a standard folder structure for your site? Sometimes our bookmarklet has trouble finding the URL if there is a non-standard WordPress file structure.

**Comment by AramZS** [comment]
Hi @nicheprof I wanted to check in on this again. Are you still having this issue consistently? Can you try our latest release and see if it fixes your problem?

**Comment by devinbalkind** [comment]
I have this issue as well. My site is at a "blog." subdomain. Any advice for how to make this work?

**Comment by AramZS** [comment]
@devinbalkind Can you try deleting the bookmarklet and re-adding it from the PressForward Tools page to your bookmark bar?

**Comment by devinbalkind** [comment]
Ya - same error.

**Comment by TimRohr22** [comment]
I am having the same issue... I have removed and re-added the bookmarklet, and I have added the bookmarklet both by dragging it from the Tools page and by manually copying the code and creating a bookmark. I have Wordpress 4.4.2 installed, and it tells me PF hasn't been tested with my version of Wordpress. Using the bookmarklet in Chrome (up to date) on a Windows Vista machine.

**Comment by devinbalkind** [comment]
I've gone through the same steps as Tim. My computer is running Ubuntu and
chrome.

As a work around I'm using getpocket.com as a bookmark tool, exposing it's
RSS feed and syndicating that into press forward.
