### ISSUE TITLE
When Feeder Menu Privileges  set to "Author" the user can view add and subscribed feeds pages but can't add feed

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#722]
One of our partners reported that they are having an issue with setting the Feeder privileges option to Author. Doing so grants permission to view the subscribed and add feeds pages but users with the role "Author" can't add a feed and get a Wordpress error that reads "Cheatin' huh?"

**Comment by dianemercier** [comment]
Can't go to "Subscribed feed" sub-menu. 
~/wp-admin/edit.php?post_type=pf_feed
Received error message : 
"You are not allowed to edit posts in this post type"

I resetted user control to default. My username account is setted to "administrator"
... both in my localhost and my website

I can go to sub-menus : Nominated; All content; Add Feeds; Tools; and View Log

**Comment by regan008** [comment]
@AramZS in 3.8.x-post-meta-fixes this appears to be resolved

**Comment by dianemercier** [comment]
The solution to the problem above has been given by @Niackery at
https://wordpress.org/support/topic/permissions-error-16
To fix the problem, add the following to the register_post_type function in pressforward/includes/feeds.php:
'show_ui' => true,

I removed the comment (#). In addition, it was necessary to add a comma at the end of the line before : 'show_in_menu' => PF_MENU_SLUG,

+1

**Comment by regan008** [comment]
Confirmed -- this has been resolved.
