### ISSUE TITLE
You are not allowed to edit posts in this post type; pf_feed

### ISSUE THREAD

**Issue by peter-nl** [PressForward/pressforward#724]
Hi PressForward,

Love the plugin and thank you for that!

When trying to access the "Subscribed feeds" submenu (edit.php?post_type=pf_feed) I run into an error, "You are not allowed to edit posts in this post type".
This error occurs in WP4.4, no other plugins active but PressForward, twenty sixteen theme, logged in as Administrator. 

Looking at the registration of the custom posttype 'pf_feed' in includes/feeds.php, I notice 'public' being set to false and 'show_ui' is commented out. 
As soon as I set 'show_ui' to true, I can access the Subscribed feeds menu again. 

I'm not entirely sure but I believe this behavior was introduced with WP4.4 and the Trac ticket [Post types with show_ui set to false should not be accessible via the admin area](https://core.trac.wordpress.org/ticket/33763) could well be involved.

Hope this helps.

**Comment by AramZS** [comment]
Yes, this change in 4.4 has altered the expected behavior of PressForward unexpectedly. We will be patching very soon.

**Comment by peter-nl** [comment]
Thanks for getting back this quick! We look forward to the patch.
I'll close the issue.
Again, thanks!
