### ISSUE TITLE
Date/Time Metadata wrong

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#725]
The date and time of each nomination is displaying wrong. (These items aren't from 1970!)  See screenshots below:
![screenshot 2015-12-22 18 58 17](https://cloud.githubusercontent.com/assets/4553057/11968818/3d1c6154-a8de-11e5-9323-8e8e62e2ba96.png)

**Comment by regan008** [comment]
Oh and this is on the 3.8-pf-meta-fixes branch

**Comment by AramZS** [comment]
Confirmed.

**Comment by regan008** [comment]
Fixed
