### ISSUE TITLE
Updating feed url doesn't update feed url display in Subscribed Feeds

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#727]
When I update the feed url in subscribed feeds either through quick edit or through the edit feed page, the url that is displayed below the feed title in the list view on Subscribed Feeds never changes.  

Probably not a big deal immediately if you need to push it out of this milestone.

**Comment by AramZS** [comment]
I will push this to 3.9

**Comment by regan008** [comment]
@AramZS This can be pushed to 4.1 if you'd like.

**Comment by AramZS** [comment]
Resolves with above.

**Comment by regan008** [comment]
Looks good!
