### ISSUE TITLE
Better failure methods for when OG image is not provided to the bookmarklet

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#731]
It should look for the first image in the content and use that as a featured image instead.

**Comment by AramZS** [comment]
For an image to be valid in the body of the content, it must exist, have width set, and have a width of greater than 300. Test with a page with no og:data but an image that satisfies those conditions.

**Comment by regan008** [comment]
@AramZS I'm trying to test this but am having issues getting the bookmarklet to work. Nothing I nominate is being sent to under review. Not sure if it is related but I do get this message at the top of the bookmarklet: 
```Deprecated: Non-static method PressForward\Controllers\PF_Readability::process_in_oembeds() should not be called statically in /srv/www/wordpress-default/wp-content/plugins/pressforward/Controllers/PF_Readability.php on line 316```

**Comment by AramZS** [comment]
Good to know and not good that nominations are not processing through the bookmarklet I'll check on this ASAP.

**Comment by regan008** [comment]
@AramZS So [here is a site ](http://www.boltsfromtheblue.com/2016/7/17/12207720/san-diego-chargers-daily-links-bosa-watch-2016-continues) where the image is def above 300px and it appears to have a twitter card preview yet the bookmarklet is not brining the image in as a featured image.  It should be catching this image, correct?

**Comment by AramZS** [comment]
The page was blocking us, figured it out a better way to access it. Give it another try.

**Comment by regan008** [comment]
Confirmed -- working now.
