### ISSUE TITLE
PressForward conflict with wp101

### ISSUE THREAD

**Issue by zlove** [PressForward/pressforward#739]
When PressForward is installed, I cannot perform admin actions with the wp101 plugin (https://wp101plugin.com/), including adding a custom video, updating settings, etc. When trying to take an action in wp101, I would receive a 403 response with the Wordpress message "Are you sure you want to do this?".

Here is a quick screen capture demonstrating the issue:

https://youtu.be/ZzQybWIO1p8

PressForward version: 3.8.0
wp101 version: 3.2.3

I did not experience this (or similar) issues with other plugins on this WP install, but did not test extensively.

**Comment by AramZS** [comment]
@zlove Do you have the latest version of PressForward?

**Comment by zlove** [comment]
I've got version 3.8.0 - the latest available at
https://wordpress.org/plugins/pressforward/

**Comment by AramZS** [comment]
@zlove Hi, this should be resolved with the latest release.

**Comment by zlove** [comment]
Thanks for the update Aram! I will check it out.

**Comment by regan008** [comment]
This appears to be a closed issue.
