### ISSUE TITLE
Control over how content is processed and the post type it is saved under

### ISSUE THREAD

**Issue by plexus77** [PressForward/pressforward#740]
Hi guys,

Great plugin, it nearly has everything I need for a project I am currently involved in.

Not sure this is the right place to be talking about this but here I go...

When an article is published what is the best way to hook into the post creation process so that I can further process the content (main body of article) into an alternative form.  I am using custom fields within the wordpress admin that seperate blocks of content into various types ie images, plain text, video etc.  
 
I have looked through the code base and can't see anywhere where I might hook into you code so I will use the 'wp_insert_post' action to do this.

Also I need to be able to select the post type for the content when it is imported as there are several post types I will be using to store the processed feed content.  It would be great to be able to handle this all on import rather than to have the need for some double handling.

Any help or suggestions would be greatly appreciated.

Regards,
Morgan

**Comment by AramZS** [comment]
Hi @plexus77 We have to reserve a particular post type for the initial ingestion of feeds so the system can understand what is going on, however, in PressForward's Preferences -> Site Options you can select from any registered Post Type as the post type you would like PressForward to send items to as its last publish/draft step. 

After that, you can do any processing of saved content the way you would with any other post, the `wp_insert_post` is definitely an option, along with other standard locations to hook into. We don't find people need a special PressForward hook for this, as WordPress hooks should do fine. 

Does that answer your questions?

**Comment by plexus77** [comment]
Yes it certainly does, thanks for getting back to me :)
