### ISSUE TITLE
Assure readability is catching references block

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#741]
See block at end of http://astro.ifweassume.com//2016/01/07/fluxcal-in-tess/

See report at https://github.com/PressForward/PF_Zenodo/issues/5

**Comment by regan008** [comment]
@AramZS Using the example URL you provided above, I am able to pull in some of the references but not the bulleted list below "Some Relevant Literature". Here is what I see: 
![screen shot 2016-08-29 at 12 32 16 pm](https://cloud.githubusercontent.com/assets/4553057/18058959/bbcda8fc-6de4-11e6-96d5-441b05e0889e.png)
![screen shot 2016-08-29 at 12 32 11 pm](https://cloud.githubusercontent.com/assets/4553057/18058958/bbcb90bc-6de4-11e6-967c-63ffc227a46c.png)

**Comment by regan008** [comment]
@AramZS Disregard the previous comment. It would help if I updated the plugin before beginning to test things! This works now
