### ISSUE TITLE
Uninstall press forward

### ISSUE THREAD

**Issue by jiunchin** [PressForward/pressforward#742]
The system generates too many pf_feed_item on my instance. What's the proper procedure for uninstalling this plugin and removing the pf_feed_item post type?

**Comment by AramZS** [comment]
@jiunchin Hey Jiun! If you are up to date with the latest version of PressForward you should be able to drastically decrease the number of pf_feed_item post_types in your database by modifying the Preferences -> Site Options setting: Months to retrieve and retain feed items. Decreasing that should decrease the number of pf_feed_item post types significantly. 

If that's not enough, the latest version of PressForward will clean up pf_feed_item posts in the database when you delete the Feeds that brought them in. Leaving the plugin installed, but removing all the Subscribed Feeds will queue deletion tasks to execute over however long it will take to execute usable queries in WP_Cron to delete the pf_feed_items.

If you're absolutely determined to remove everything Right Now, you can delete the plugin and run a MySQL statement to remove all post table rows with post_type = `pf_feed_item`, but don't forget to join on the post meta table and remove those too, as that is where some of the heaviest number of PressForward rows are.

**Comment by jiunchin** [comment]
I'll update the plugin but will probably manually remove the post and post
meta. I just wanted to confirm it's not going to impact the site.

Thanks

On Tue, Apr 5, 2016 at 1:56 PM, Aram Zucker-Scharff <
notifications@github.com> wrote:

> @jiunchin <https://github.com/jiunchin> Hey Jiun! If you are up to date
> with the latest version of PressForward you should be able to drastically
> decrease the number of pf_feed_item post_types in your database by
> modifying the Preferences -> Site Options setting: Months to retrieve and
> retain feed items. Decreasing that should decrease the number of
> pf_feed_item post types significantly.
>
> If that's not enough, the latest version of PressForward will clean up
> pf_feed_item posts in the database when you delete the Feeds that brought
> them in. Leaving the plugin installed, but removing all the Subscribed
> Feeds will queue deletion tasks to execute over however long it will take
> to execute usable queries in WP_Cron to delete the pf_feed_items.
>
> If you're absolutely determined to remove everything Right Now, you can
> delete the plugin and run a MySQL statement to remove all post table rows
> with post_type = pf_feed_item, but don't forget to join on the post meta
> table and remove those too, as that is where some of the heaviest number of
> PressForward rows are.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/PressForward/pressforward/issues/742#issuecomment-205919853>
>



-- 
Jiun Chin

CFO Publishing
45 West 45 St
12 th floor
New York, NY 10036
ph: (212) 488-4704
fax:  (212) 459-3007
