### ISSUE TITLE
Codes replacing punctuation in the reader

### ISSUE THREAD

**Issue by eolson3** [PressForward/pressforward#745]
Sharing an issue from email:

"You will see in the attached image, articles that I have nominated are appearing with codes in place of apostrophes, brackets, hyphens and more - but worse still - it is only happening some of the time, so I have not been able to get to the root of it.

Please see the attached and let me know your thoughts?"

Updated WP and php, all arriving via rss feeds.

Thanks, Aram,

![nominated_ _fixmyinfo_ _wordpress](https://cloud.githubusercontent.com/assets/11685672/14924181/2c8a4874-0e0f-11e6-8088-c152bd0dbc3e.png)

**Comment by regan008** [comment]
@AramZS We saw this on DHNow last week. Any chance you can take a look when you fix readability? We'll get you the urls it occurred on.

**Comment by asmorton** [comment]
examples of nominated posts on digitalhumanitiesnow.org that have this issue:

http://dmlcentral.net/artificial-intelligence-cognitive-systems-learning-brain/

http://digitalhumanitiesnow.org/wp-admin/admin.php?page=pf-review#modal-cbb07daa5be97d22242e31aa326604fa

**Comment by regan008** [comment]
@eolson3  @asmorton Can either of you confirm whether this is still happening?

**Comment by asmorton** [comment]
I haven't noticed it in the last few weeks.

**Comment by regan008** [comment]
Ok so lets close this until we see it again
