### ISSUE TITLE
Add ability to tag items/feeds in bookmarklet

### ISSUE THREAD

**Issue by slwestcott** [PressForward/pressforward#746]
Partners would like to be able to add tags to items nominated in order to send them directly to draft without having to add the tags in nominated panel.

**Comment by AramZS** [comment]
Tags now active on the Bookmarklet for the items. Also will seek OG tags to auto-fill

**Comment by regan008** [comment]
This is working, however I am noticing that the feeds are being duplicated in the info box in Nominated. The appear correctly when they are sent to draft from the bookmarklet and they are also correct once sent to draft from Nominated.  
![screen shot 2016-07-18 at 10 38 15 am](https://cloud.githubusercontent.com/assets/4553057/16918603/2251923c-4cd4-11e6-857c-bfc30107b976.png)

**Comment by AramZS** [comment]
Should be resolved now.

**Comment by regan008** [comment]
All fixed.
