### ISSUE TITLE
Edits to bookmarklet submitted content automatically reset

### ISSUE THREAD

**Issue by eolson3** [PressForward/pressforward#749]
A question by way of the OSI site:

When using the bookmarklet to nominate content, a text editor is included.  If the content is sent strait to draft, any changes are present in the post.  If the content is nominated the changes are acknowledged in the reader, but the readability is automatically reset when the content is sent to draft, thus erasing the previous changes.  Is there a way to prevent this?

**Comment by AramZS** [comment]
@jccatalano @slwestcott Do we prefer to have the bookmarklet override the nominations or not?

**Comment by AramZS** [comment]
Bookmarklet content should be preferred: Lets change this in practice and also get the unit test working accordingly.

**Comment by AramZS** [comment]
Note: we will have to revert this commit - https://github.com/PressForward/pressforward/commit/050ea5c2850b52ba0a7adae208952a2bf4f43541

**Comment by boonebgorges** [comment]
This no longer takes place after cd9a939.
