### ISSUE TITLE
Error upon activation 

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#751]
The message appears at the top of the plugin page after opting to activate the plugin. However, the plugin appears to activate regardless of the message. 

The message reads: 

> The plugin generated 186 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

![screenshot 2016-05-31 13 08 37](https://cloud.githubusercontent.com/assets/4553057/15683553/02511c32-2731-11e6-9915-31b1b1a7c518.png)

**Comment by AramZS** [comment]
Interesting, well, glad it activates. I'll have to look into that process.

**Comment by AramZS** [comment]
This should be resolved now, try it out.

**Comment by regan008** [comment]
confirmed, this is now working.

**Comment by asmorton** [comment]
Installed on pftesting.chnm.org via WP upload plugin interface. Got this error when I tried to activate:

Warning: require(/websites/pftesting/www/wp-content/plugins/pressforward-3.9.x-recore/Interfaces/Templates.php): failed to open stream: No such file or directory in /websites/pftesting/www/wp-content/plugins/pressforward-3.9.x-recore/class-SplClassLoader.php on line 164 Fatal error: require(): Failed opening required '/websites/pftesting/www/wp-content/plugins/pressforward-3.9.x-recore/Interfaces/Templates.php' (include_path='.:/opt/php-5.5/lib/php') in /websites/pftesting/www/wp-content/plugins/pressforward-3.9.x-recore/class-SplClassLoader.php on line 164

**Comment by regan008** [comment]
Oddly though I cannot replicate the issue on my local install. I'm running php 5.5.9-1ubuntu4.11. PFtesting is running php 5.5.26

**Comment by AramZS** [comment]
Resolved now
