### ISSUE TITLE
 Notice: get_currentuserinfo is deprecated since version 4.5! Use wp_get_current_user() instead. in /srv/www/wordpress-default/wp-includes/functions.php on line 3658

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#752]
I assume this is plugin related. 

@AramZS If replacing this function is something you'd like me to tackle let me know. I'm not sure if its more complex than just replacing the function used.

**Comment by AramZS** [comment]
You want to make a branch and try to patch it? It is a little bit more complex then just switching out the function, but the way to change it should be discoverable.

**Comment by regan008** [comment]
Sure, let me finish some testing and I'll give it a shot either today or tomorrow morning. I'll ping you if I have trouble

**Comment by regan008** [comment]
I think I've fixed this with ed6f199b363386fba020483144b7ed35c3e8f4f0. 

@AramZS Do you want me to submit a pull request or wait until you are done with the recore? I think I've fixed it -- it hasn't broken anything as far as I can tell.

**Comment by AramZS** [comment]
@regan008 Issue the pull request right now, we're more at the cleanup stage for the recore and this is part of that.

**Comment by regan008** [comment]
@AramZS Sounds good -- all merged. Let me know if theres anything else I should do to it.

**Comment by AramZS** [comment]
@regan008 I need you to do one change on the branch though, everywhere the function is called, use it to set `$current_user = wp_get_current_user();` The old way populated a global, I don't think the new way does it quite the same, better to be purposeful then trust in the global anyway.

**Comment by regan008** [comment]
@AramZS ah gotcha -- I'll work on that this afternoon and then resubmit the pull request.

**Comment by AramZS** [comment]
Pull request merged in.
