### ISSUE TITLE
Send to Draft process not working 

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#753]
The send to draft button isn't working. When I click it I get the loading bar but it just hangs. Here is the info from the log, the console, as well as details about my wp, browser, and pf versions. 

Browser: Chrome 
Wp Version: 4.5.2
PF: 3.9.x-recore (pulled 5/31 around 1pm)

This appears in the console when the "Send to Draft" button is clicked: 
```
load-scripts.php:4 POST http://local.wordpress.dev/wp-admin/admin-ajax.php 500 (Internal Server Error)send @ load-scripts.php:4ajax @ load-scripts.php:4n.(anonymous function) @ load-scripts.php:4(anonymous function) @ nomination-imp.js:73dispatch @ load-scripts.php:3r.handle @ load-scripts.php:3
load-scripts.php:4 POST http://local.wordpress.dev/wp-admin/admin-ajax.php 500 (Internal Server Error)
```

Here is what is shown in the log: 
```
load-scripts.php:4 POST http://local.wordpress.dev/wp-admin/admin-ajax.php 500 (Internal Server Error)send @ load-scripts.php:4ajax @ load-scripts.php:4n.(anonymous function) @ load-scripts.php:4(anonymous function) @ nomination-imp.js:73dispatch @ load-scripts.php:3r.handle @ load-scripts.php:3
load-scripts.php:4 POST http://local.wordpress.dev/wp-admin/admin-ajax.php 500 (Internal Server Error)
```

**Comment by regan008** [comment]
Also, even though the item isn't being sent to drafts when the page is refreshed the "nominate" icon has turned green. I can't tell yet if it actually is being nominated but that aspect of the button appears to be working.

**Comment by regan008** [comment]
Just realized I never assigned this to the milestone.

With the newest batch of commits it seems that Send to Draft has been fixed in most instances. The problem I'm having now is that the send to draft button (in all content) only works if the post _has not_ already been nominated. If the post is already nominated and you try to send it to draft not only does it not get sent but it also disappears from nominated. Seems like maybe a relationship issue?

When I log in as a contributor and nominate the same item it then shows up in nominated but with only 1 nomination rather than two. 

Does that make sense @AramZS ?

**Comment by AramZS** [comment]
Yup. This should be resolved with the latest update.

**Comment by regan008** [comment]
Confirmed, this is working now.
