### ISSUE TITLE
Nominate This Button Missing in All Content

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#756]
The nominate this button in the first box in All Content seems to have disappeared. I believe this happened in the last milestone when we moved the date/time. It looks like the button is actually there but just being covered up.

**Comment by AramZS** [comment]
Should now be resolved, could not duplicate error, so you'll have to double check.

**Comment by regan008** [comment]
Ok so upon further investigation there are two interrelated issues here. (1) The button is not visible when the screen is small enough. (On my desktop it didn't show up unless I made the screen full width. Below is a screenshot. (2) We've lost the styling from the button -- it just appears as a link now. It used to have an icon and looked like a button rather than a link. 

![screen shot 2016-06-07 at 10 09 33 am](https://cloud.githubusercontent.com/assets/4553057/15860719/342acde0-2c98-11e6-83c8-9665dec4e611.png)
![screen shot 2016-06-07 at 10 09 22 am](https://cloud.githubusercontent.com/assets/4553057/15860718/342845d4-2c98-11e6-9b98-4419be013348.png)

**Comment by regan008** [comment]
However, I should note that the styling does appear in list view 
![screen shot 2016-06-07 at 10 11 58 am](https://cloud.githubusercontent.com/assets/4553057/15860756/56a5f87c-2c98-11e6-9e4e-71b816919b66.png)

**Comment by regan008** [comment]
Confirmed!

**Comment by asmorton** [comment]
![screen shot 2016-06-14 at 4 00 36 pm](https://cloud.githubusercontent.com/assets/3477432/16057667/20c701e0-3249-11e6-8dce-10678a1acad5.png)

button is there when browser window is full screen, but hidden as soon as window width narrows.

**Comment by regan008** [comment]
@AramZS So this is working on my default screen now. But once the screen gets smaller on my tiny macbook air, the button is lost again. It begins to move for me at 1244px wide. 

Lets call this resolved for 3.9.x but is there anything we can do to make this work on a smaller screen? I could imagine a scenario where someone might want to work in a sort of split screen mode and encounter this problem. 

Alternatively, and maybe this would be just easier in the long run, could we have this box only show when the screen size is above a certain point? (If you are using foundation media queries, maybe medium or above?)

**Comment by regan008** [comment]
@AramZS Am I understanding this commit right? The nom this "item" should be hidden completely for smaller screens? I still see it

**Comment by regan008** [comment]
But the button isn't hidden so I'd say this is good to go for 3.9

**Comment by AramZS** [comment]
Nah, just the first paragraph should be. It sounds like that's what is happening?
