### ISSUE TITLE
If item_author is empty, WordPress is defaulting to the first user (alphabetically)  not the current user

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#764]
We're noticing this on DHNow and also on test sites. The issue is that if item_author is empty WordPress is pulling the first alphabetical user not the current user.  It doesn't seem to matter if the post was drafted from the bookmarklet or through the regular workflow. Does that make sense? We're not sure when this started but its been an annoying issue on DHNow and it took us a while to figure out what was going on. Any idea if this is a quick fix we could include in 3.9.x @AramZS?

**Comment by AramZS** [comment]
Huh, yeah, should be easy enough. Can you give me an exact chain of actions that leads to the occurrence.

**Comment by AramZS** [comment]
This is either resolved or should be moved to 4.x

**Comment by regan008** [comment]
Yeah lets move this to 4.x -- @asmorton and I will work on documenting when it happens so that I can give you an exact chain of events.

**Comment by AramZS** [comment]
Author when unidentified should be the name of the site.

**Comment by regan008** [comment]
The item_author isn't appearing blank anymore, but now item_author is showing "bookmarklet" as the source rather than the name of the site.

**Comment by AramZS** [comment]
@regan008 That's the intent. If there's no author and the Bookmarklet can't find the title of the site, it'll note the Bookmarklet as the author. Is that ok or would you prefer a different option?

**Comment by regan008** [comment]
@AramZS Oh, I misunderstood then. I thought we had discussed having the name of the site be the item author? Is it different for the bookmarklet?

**Comment by AramZS** [comment]
@regan008 That is what is occurring, but you're witnessing a cascaded failure here so what the system is currently doing is:
Can't Find Item Author to use as author
Can't Find Site Title to use as author
Use "Bookmarklet" as author

Does that work?

**Comment by regan008** [comment]
Yes that is perfect, lets close this then!
