### ISSUE TITLE
User nom_count is not increasing beyond 2

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#769]
I’m working on some user management stuff and I exported a csv of all our users on dhnow and the info included about them in the meta table. The nom_count field is one of the fields that was exported but looking through the data, its odd but there aren’t any users who have more than 2 nominations. I know my count should be much higher. Here is a snipped of the csv so you can see what was pulled out: 
```
Role	Login	Data de Registro	nom_count
administrator	joan	                2011-09-08 19:03:33	   2
administrator	jeri	                2011-09-08 19:03:59	   2
administrator	sashab	        2011-09-26 16:16:50	   2
administrator	bens	                2013-08-27 15:10:11	   2
administrator	amandam	2013-08-27 15:11:02	   2
administrator	lindseyb	        2013-08-27 15:12:09	   2
administrator	westcott	        2013-09-19 18:21:52	   2
administrator	Amanda      	2014-02-24 17:03:49	   2
administrator	pfadmin	        2014-08-05 21:11:55	
contributor	xxxx	                2013-08-09 1:37:44	           2, 2, 2002																										
```

**Comment by regan008** [comment]
@AramZS I'm still not able to get the numbers to increase beyond 2. Here is a snapshot of the my user_meta table: 
![screen shot 2016-07-18 at 11 12 09 am](https://cloud.githubusercontent.com/assets/4553057/16920028/fee2b032-4cd9-11e6-8401-9bb106efd78a.png)
Users 27 and 28 should both have way more than 2 nominations.

**Comment by regan008** [comment]
@AramZS  So this does appear to be fixed. But when I am exporting the csv I see "5</br>".  I'm not sure if the tag is being added during the export or if its added in the plugin but I'm not sure it should be there? Will that cause issues down the road?

**Comment by AramZS** [comment]
@regan008 I have to assume it is the export process. There should only be a number in there. What are you using to export?
