### ISSUE TITLE
Items nominated with bookmarklet display error in Nominated

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#773]
Underneath the title in Nominated the following notice appears: 
```
Notice: Undefined index: host in /srv/www/wordpress-default/wp-content/plugins/pressforward/Core/Admin/PFTemplater.php on line 475
```

**Comment by regan008** [comment]
Oddly, though -- this error seems to go away after a few minutes. Is it possible that it just appears while the post is being processed?

**Comment by AramZS** [comment]
Could be, looking into it.

**Comment by AramZS** [comment]
Can you see what happens with this with the latest update?

**Comment by regan008** [comment]
Still displaying a notice but a slightly different one now: 
```
Notice: Undefined index: host in /srv/www/wordpress-default/wp-content/plugins/pressforward/Core/Admin/PFTemplater.php on line 478
```

**Comment by regan008** [comment]
Seems to be fixed
