### ISSUE TITLE
If nothing is hidden in All Content the filter displays everything but the breadcrumbs indicate that a filter has been applied.

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#774]
When I'm in All Content and I filter to show hidden even though I have not hidden anything all the content is displayed. However the bread crumbs still say "Showing Hidden" even though its displaying all the normal content.

**Comment by AramZS** [comment]
Screen-Shot please?

**Comment by regan008** [comment]
![screenshot 2016-06-13 11 03 10](https://cloud.githubusercontent.com/assets/4553057/16012260/adb45c9a-3156-11e6-9c64-2098a9168464.png)

**Comment by AramZS** [comment]
This will only occur if nothing in the system is hidden as far as I can tell. Can you confirm?

**Comment by regan008** [comment]
Yes, that was the only place I could make it occur. If you want to push to 4.0 since we've added so many new issues this morning that should be fine.

**Comment by AramZS** [comment]
Going to note this as a candidate to drop to next milestone, if we clear everything else on the board but not this, I'll drop it, but I may end up finding the problem as part of fixing something else so I don't want to entirely drop it out of the milestone right now.

**Comment by regan008** [comment]
Sounds good

**Comment by AramZS** [comment]
Should now be resolved.

**Comment by regan008** [comment]
@AramZS -- the url now reflects that there is nothing hidden (#no-hidden) but the breadcrumbs still indicate that it is shown hidden items. We can push that small detail off till 4.0.x though if you want

**Comment by AramZS** [comment]
"no-hidden" means nothing is hidden - > hidden content should be shown. This is the expected breadcrumb. Is it showing expected items?

**Comment by regan008** [comment]
So when I filter by hidden, and nothing is hidden, all content shows everything but the breadcrumb indicates that I am viewing hidden items. But when something is hidden its showing the correct items. I would expect that if nothing is hidden, I would see no items when filtering by hidden. Does that make sense or am I misunderstanding how this should work? Here is a screenshot: 
![screen shot 2016-06-20 at 10 45 04 am](https://cloud.githubusercontent.com/assets/4553057/16198505/31d9d824-36d4-11e6-9203-1953273b5e25.png)

**Comment by AramZS** [comment]
I believe the spec for that feature is to include hidden alongside not hidden, not to show only hidden content.

**Comment by regan008** [comment]
Ah ok that makes sense. Lets close this then
