### ISSUE TITLE
Filtering by "my drafted" in All content (as a contributor) displays content drafted by another user

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#775]

**Comment by AramZS** [comment]
Ready to test.

**Comment by regan008** [comment]
@AramZS it is still showing items that were nominated by another user.  I'm also noticing that it never populates with more than 5 items regardless of the user or user's privileges. In my admin account I've drafted at least 15 items but only 5 show up in "Show all Drafted." See screen shots.

![screenshot 2016-06-14 10 23 38](https://cloud.githubusercontent.com/assets/4553057/16046416/6a9e49f6-321a-11e6-99ae-48934ddb08ad.png)
![screenshot 2016-06-14 10 26 50](https://cloud.githubusercontent.com/assets/4553057/16046460/8aefc914-321a-11e6-9c06-b9d7d48bd079.png)

**Comment by AramZS** [comment]
Drafted is not currently user specific, though Nominated should be.

**Comment by AramZS** [comment]
Limited number of posts problem now resolved.

**Comment by regan008** [comment]
Hmm, so the issue of limited number of posts is still occurring for me. I only see 3 now regardless of how many I draft.

**Comment by asmorton** [comment]
I'm only seeing 5 on pftesting.
