### ISSUE TITLE
Nominating a feed from Nominate This triggers notice 

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#777]
After nominating a feed associated with a post using Nominate This the following notice appears at the top of the success page in the bookmarklet:
```
Notice: Undefined index: extension in /srv/www/wordpress-default/wp-content/plugins/pressforward/Core/Schema/Feed_Items.php on line 940
```

**Comment by AramZS** [comment]
@regan008 Can you check this again and see what occurs?

**Comment by AramZS** [comment]
With the latest update I mean.

**Comment by regan008** [comment]
This appears to be working now!

**Comment by AramZS** [comment]
It is just handling the problem in a user friendly way, but not sure what is causing the problem. I would like to look more deeply into this later. Re-opening and moving to 4.x

**Comment by AramZS** [comment]
This should now be fully resolved.
