### ISSUE TITLE
Preferences will not save changes to options

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#780]
I'm having trouble getting user control options to save. I tried to change the Nominated menu access from contributor to administrator and after I click save changes it reverts right back to contributor. It is reverting any change to these options back to the previous value.

**Comment by regan008** [comment]
In fact its doing this for any option within the Preferences page.

**Comment by AramZS** [comment]
I think the latest update has fixed this. Please try again.

**Comment by regan008** [comment]
Yup, all fixed.
