### ISSUE TITLE
Nominating a feed pulls in the site url not the feed url

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#783]
From what I can tell, when a feed is nominated with the bookmarklet it always adds the site url as the feed url. It shouldn't be doing this right? Or does it find the feed url after the feed is approved?

![screenshot 2016-06-14 10 37 47](https://cloud.githubusercontent.com/assets/4553057/16046936/23d1e24c-321c-11e6-8c1f-a180c52542c3.png)
![screenshot 2016-06-14 10 37 36](https://cloud.githubusercontent.com/assets/4553057/16046937/23d7556a-321c-11e6-9586-60607bb1a771.png)
![screenshot 2016-06-14 10 35 02](https://cloud.githubusercontent.com/assets/4553057/16046935/23cfa82e-321c-11e6-8370-593c995bc0c2.png)

**Comment by AramZS** [comment]
This is known. Our feed processor will attempt to find the feed url on first retrieval.

**Comment by regan008** [comment]
Ahhh, ok then lets close this. @asmorton fyi.
