### ISSUE TITLE
Clicking on an empty folder just refreshes All Content

### ISSUE THREAD

**Issue by asmorton** [PressForward/pressforward#785]
Breadcrumbs are correct, but should show as empty?

![screen shot 2016-06-15 at 11 35 22 am](https://cloud.githubusercontent.com/assets/3477432/16086334/2caf2506-32ed-11e6-8c50-6b2c049a7d08.png)

**Comment by AramZS** [comment]
Should be resolved, is ready to test.

**Comment by asmorton** [comment]
This is working now. Clicking on empty feed shows nothing in AC
