### ISSUE TITLE
Create a function for generating a list of feeds

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#786]
Create a function that generates a list of feeds the site is subscribed to. It should break them down by active, alerted, and inactive. Possibly by under review too. We probably wouldn't make that outwardly visible but I can imagine scenarios where publications would. 

Here is the short code function we to do this use on DHNow: 
```
function active_feeds_function($atts) {
  extract(shortcode_atts(array(
      'status' => 'publish',
    ), $atts));


  $return_string = '<ul class="feedlist">';
  query_posts(array('post_type' => pressforward('schema.feeds')->post_type, 'post_status' =>
    $status, 'nopaging' => true, 'orderby' => 'title', 'order' => 'ASC'));

  if (have_posts()) :
    while (have_posts())  : the_post();
      $return_string .= '<li class="feeditem"><a href="'.get_post_meta(get_the_ID(), 'feedUrl', true).'"target="_blank">'.get_the_title().'</a></li>';
    endwhile;
  endif;
  $return_string .= '</ul>';
wp_reset_query();
return $return_string;
}
```

**Comment by regan008** [comment]
@AramZS I'm attempting to test this but I'm not sure if I'm doing something wrong (more than likely) or if this is a bug...but I can only get the same 3 feeds to appear when I use the shortcode for both published and alerted feeds. Here's what I see: 
![screen shot 2016-07-15 at 10 57 31 am](https://cloud.githubusercontent.com/assets/4553057/16878549/f750bc4e-4a7a-11e6-8dff-f786aabf88a3.png)

And I'm using these shortcodes: 
```
Alerted Feeds:

[feeds="alert_specimen"]

Active Feeds:

[feeds="publish"]
```

Here is the code for the shortcode that I added to functions.php in the theme: 
```function active_feeds_function($atts) {
  extract(shortcode_atts(array(
      'status' => 'publish',
    ), $atts));


  $return_string = '<ul class="feedlist">';
  query_posts(array('post_type' => pressforward('schema.feeds')->post_type, 'post_status' =>
    $status, 'nopaging' => true, 'orderby' => 'title', 'order' => 'ASC'));

  if (have_posts()) :
    while (have_posts())  : the_post();
      $return_string .= '<li class="feeditem"><a href="'.get_post_meta(get_the_ID(), 'feedUrl', true).'"target="_blank">'.get_the_title().'</a></li>';
    endwhile;
  endif;
  $return_string .= '</ul>';
wp_reset_query();
return $return_string;
}
function register_shortcodes() {
  add_shortcode('feeds', 'active_feeds_function');
}
add_action('init', 'register_shortcodes');
```

My site has 2 alerted feeds and 6 active feeds so I should be getting more than just these 3 feeds. Am I missing something here?

**Comment by regan008** [comment]
Here is a screenshot of my subscribed feeds, I actually have more that 2 alerted feeds and the fact that post politics is showing up twice is accurate -- its in there twice (but with different feed urls I think).  

![screen shot 2016-07-15 at 10 59 53 am](https://cloud.githubusercontent.com/assets/4553057/16878678/765c8fcc-4a7b-11e6-997a-52d8e7d1cfd6.png)

**Comment by AramZS** [comment]
Hey @regan008 This doesn't set up the shortcode or anything like that, the goal of the function is to allow it to be easily plugged in to other functions. 

In your theme, to test this, you should change the theme function as follows:
```
function active_feeds_function($atts) {
  extract(shortcode_atts(array(
      'status' => 'publish',
    ), $atts));

  return get_pf_feed_list($status);
}
```

**Comment by regan008** [comment]
@AramZS Gotcha -- ok then yes this is working! 

One question though, it doesn't appear to be displaying the child feeds for an opml subscription, just the opml title.  Whats the expected behavior? Shouldn't it probably show all the children of an opml subscription?  (There is also some funky formatting but I think that is on my end not yours.)

![screen shot 2016-07-18 at 11 12 09 am](https://cloud.githubusercontent.com/assets/4553057/16919677/b50ccd2c-4cd8-11e6-886d-7f083be50f98.png)

**Comment by AramZS** [comment]
If OPML subscription, create subset list.
