### ISSUE TITLE
Invalid or failed feed triggers error upon submission

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#788]
This occurred when I intentionally added a fake feed to try and trigger an alerted feed.
```
 Fatal error: Uncaught Error: Call to undefined function the_alert_box() in /srv/www/wordpress-default/wp-content/plugins/pressforward/modules/rss-import/rss-import.php:368 Stack trace: #0 /srv/www/wordpress-default/wp-includes/plugin.php(235): PF_RSS_Import::pf_feedlist_validate(Array) #1 /srv/www/wordpress-default/wp-includes/formatting.php(3882): apply_filters('sanitize_option...', Array, 'pf_feedlist', Array) #2 /srv/www/wordpress-default/wp-includes/option.php(265): sanitize_option('pf_feedlist', Array) #3 /srv/www/wordpress-default/wp-admin/options.php(215): update_option('pf_feedlist', Array) #4 {main} thrown in /srv/www/wordpress-default/wp-content/plugins/pressforward/modules/rss-import/rss-import.php on line 368
```

**Comment by regan008** [comment]
This is working now, however, I'm getting two alerts when I only submitted one feed: 

![screenshot 2016-06-16 16 45 14](https://cloud.githubusercontent.com/assets/4553057/16132582/bfb2791c-33e1-11e6-8faf-5c14f9322af0.png)

**Comment by regan008** [comment]
The feed is actually being added twice as well

**Comment by AramZS** [comment]
Ok, so for some reason, every feed is being added twice on your install, but not mine. Can you access the php error log and check there?

**Comment by regan008** [comment]
Hmmm, yes let me double check its not a weird issue on my end too. Stay tuned....

**Comment by regan008** [comment]
For whatever reason it did it for me once, and now I can't replicate it. And, of course, this is the one install I don't have a log set up on! 

So lets call this resolved unless I can make it do it again. But so far no luck.
