### ISSUE TITLE
Feeds pending review are slated as "Pending Review" inside the edit page but in Quick Edit the feeds display as published

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#789]
Lets slate this for 4.0 if its ok with you @AramZS . I don't think its absolutely crucial for 3.9 just a small thing I noticed.

![screenshot 2016-06-16 17 09 39](https://cloud.githubusercontent.com/assets/4553057/16133342/5a8c6cb0-33e5-11e6-83f9-224e5e16a424.png)
![screenshot 2016-06-16 17 09 48](https://cloud.githubusercontent.com/assets/4553057/16133354/6da59574-33e5-11e6-841d-8e2f0dc1b46b.png)
![screenshot 2016-06-16 17 09 59](https://cloud.githubusercontent.com/assets/4553057/16133360/722860e0-33e5-11e6-9c8c-cb9f5fb801ea.png)

**Comment by regan008** [comment]
This is working on every kind of feed except for alerted feeds. 
![screenshot 2016-08-05 10 49 46](https://cloud.githubusercontent.com/assets/4553057/17440473/bae05d42-5afa-11e6-82f0-02eed385b325.png)
![screenshot 2016-08-05 10 49 38](https://cloud.githubusercontent.com/assets/4553057/17440474/bae2e8a0-5afa-11e6-877f-65f5a7c906d8.png)

**Comment by AramZS** [comment]
@regan008 that's expected behavior, alerted feeds are still active and regularly very checked to see if they come back online. Is that ok? If not, it's a separate issue anyway and if there is nothing else we should close this and open one for the next sprint.

**Comment by regan008** [comment]
Hm, lets close this for now. I'm wondering if that is confusing since alerted is a status up top but we can revisit this later.
