### ISSUE TITLE
Position of Source Statement Option is Broken

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#797]
The source is defaulting to the top of the post regardless of the setting in Preferences. 
![screen shot 2016-07-18 at 10 57 05 am](https://cloud.githubusercontent.com/assets/4553057/16919129/77988a14-4cd6-11e6-84df-486f12ce9844.png)
![screen shot 2016-07-18 at 10 57 22 am](https://cloud.githubusercontent.com/assets/4553057/16919131/78c395b4-4cd6-11e6-96c7-2ddeaa5626de.png)

**Comment by regan008** [comment]
@AramZS I'm still seeing it default to the source at the top of the post regardless of how the option is set. Should there be a commit tagged here?

**Comment by AramZS** [comment]
@regan008 I just couldn't duplicate this problem. It happens on save. It won't change positions if you've already saved the post, is that what is being reported here?

**Comment by regan008** [comment]
@aramzs I'm still having trouble to get this to work on posts drafted or nominated from all content. The only place I can get it to work is on posts that are nominated/drafted via the bookmarklet.
