### ISSUE TITLE
Items either not being sent to nominated at all or taking a very long time and triggering errors

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#799]
I see this in the console: 
![screen shot 2016-07-19 at 10 46 49 am](https://cloud.githubusercontent.com/assets/4553057/16954486/063c7f64-4d9f-11e6-9328-147643e2a783.png)

If the item does end up getting sent to nominated, there are a number of errors below the title and the nominated by field in the info tab is displaying oddly. 
![screen shot 2016-07-19 at 10 55 32 am](https://cloud.githubusercontent.com/assets/4553057/16954606/70d234ae-4d9f-11e6-9251-059a12a0b51d.png)

**Comment by AramZS** [comment]
With the fix, I can't duplicate this. Tell me if the latest fixes this.

**Comment by regan008** [comment]
Yup, nominating is working now

**Comment by asmorton** [comment]
This isn't working on pftesting.chnm. I haven't been able to get anything into nominated, just a seemingly permanent loading bar.
![screen shot 2016-07-19 at 1 15 46 pm](https://cloud.githubusercontent.com/assets/3477432/16959407/ef0d2398-4db2-11e6-9952-4110cb54e3d0.png)

**Comment by regan008** [comment]
Confirmed, this is back to working!
