### ISSUE TITLE
Images appear in Nominated

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#800]
Not sure why, but I have a post that is rendering images in Nominated

The link is: https://smittenkitchen.com/2016/07/corn-bacon-and-parmesan-pasta/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+smittenkitchen+%28smitten+kitchen%29

here is what I see: 
![screen shot 2016-07-19 at 1 10 27 pm](https://cloud.githubusercontent.com/assets/4553057/16959307/75954324-4db2-11e6-97b7-994bd741d08d.png)

**Comment by regan008** [comment]
Still seeing this but this time on a different blog. Here is the url: http://usreligion.blogspot.com/2016/07/sportianity-at-forty-rereading-frank.html

![screenshot 2016-07-23 21 24 07](https://cloud.githubusercontent.com/assets/4553057/17081182/ed336ab6-511b-11e6-9e1c-586a69fef257.png)

**Comment by regan008** [comment]
Here is the food blog I was seeing this on: https://smittenkitchen.com/

**Comment by AramZS** [comment]
`pf_prep_item_for_submit` is the problem function.

**Comment by AramZS** [comment]
It will only fix nominations made from here on forward.
