### ISSUE TITLE
New York Times Articles Failing in Bookmarklet

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#801]
I'm not sure why, but I'm getting all kinds of errors when I try to nominate posts from the New York  Times. I think it might be due to the way they are formatting convention posts but this might be something to look into: 

![screen shot 2016-07-19 at 1 14 43 pm](https://cloud.githubusercontent.com/assets/4553057/16959544/a115b83e-4db3-11e6-8ed9-8e28ffde6f42.png)

**Comment by regan008** [comment]
This is still failing for me on the same [nyt article](http://www.nytimes.com/interactive/2016/07/19/opinion/campaign-stops/Republican-Convention-Day-2-Campaign-Stops.html?list_item=Populism-Without-Racism&action=click&pgtype=Homepage&clickSource=story-heading&module=opinion-c-col-left-region&region=opinion-c-col-left-region&WT.nav=opinion-c-col-left-region). There are less errors appearing but I do still see an error in the title field and above the nominate/draft buttons. Here is the full text since the screenshot below cuts off the errors. In the title box: ``` <br /><b>Notice</b>:  Undefined variable: title in <b>/srv/www/wordpress-default/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php</b> on line <b>816</b><br /> ```

Above the nominate/draft buttons: ``` Notice: Undefined variable: author_retrieved in /srv/www/wordpress-default/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php on line 640 ```

![screenshot 2016-07-23 21 09 15](https://cloud.githubusercontent.com/assets/4553057/17081123/03c71dec-511a-11e6-815b-6c2d1ed57c9f.png)

**Comment by AramZS** [comment]
This happens on nominate, after button is pressed.

**Comment by AramZS** [comment]
I think this is fixed now.

**Comment by regan008** [comment]
@AramZS I'm still having it happen (retested it on that same NYT article from above.) It happens once you click nominate.

**Comment by AramZS** [comment]
@regan008 It seems to not be happening when no category is selected. Can you confirm?

**Comment by regan008** [comment]
Hmm, no I am still having it happen when I select a category or when I don't

**Comment by AramZS** [comment]
I think this is finally resolved. The URLs were too long for that article. Resolved by getting canonical.
