### ISSUE TITLE
Duplication in All Content

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#803]
I'm just noticing that there is some item duplication in All Content. See the screenshots below. Would a copy of the log be useful to diagnose this @AramZS?

![screenshot 2016-07-26 14 20 28](https://cloud.githubusercontent.com/assets/4553057/17150173/69383e76-533c-11e6-99a9-288bd86d2e1a.png)
![screenshot 2016-07-26 14 20 16](https://cloud.githubusercontent.com/assets/4553057/17150174/693c425a-533c-11e6-9de4-644a52ccb9fd.png)

**Comment by AramZS** [comment]
Duplication posts detected at post level, but not nomination level. Unsure of Items, need to check
