### ISSUE TITLE
Oddity? Items sent to draft from All Content vs. Bookmarklet

### ISSUE THREAD

**Issue by asmorton** [PressForward/pressforward#806]
Bookmarklet items sent to draft appear in Nominated without the send to draft button turning green. Items send to draft from All Content do show they've been sent to draft in Nominated.

**Comment by AramZS** [comment]
I believe this to be resolved.

**Comment by kelle** [comment]
I'm also seeing this behavior and don't think it's been resolved...the button is not turning green for articles sent to draft via the bookmarklet.

**Comment by asmorton** [comment]
@AramZS looks like this is broken again on pftesting. It was working briefly before release.

**Comment by regan008** [comment]
Same as #918
