### ISSUE TITLE
Broken Feeds in OPML Subscription continue to be added

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#808]
I’ve got an opml subscription that has a broken feed. The feed is broken but it is being duplicated in subscribed feeds for some reason. It is showing up as a red alerted feed 5 times with different dates for when it was added. For example, it says I added the feed this morning which is not true.
![screen shot 2016-08-08 at 10 34 07 am](https://cloud.githubusercontent.com/assets/4553057/17483432/fabe4ef0-5d53-11e6-85c5-521ac502d1a7.png)

**Comment by AramZS** [comment]
Please link the OPML file

**Comment by regan008** [comment]
http://www.inoreader.com/reader/subscriptions/export/user/1005688124/label/Gizmos

**Comment by AramZS** [comment]
Can you check if this is fixed by the 4.0.1 branch?

**Comment by regan008** [comment]
Added it as a new feed on my laptop just now, will wait to see if it does it again

**Comment by regan008** [comment]
I'm not seeing this happen anymore.
