### ISSUE TITLE
Clicking on a folder in the PressForward Add Folders page, redirects you to post categories 

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#809]

**Comment by AramZS** [comment]
I'm confused. What exactly are you doing? I can't seem to duplicate this, but mby I'm not understanding the problem.

**Comment by regan008** [comment]
Sorry this is confusing. I have a screencast that I will throw in slack when I get into the office. Basically, here are the steps that are leading to this: 

1. Navigate to the Folders Panel in the PressForward Menu
2. Click on a folder to go to the edit folder page (where you can change things like slug etc)

Once you click on a folder you are redirected to the post category edit page. It still works, but its a big confusing because on the WordPress menu it indicates that you are editing a Post Category not a Folder anymore.  Does that make sense?

**Comment by regan008** [comment]
Also, it isn't a big issue and if you want to push to 4.1.x that is totally fine

**Comment by AramZS** [comment]
The navigation in the sidebar changes, not the main body of the page.

**Comment by regan008** [comment]
Fixed!
