### ISSUE TITLE
Cannot activate plugging, reporting Parse error: Syntax Error

### ISSUE THREAD

**Issue by dreamermanu** [PressForward/pressforward#814]
Hi guys
I installed PressForward and when I tried to activate it this happened. I uninstalled and tried it again and got the same result. Any ideas as to what is happening?

Parse error: syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in /home/vlistdu5/public_html/wp-content/plugins/pressforward/Libraries/PFOpenGraph.php on line 56

**Comment by AramZS** [comment]
Hi @dreamermanu - we're looking through this now. It would help if you knew what version of PHP was currently on your server?

**Comment by adathakkar** [comment]
I am having the same issue.

**Comment by AramZS** [comment]
Hi all,

After some testing, I have determined the issue lies in our backup retrieval method with cURL. We will release a hotfix for this issue shortly. 

If you would like to use this feature and turn off the problem before than, please ask whomever runs your server to install cURL for PHP.

**Comment by AramZS** [comment]
Patch to fix this should be in place with https://github.com/PressForward/pressforward/commit/078bb4b8d6ec9b3b66d4c5b0992e39fb8cc56249 - I will release it shortly

**Comment by regan008** [comment]
@AramZS Was this patch released? I'm still having the problem on our multisite.
