### ISSUE TITLE
pf_source_link not populating

### ISSUE THREAD

**Issue by mchavezi** [PressForward/pressforward#815]
I am running fresh install of multisite with no plugins except PressForward. When I subscribe to a feed from a sub site in the same install, the "pf_source_link" is not populated when sending to draft.

Is this a bug or I am mis-configuring something?

Thanks,
Michael

**Comment by AramZS** [comment]
@bigbassroller  Might be a bug. Is this a live site or is it possible to flip on debugging? And if it isn't can you walk me through the exact series of actions you take to send to draft?

**Comment by AramZS** [comment]
I believe this is now working in upcoming 4.1.x release @casmir72. Are you trying `pressforward('controller.metas')->get_post_pf_meta([postIDnumber], 'source_title')`?
