### ISSUE TITLE
Project MUSE RSS broken.

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#816]
From: https://wordpress.org/support/topic/pressforward-does-not-load-project-muse-rss-feeds 

Our Press Forward (4.0.2) on 18th-Century Common is not loading any RSS feed provided by Johns Hopkins' Project MUSE, but it's not throwing errors, either. Specifically, the 5 feeds we would like to add are below:

http://muse.jhu.edu/journals/eighteenth_century_fiction/latest_articles.xml
http://muse.jhu.edu/journals/eighteenth-century_studies/latest_articles.xml
http://muse.jhu.edu/journals/restoration/latest_articles.xml
http://muse.jhu.edu/journals/studies_in_eighteenth_century_culture/latest_articles.xml
http://muse.jhu.edu/journals/the_eighteenth_century/latest_articles.xml
It does seem that Project MUSE RSS feeds don't strictly adhere to RSS but use a customized variant that also makes use of RDF. However, these feeds are successfully fetched by other feed readers.

For example, we noted that PressForward uses WordPress's built-in feed functionality — which itself uses SimplePie. When we tested one of the Project Muse feeds in SimplePie, the feeds worked fine.

Additionally, another RSS reader, FeedBin, also fetches these feeds successfully.

How can we fetch these feeds within our installation of PressForward? Many thanks!

**Comment by AramZS** [comment]
Because this feed is not standard, we are unable to parse some the aspects of these feeds.

**Comment by regan008** [comment]
Confirmed
