### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by adathakkar** [PressForward/pressforward#818]
I tried activating it on multisite and gave me error "header missing" I then deleted the plugin from server and tried reinstalling from wordpress and got error "cannot install" So I tried uploading the plugin via ftp and installing it, here is the error message I get.

Installing Plugin from uploaded file: pressforward.4.0.4.zip
Unpacking the package…

Installing the plugin…

The package could not be installed. No valid plugins were found.

Plugin install failed.

**Comment by regan008** [comment]
Can you tell us what version of Wordpress and php you are using so we can try to replicate this issue?

**Comment by adathakkar** [comment]
PHP 5 this is a multisite main site is http://beautifulcity.us

**Comment by regan008** [comment]
@AramZS I'm having the same problem with pftesting. Its very odd -- it looks like the plugin is installed, and Wordpress won't let me reinstall it via the plugin directory. The install button is grayed out and it says "already installed".  However, it doesn't show up at all in the list of installed plugins

**Comment by AramZS** [comment]
There was an upload error that hit some but not all WP configurations, now resolved with 4.0.5

**Comment by slwestcott** [comment]
That solved the problem I was having with installation, as well.
