### ISSUE TITLE
Error in Nominated This

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#822]
I'm getting this error when I try to nominate a NYT article from the bookmarklet: 
```
Notice: Trying to get property of non-object in /srv/www/wordpress-default/wp-content/plugins/pressforward/Libraries/FiveFiltersReadability/Readability.php on line 1120
```
Possibly related to #811

**Comment by regan008** [comment]
@AramZS I can't find any NYT articles that aren't triggering this error but here are some examples: 
* http://www.nytimes.com/2016/08/30/opinion/cutting-ties-to-the-clinton-foundation.html
* http://www.nytimes.com/2016/08/30/well/eat/why-your-granola-is-really-a-dessert.html?contentCollection=smarter-living
* http://www.nytimes.com/2016/08/31/technology/apple-tax-eu-ireland.html
* http://www.nytimes.com/2016/08/24/us/politics/facebook-ads-politics.html?ref=technology

**Comment by casmir72** [comment]
I tested several NYT articles without issue.

**Comment by regan008** [comment]
I think this can be closed
