### ISSUE TITLE
Duplication in All Content

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#823]
I'm seeing duplication in All Content again. 
![screen shot 2016-08-29 at 1 37 55 pm](https://cloud.githubusercontent.com/assets/4553057/18060743/d4d49ac8-6ded-11e6-8999-31e959273444.png)

**Comment by AramZS** [comment]
Ok, please link the Bolt Beat rss feed?

**Comment by regan008** [comment]
http://boltbeat.com/feed/

**Comment by casmir72** [comment]
Tested the Bolt Beat and several other feeds without any duplication issue.
