### ISSUE TITLE
Tags are not being passed through to draft

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#824]
I'm having an issue where tags appear in the info panel of an item on both All Content and Nominated but the tags never get passed through to the drafted post. 
![screen shot 2016-08-30 at 12 32 38 pm](https://cloud.githubusercontent.com/assets/4553057/18097903/edc6dab2-6ead-11e6-8ee4-4b3007d15591.png)
![screen shot 2016-08-30 at 12 32 55 pm](https://cloud.githubusercontent.com/assets/4553057/18097904/ef6ce1b8-6ead-11e6-8ae1-be3da94ddade.png)

**Comment by AramZS** [comment]
Ready for testing

**Comment by casmir72** [comment]
Tags are working properly.
