### ISSUE TITLE
Add wordcount across the board to all objects

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#825]
Items, Nominations and Posts should have word count on them, it should be sortable and it should re-count after readable

**Comment by regan008** [comment]
@AramZS when you say it should be sortable, what do you mean? How would I go about sorting the wordcount field in the api?

**Comment by AramZS** [comment]
@regan008 There's no way to do anything with it right now, it is just how it is saved in the database. As long as it shows up in the API response we're solid on this issue.

**Comment by regan008** [comment]
This works on the Posts endpoint. Will test on the items endpoint when that is ready!

**Comment by regan008** [comment]
I can confirm that this is working on items and posts now. Should I now be able to sort by wordcount on the items endpoint @AramZS? If so, what would the syntax for that be?
