### ISSUE TITLE
V4.0.5 source_title no longer being set

### ISSUE THREAD

**Issue by plexus77** [PressForward/pressforward#827]
Hi guys,

Love your plugin by the way, it has been a great help for a large news site I have built that republishes some content from other sites.

I recently updated the pressforward plugin and now when we send items to draft the source_title is no longer being set.

I have tried tracing the issue myself but have not had any luck.  Any pointers or a fix would be great.

Regards,
Morgan

**Comment by AramZS** [comment]
Hi @plexus77 We'll take a look at this issue.

**Comment by casmir72** [comment]
I am still not getting the source_title in drafts.

**Comment by AramZS** [comment]
I believe this is now working in upcoming 4.1.x release @casmir72. Are you trying `pressforward('controller.metas')->get_post_pf_meta([postIDnumber], 'source_title')`?

**Comment by plexus77** [comment]
Thanks guys....
