### ISSUE TITLE
66% of my Subscribed Feeds are Broken

### ISSUE THREAD

**Issue by devinbalkind** [PressForward/pressforward#828]
I've checked the validity of the RSS feeds I'm subscribed to in PressForward and yet many of the feeds are declared broken by the plugin and items won't flow through them. If I delete the feed and resubscribe it works again but then becomes "broken" a few days later. 

Am I doing something wrong?  Are there techniques for ensuring feeds don't break?

**Comment by AramZS** [comment]
Hi @devinbalkind - Can you give us some examples of feeds that are breaking consistently?

**Comment by AramZS** [comment]
@devinbalkind  The next release should use the value more effectively, but until then I think that using the `No alerts, never let feed go inactive.` check box in any broken feeds that you are sure are working should resolve this issue.

**Comment by devinbalkind** [comment]
This resolved the issue. Thanks!
