### ISSUE TITLE
Add feed items to the pf API endpoint. 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#829]

**Comment by AramZS** [comment]
This is now complete. We have all non-hidden endpoints on the public API under the `pf/v1` endpoint. Ready to test.

**Comment by jccatalano** [comment]
Should inactive feeds appear on the endpoint?

**Comment by regan008** [comment]
@AramZS I've been playing with this all morning and I see no issues. My only question would be -- is there a way to view the items associated with a particular feed? We tried to filter by feed in the feed_items endpoint (?feed=feedid) but that didn't work. Is this not something that is available? Or are we doing it the wrong way?

**Comment by jccatalano** [comment]
1. If you add a new folder does the folder appear?  (YES)
* Are the correct number of feeds appearing in the feed? (YES)
* add a new feed to the folder does the feed appear in the endpoint? (YES)

2. If you add a new feed, does the feed appear on the feeds endpoint? (YES)
* Is the metadata correct? (YES, custom field metadata matches endpoint)
* Does the time retrieved populate correctly? (YES)
* If you delete a feed does it disappear from the response? (YES)

3. On the feeds endpoint is the metadata correct for alerted feeds? For inactive feeds? (YES, NO-innactive feeds do not appear on the endpoint)

**Comment by regan008** [comment]
@AramZS I have found no issues with this, so I am going to go ahead and close this issue.
