### ISSUE TITLE
Bookmarklet Nomination Posted Time Inaccurate 

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#830]
Nominations using the Bookmarklet do not display the accurate "posted" time for items. One user nominated content at 9:38 am EST, but the "posted" time was 1:38 pm (in the future). 
A second user nominated content at 11:53 am, but the "posted" time was 3:38 pm. It appears that the Bookmarklet is 4 hours ahead of time. Still this time is inaccurate because it does not capture when the item was originally posted. 

The normal retrieval process appears to be working properly and recording the correct "posted" time for items.

**Comment by AramZS** [comment]
It sounds like something is not catching the server or site's current time. I will investigate.

**Comment by jccatalano** [comment]
The bookmarklet works off of the WP time settings.
