### ISSUE TITLE
Drafted Items with tags are generating tag id numbers as tags

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#833]
When I draft a post that has tags, the tags are passed through to the draft but it appears that it is also adding the tag ID number as a tag? At least I think that is what is happening. Here is what I see in the Edit Posts page: 
![screen shot 2016-09-19 at 3 51 08 pm](https://cloud.githubusercontent.com/assets/4553057/18646779/1d88950a-7e81-11e6-94ce-ec2079606b33.png)

**Comment by AramZS** [comment]
Basic patch, resolved for 4.1.x release.

**Comment by regan008** [comment]
Confirmed -- this is fixed!

**Comment by regan008** [comment]
@AramZS This is happening again in 4.2.x

**Comment by regan008** [comment]
![screen shot 2016-10-12 at 12 59 42 pm](https://cloud.githubusercontent.com/assets/4553057/19319654/cc4d5c0e-907b-11e6-97a4-ea1f9966ef6c.png)

**Comment by AramZS** [comment]
Are you absolutely sure the server is running the latest version? I'm just not sure how this could have been fixed and then unfixed.

**Comment by regan008** [comment]
@AramZS Ok yes, you are right. This must have been left over on my local install at work. I will scrap that and start fresh next week. This is resolved.
