### ISSUE TITLE
Canonical not hooking into WPMU SmartCrawl SEO plugin

### ISSUE THREAD

**Issue by handythinks** [PressForward/pressforward#834]
https://premium.wpmudev.org/project/smartcrawl-wordpress-seo

The way this plugin works is it assigns the current post as Canonical unless it is told otherwise. So there are conflicting canonical tags in the source of nominated items.

**Comment by AramZS** [comment]
Hi @handythinks 

We do attempt to hook and overwrite the canonical tag in a number of ways and for a number of plugins, however, since this is a premium plugin I don't have the ability to examine the code and add it's canonical statement to our set of overrides. Perhaps you can ask in the forum for the filter hook that we could use to fix this issue?

-Aram

**Comment by handythinks** [comment]
*Chris Handy*Agency
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S1KL8bGch0W2n0x6l2B9nMJN7t6js6d0GfxN1qfWCn1NJ9pf459Cfv03?t=http%3A%2F%2Fwww.thinkhandy.com%2F&si=8081245&pi=c72b31f0-7d69-4103-8a5f-8e05a2dbfcc9>
 | Podcast
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S1KL8bGch0W2n0x6l2B9nMJN7t6js6d0GfxN1qfWCn1NJ9pf459Cfv03?t=http%3A%2F%2Fwww.togo.fm%2F&si=8081245&pi=c72b31f0-7d69-4103-8a5f-8e05a2dbfcc9>
 | LinkedIn
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S1KL8bGch0W2n0x6l2B9nMJN7t6js6d0GfxN1qfWCn1NJ9pf459Cfv03?t=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fchristophermhandy&si=8081245&pi=c72b31f0-7d69-4103-8a5f-8e05a2dbfcc9>
 | Twitter
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S1KL8bGch0W2n0x6l2B9nMJN7t6js6d0GfxN1qfWCn1NJ9pf459Cfv03?t=https%3A%2F%2Ftwitter.com%2Fhandythinks&si=8081245&pi=c72b31f0-7d69-4103-8a5f-8e05a2dbfcc9>
|
Calendar
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S1KL8bGch0W2n0x6l2B9nMJN7t6js6d0GfxN1qfWCn1NJ9pf459Cfv03?t=http%3A%2F%2Fwww.thinkhandy.com%2Fcall-chris&si=8081245&pi=c72b31f0-7d69-4103-8a5f-8e05a2dbfcc9>
817.372.9899 (c) 817.601.5253 (o)
Are you listening to my radio show
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S1KL8bGch0W2n0x6l2B9nMJN7t6js6d0GfxN1qfWCn1NJ9pf459Cfv03?t=http%3A%2F%2Fwww.togo.fm%2F&si=8081245&pi=c72b31f0-7d69-4103-8a5f-8e05a2dbfcc9>
?

**Comment by handythinks** [comment]
[72160_smartcrawl-easier-faster-wordpress-seo-1.7.7.zip](https://github.com/PressForward/pressforward/files/483074/72160_smartcrawl-easier-faster-wordpress-seo-1.7.7.zip)

**Comment by regan008** [comment]
@AramZS Suggestions on how to test this?

**Comment by AramZS** [comment]
You can download the plug in from the link above and check the source on pf and non pf posts to make sure that all canonical links are the same.

**Comment by handythinks** [comment]
can I get yall an updated package?

Chris Handy
ClosedWon.com <https://www.closedwon.com/?ref=emsigch>

   1. Send me an instant message <http://closedwon.drift.com/chris>
   2. Schedule a meeting on my calendar
   <https://closedwon.drift.com/chris?schedule>
   3. Connect with me on LinkedIn
   <https://www.linkedin.com/in/christophermhandy>

**Comment by AramZS** [comment]
@handythinks I'd hope that the hooks are the same, but yes, if you can upload a new version that would be great.

**Comment by jccatalano** [comment]
Working
