### ISSUE TITLE
Add a comment via Nominate This

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#843]

**Comment by boonebgorges** [comment]
I envision a future where you'll be able to see and manage comments on an item at all points during the PF lifecycle: during nomination, during review, and when the item becomes a 'post'. With that in mind, I've done the following. I built a 'Comments' section that appears in the sidebar of the block editor. For the time being, this appears only when using Nominate This. It looks like this:

![Screenshot_2024-07-31_14-25-12](https://github.com/user-attachments/assets/27799843-bd1f-440a-91db-eff4073e2a98)

The idea is that you don't need a full-fledged comment section here - it's a new item, so there are no comments yet - but you just need a single field where you can add a note, which in turn becomes the first comment after submission:

![Screenshot_2024-07-31_14-25-36](https://github.com/user-attachments/assets/caa74f2d-d1c3-44ea-a703-e174d0479910)

I've built this in such a way that, in a future release, we can show the same Comments sidebar section when viewing a `post`. When that happens, you'll see a different interface, one that allows you to see all existing comments as well as post new ones (similar to what you see in the comment modal, but built for the block editor).  I'll open a separate ticket to discuss this future enhancement.

For the time being, the new field should provide a useful bit of functionality as a standalone feature.
