### ISSUE TITLE
Fatal error after recent updat

### ISSUE THREAD

**Issue by adathakkar** [PressForward/pressforward#847]
Hi,

I updated the plugin yesterday. Now when I try to login to my control panel I get the following error: Fatal error: Can't use method return value in write context in /home/cp005/public_html/wp-content/plugins/pressforward/Libraries/FiveFiltersReadability/Readability.php on line 1121

**Comment by AramZS** [comment]
Issue confirmed with older versions of php (pre-5.5). You should probably update your PHP version, but we do support 5.4. A patch is coming shortly.

**Comment by devinbalkind** [comment]
This took my site down as well. PHP version 5.3.29

**Comment by AramZS** [comment]
Hey, this is occurs only with php 5.4 installs or lower. We've just released a patch to resolve it, but we highly recommend you update the version of PHP on your server.
