### ISSUE TITLE
Fatal Errors causing sites to crash

### ISSUE THREAD

**Issue by eolson3** [PressForward/pressforward#850]
PFSample throws the following error: 
Fatal error: Can't use method return value in write context in /websites/pfsample/www/wp-content/plugins/pressforward/Libraries/FiveFiltersReadability/Readability.php on line 1121

Partner site, OSI, was throwing the following error until PF files deleted:
Fatal error: Can't use function return value in write context in /home/content/77/7391577/html/osi/wp-content/plugins/pressforward/Controllers/HTTPTools.php on line 155

php 5.4 for OSI.

**Comment by AramZS** [comment]
@eolson3 The first error was resolved with the release of 4.1.1

**Comment by eolson3** [comment]
Just tried updating pfsandbox to 4.1.1.  It is throwing the second error, but I can at least access the site.

**Comment by AramZS** [comment]
Hi, this should be resolved with 4.1.2, yes?

**Comment by eolson3** [comment]
I actually can't access the site from off-campus, but I will check on Thursday.

**Comment by regan008** [comment]
@eolson3 have you checked to see if this can be closed?
