### ISSUE TITLE
Nominate This gives 404 Error

### ISSUE THREAD

**Issue by devinbalkind** [PressForward/pressforward#857]
The popup appears like this:
![screenshot 2016-10-21 at 19 10 14](https://cloud.githubusercontent.com/assets/444311/19614321/05ab1084-97c2-11e6-88a0-93ce00490c20.png)

The URL of that popup is:
https://resiliencecolab.org/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php?u=https%3A%2F%2Fgithub.com%2FPressForward%2Fpressforward%2Fissues%2Fnew&t=New%20Issue%20%C2%B7%20PressForward%2Fpressforward&s=&v=4

The bookmarklet code is:
javascript:var d=document,w=window,e=w.getSelection,k=d.getSelection,x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:0)),f='https://resiliencecolab.org/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php',l=d.location,e=encodeURIComponent,u=f+'?u='+e(l.href)+'&t='+e(d.title)+'&s='+e(s)+'&v=4';a=function(){if(!w.open(u,'t','toolbar=0,resizable=1,scrollbars=1,status=1,width=720,height=620'))l.href=u;};if (/Firefox/.test(navigator.userAgent)) setTimeout(a, 0); else a();void(0);

I'm using Chrome on a Chromebook.

Thanks so much.

**Comment by eolson3** [comment]
Hi, David,

Most likely you've used a bookmarklet from another site or one from a previous version of PressForward.  Can you try adding the bookmarklet again and starting from there?


Eric

**Comment by devinbalkind** [comment]
I tried again. Same error.

URL:
https://resiliencecolab.org/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php?u=https%3A%2F%2Fsahanafoundation.org%2Fabout%2F&t=About%20%E2%80%93%20Sahana%20Foundation&s=&v=4

Code:
javascript:var d=document,w=window,e=w.getSelection,k=d.getSelection,x=d.selection,s=(e?e():(k)?k():(x?x.createRange().text:0)),f='https://resiliencecolab.org/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php',l=d.location,e=encodeURIComponent,u=f+'?u='+e(l.href)+'&t='+e(d.title)+'&s='+e(s)+'&v=4';a=function(){if(!w.open(u,'t','toolbar=0,resizable=1,scrollbars=1,status=1,width=720,height=620'))l.href=u;};if (/Firefox/.test(navigator.userAgent)) setTimeout(a, 0); else a();void(0)

Chrome on an Ubuntu Desktop.

Thanks.

**Comment by regan008** [comment]
@eolson3 I'm assigning this to @AramZS  instead. I'm not at all sure how to go about diagnosing the issue

**Comment by AramZS** [comment]
Hi @devinbalkind Can you tell me what the install folder of your WordPress site is in your server?

**Comment by devinbalkind** [comment]
Hi. It started working. I don't know why. You can close this.
