### ISSUE TITLE
register_rest_field() only available on WP 4.7 or with WP-API

### ISSUE THREAD

**Issue by boonebgorges** [PressForward/pressforward#859]
In version 4.1.2, `APIWithMetaEndpoints::register_rest_post_read_field()` calls `register_rest_field()`. The latter function is from the WP-API plugin. When WP-API is not available, a fatal error is thrown.

Is WP-API a requirement for PressForward? I couldn't find it in the documentation anywhere.

**Comment by AramZS** [comment]
@boonebgorges Hi, all the calls are tucked away inside of WP-API action hooks, if the action hooks are not called that function should never be called. You're seeing the system throwing this error?

**Comment by boonebgorges** [comment]
Yes, and it's happening on a Jetpack admin page. So I wonder whether 
Jetpack is triggering an API endpoint. Can you give me a quick rundown 
of the stack trace leading up to the call, so I can cross-reference?

**Comment by AramZS** [comment]
@boonebgorges Ok, here's how they get called in our current active release:

Core/API/APIWithMetaEndpoints is an extendable class, it is extended by both 
 - https://github.com/PressForward/pressforward/blob/master/Core/API/PostExtension.php
 - https://github.com/PressForward/pressforward/blob/master/Core/API/FeedEndpoint.php

Both of which add the function `register_rest_post_read_meta_fields` to the `rest_api_init` action hook.

They hook it by declaring it in their own `action_hooks()` functions, which implement a contract for the loader seen at https://github.com/PressForward/pressforward/blob/master/Libraries/Jaxion/src/Core/Loader.php#L60. That is processed through `add` to assure format - https://github.com/PressForward/pressforward/blob/master/Libraries/Jaxion/src/Core/Loader.php#L112 and then simply passed to `add_action` https://github.com/PressForward/pressforward/blob/master/Libraries/Jaxion/src/Core/Loader.php#L37 

Both of the extending classes establish their class-level variables.
 
`Core\API\APIWithMetaEndpoints\register_rest_post_read_meta_fields()` 
walks through `APIWithMetaEndpoints\valid_metas()` which calls the PF Meta controller's class and filters the list of metas against the extending classes `level`. 

Then each of those meta labels gets passed to `Core\API\APIWithMetaEndpoints\register_rest_post_read_field()` and that function calls `register_rest_field()`. Those are the only times it gets actively called, I don't see how it could trigger outside of the `rest_api_init` function. 

The only other place that function gets called is in `Core\API\PostExtension\item_id` which doesn't get called by anything, I set up that function and forgot to remove it. Is that enough detail to help troubleshoot?

**Comment by boonebgorges** [comment]
Thanks for the detailed outline, @AramZS.

The 'rest_api_init' action was introduced in WP 4.4 along with the API infrastructure. I don't believe it's a reliable way to determine whether the core endpoints (and `register_rest_field()`) are available.

If I'm understanding correctly, `register_rest_post_read_field()` is modifying the values returned by `wp-json/wp/v2/posts`. In other words, you are piggybacking on the existing post endpoint, rather than creating your own. This suggests that polyfilling `register_rest_field()` is not enough - you need true dependence on the post endpoint. I think the best way to do that is something like:

```php
global $wp_rest_server;
$routes = $wp_rest_server->get_routes();
$has_posts_endpoint = isset( $routes['/wp/v2/posts'] );
```

**Comment by AramZS** [comment]
@boonebgorges That is indeed what is happening in one of those cases. Ok, good to know. I will add that check to our api loading process.

**Comment by AramZS** [comment]
@boonebgorges Give the new version a try, should have resolved this issue by only setting up the API pieces without the post endpoint when the post endpoint is not available.

**Comment by boonebgorges** [comment]
Thank you, @AramZS! This seems to do the trick.
