### ISSUE TITLE
Fatal error: Cannot use object of type WP_Error as array in /home/arazuc/chronoto.pe/wp-content/plugins/pressforward/Core/Utility/Forward_Tools.php on line 329

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#860]

**Comment by AramZS** [comment]
Happens on the URL at: https://www.buzzfeed.com/nitashatiku/trump-supporting-startup-ceo-kicked-out-of-y-combinator?utm_term=.qqmjLoQWA#.jg2bzkXy4

**Comment by regan008** [comment]
Confirmed this is working now
