### ISSUE TITLE
Error on Pfsample: Allowed Memory Size Exhausted

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#861]
Roberto said this was triggered in the server logs on Oct 30th. 

```Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2593758 bytes) in /websites/pfsample/www/wp-includes/functions.php on line 443```

@AramZS Do you think this is related to the delete function?

**Comment by AramZS** [comment]
This is `maybe_serialize`

**Comment by AramZS** [comment]
Mby related to hanging on Add New Post

**Comment by AramZS** [comment]
Not sure if related, but `posted_submitbox_pf_actions` should fire in an alternate way when post is a New Post.

**Comment by regan008** [comment]
@AramZS I updated this morning and am still having this issue when adding a new post. It hangs and doesn't want to load the remainder of the page

**Comment by regan008** [comment]
I see this in my console, but I'm not positive this is related to the issue
![screenshot 2016-11-29 10 47 25](https://cloud.githubusercontent.com/assets/4553057/20716764/4da20f32-b621-11e6-8b7a-a32b1de28855.png)

**Comment by regan008** [comment]
@AramZS Is this in the 4.2 release?

**Comment by regan008** [comment]
@AramZS I because we're still having the same issue (even with last night's release candidate) on pfsample

**Comment by regan008** [comment]
I think this has been fixed so I'm going to close it for now and will reopen if it reappears.
