### ISSUE TITLE
Test 4.2 with WP3.8 and higher

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#862]
Create a new site using `vv create` from within your vagrant directory. Be sure to turn debug on and add the sample content.
- [x] v3.8
- [x] v3.9
- [x] v4.0
- [x] v4.1
- [x] v4.2
- [x] v4.3
- [x] v4.4
- [x] v4.5
- [x] Trunk Version (4.7?)

**Comment by regan008** [comment]
All looks good on 4.5

**Comment by regan008** [comment]
@jccatalano I only got through 4.4, 4.5, and troubleshooting 4.7 this morning. Go ahead and check off whatever you get through on here

**Comment by jccatalano** [comment]
WP versions 3.8 - 4.3 look good. They are still installed on my machine if further testing is needed.

**Comment by regan008** [comment]
I have problems accessing the api on 4.4 and 4.5 regardless of whether PF is installed. And on 4.6 _only_ when pressforward is installed.

**Comment by regan008** [comment]
Note to self, the API requires 4.4 and up
