### ISSUE TITLE
Archived items are disappearing

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#863]
When I archive a nominated item and then try to filter by only archived, I see no items. I'm seeing this on 4.4 but will confirm on other versions.

**Comment by regan008** [comment]
Yeah this is happening in all wp versions.

**Comment by AramZS** [comment]
Do we know if the query showing them is broken or if they're actually disappearing from the database?

**Comment by regan008** [comment]
Good question, how would I test that?

**Comment by regan008** [comment]
@AramZS Hold off on spending too much time on this, it is working now on my trunk install. Let me finish testing the other versions and figure out if this is version specific or something weird with my work computer

**Comment by regan008** [comment]
It worked both in the db and on the UI in the 4.7 trunk build

**Comment by regan008** [comment]
We haven't been able to replicate this so I'm going to close this. Must have been a fluke with my install.
