### ISSUE TITLE
Admin Dashboard Breaks with Trunk Version

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#864]
@AramZS I'm trying to test the latest trunk build (4.7?) and am having issues. When the plugin isn't activated I have no problem accessing the dashboard but as soon as I activate it , I then can't get back to the WP dashboard. I get a http 500 error (see screenshot). The log doesn't really show anything. Is there some better way to diagnose what is going on? Here is the screen I get: 

![screenshot 2016-11-01 11 36 24](https://cloud.githubusercontent.com/assets/4553057/19895584/b48b9728-a027-11e6-966a-1374d9fb4c73.png)

**Comment by AramZS** [comment]
Any PHP errors?

**Comment by regan008** [comment]
Not that I see, but I can't access the dashboard. Is there another area I might be able to find those?
