### ISSUE TITLE
Nominate this - HTTP ERROR 500

### ISSUE THREAD

**Issue by jessicasteeleapcela** [PressForward/pressforward#871]
Using Chrome, when I use the "nominate this" tool - I receive this error:
The www.apcela.com page isn’t working

www.apcela.com is currently unable to handle this request.
HTTP ERROR 500

(Apcela.com is our website with the Press Forward  plugin installed).

Using Firefox, the nominate this tool just opens a blank page that never loads...

**Comment by AramZS** [comment]
Hi @jessicasteeleapcela 

Can you tell us what version of the plugin and WordPress you are using?

-Aram

**Comment by AramZS** [comment]
Dedicating significant improvements towards this in 4.2.x

**Comment by AramZS** [comment]
Further improvements to this in 4.3.

**Comment by AramZS** [comment]
Without further feedback we cannot progress in this issue. Closing it.
