### ISSUE TITLE
PressForward/Jetpack Conflict

### ISSUE THREAD

**Issue by slwestcott** [PressForward/pressforward#872]
From one of our partners: 

We have had a conflict btw PressForward (latest) and Jetpack (latest) for several months now. Since I’m getting back to our ds.lclark.edu/envx/ site in preparation for next semester, I looked into this a bit, and found this similar thread:

https://wordpress.org/support/topic/php-fatal-error-91/

This may be our problem as well: in brief, with PF activated (which we of course need) we cannot access Jetpack on that site to edit settings/modules/etc., which is a real problem on this very public PF site…we just get white screen of death (which we can back out of, but can’t access any Jetpack windows at all).

**Comment by regan008** [comment]
Confirmed, this is def an issue. Jetpack isn't installed by default so we never caught this. @AramZS What milestone do you want to address this in?

**Comment by slwestcott** [comment]
(sooner better than later - we need to be able to show Sloan that our partners are publishing)

**Comment by regan008** [comment]
If its ok with @AramZS, we can add it to 4.2 since we still have a bunch of outstanding bugs in that milestone. If not 4.2, it should go in 4.3 for sure but I'm worried the timeline on that might be a little late since they need it for next semester.

**Comment by slwestcott** [comment]
4.2 would be better, if it's possible, @AramZS.

**Comment by AramZS** [comment]
The patch for this is already in 4.2

**Comment by slwestcott** [comment]
From our partner: 

We have now installed PressForward v. 4.2.1, and our problems with Jetpack (4.4.2) remain on WP v4.6.1 in our multisite environment. I have tried disconnecting/reconnecting to Jetpack, etc., but we still receive a white screen upon attempting to connect to any Jetpack windows on our PressForward-enabled site. So, at least in our case, the problem persists.
