### ISSUE TITLE
Links posted on Facebook Redirect to the Original Source

### ISSUE THREAD

**Issue by eolson3** [PressForward/pressforward#873]
[From the WordPress forums](https://wordpress.org/support/topic/sharing-on-facebooktwitter/#post-8531335)

I haven't tested this out yet, but it wouldn't surprise me if this has slipped by us.  Haven't had a lot of users relying on Facebook posting.

**Comment by AramZS** [comment]
This is an intentional feature. I added a reply to the user thread.

**Comment by eolson3** [comment]
Ah, gotcha.  Thanks, Aram.
