### ISSUE TITLE
Post sanitation process does not remove emoticons that prevent db entry

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#874]
Emojis in article bodies or content via Nominate This.

**Comment by AramZS** [comment]
http://stackoverflow.com/questions/12807176/php-writing-a-simple-removeemoji-function

**Comment by AramZS** [comment]
Also check https://github.com/scottmac/opengraph/pull/39

**Comment by AramZS** [comment]
Just the body!

**Comment by jccatalano** [comment]
This appears to be working (for the emojis tested).
