### ISSUE TITLE
Entry Processes that don't stop

### ISSUE THREAD

**Issue by devinbalkind** [PressForward/pressforward#877]
Hi folks. 

Today my Nominate This bookmarklet feature stopped working. It generated the appropriate window and page URL, but the process seemed to stall. I closed the window and tried a few more times. Then my website went down with a 508 error and I looked into the CPanel to see if anything was wrong and I discovered that I was maxing out my "Entry Processes". I deactivated PressForward and then a few processes stopped. I started it up again and tried to use the bookmarklet again and the process counter went up by one. Then I tried again and it went up by one more. Is it possible these processes are starting and then not stopping - which is why I'm still on the verge of maxing out my Entry Processes? If so, you might want to create a feature that either allows the user to stop these processes or does so automatically. 

Happy to troubleshoot this more with you all.

Thanks!

**Comment by AramZS** [comment]
Thanks for the report. I'll look into this now.

**Comment by AramZS** [comment]
@devinbalkind Can you try making the following change and see if that fixes anything? https://github.com/PressForward/pressforward/pull/876/commits/85c33f325aa23c1b94dcb87b130641183e2f1c19

**Comment by devinbalkind** [comment]
Hmm my system calmed down and now I tried but couldn't induce Nominate This
to stall - and my Entry Processes are now at zero. I hope I didn't send you
on a wild goose chase...

Thank you for your help!!

**Comment by AramZS** [comment]
No worries, closing issue.
