### ISSUE TITLE
Redirecting despite settings

### ISSUE THREAD

**Issue by chrisaldrich** [PressForward/pressforward#878]
From Manual:
Seconds to redirect user to source: 0 means no redirect. PressForward makes use of canonical URLs. If you would like to redirect your readers automatically to the items aggregated by the feed reader and published to your site, this setting will determine how long to wait before redirecting. The default setting is 0 seconds. The redirect setting can be manually overridden in the Edit Post page by editing the forwarding status in the publish box.

ISSUE:
I've got the "seconds to redirect" set to 1 and regardless of whether I have the per post override set to either "Forward" or "Don't forward" all posts want to forward to the canonical URL. This is disconcerting particularly for the posts that I don't want to forward, and when this happens I'm seeing the page not only forward to itself (and therefore refresh), but it does it every few seconds continually which makes the page terrifically hard to try to read. Is it possible that it's not checking for the "forward/don't forward" toggle somehow?

**Comment by AramZS** [comment]
Thank you for this report, I'll look into it ASAP

**Comment by AramZS** [comment]
This will be resolved in the upcoming patch!

**Comment by chrisaldrich** [comment]
<a href="https://github.com/PressForward/pressforward/issues/878" class="u-in-reply-to"></a>I tested this quickly with 4.2.2 patch Release Candidate 1 and it does seemed to have fixed the issue. 
Thanks AramZS!
