### ISSUE TITLE
When avoiding duplication for creating a post via Nominate This, the image can still be duplicated. 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#879]

**Comment by jccatalano** [comment]
This appears to be working, but duplicate images are still being brought in if post urls don't match and are not aggregated into a single nomination. Will retest with more posts.

**Comment by AramZS** [comment]
That's expected, because the system doesn't see those as the same posts. If that is the only situation in which this isn't working the ticket should be a pass.
