### ISSUE TITLE
Link to see nomination/draft from Bookmarklet finish screen

### ISSUE THREAD

**Issue by chrisaldrich** [PressForward/pressforward#881]
UI suggestion

When using the bookmarklet to nominate/draft an article or source, it would be nice if the final page of the process in the modal would/could include direct links to open the interface to see the nomination, the draft, or the page for the RSS nominations respectively depending on the action taken.

In small(er) organizations this could help cut down on several seconds of workflow for those who might then begin work on the next step in the process immediately.

![nomination saved](https://cloud.githubusercontent.com/assets/5882943/21744322/0ebf70aa-d4c8-11e6-8dbc-0a01a8853f15.PNG)

**Comment by AramZS** [comment]
@chrisaldrich It is possible to set the system to automatically send Nominate This posts to Draft or Publish instead of to Nomination. Does that not fit your use case?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/PressForward/pressforward/issues/881#issuecomment-271106379" class="u-in-reply-to"></a>That could potentially work. Is there a filter or setting for that which I'm missing?

I also just tried another Draft version a bit ago and noticed that the exact interface has the two bits I thought it was missing. Apparently they don't appear for Nominate.

![draft](https://cloud.githubusercontent.com/assets/5882943/21745351/b25ef026-d4de-11e6-80ea-ee8eb84cde5e.PNG)

One of the things I notice that is missing between the Nominate and Draft functionalities is that the Draft option scrapes and properly places a featured image while the Nominate option doesn't do this and doesn't seem to add it when the piece is moved from the nomination queue into draft form. Is this a feature, flaw, or just an oversight? I can understand not saving the photo unless it goes to draft/publish as ones media folder gets filled up, but in some cases it would be nice to be able to scrape it easily when going from nomination to draft/publish.

**Comment by boonebgorges** [comment]
I've added a 'See all nominations' link, which goes to Dashboard > PressForward > Nominations. It works like the other links in this window, which simply open the link in the current window. This is not great behavior, but there's no real way around it aside from the unpleasant `target="_blank"`. It looks like the plugin tries to use `window.opener.location.assign()`, but security restrictions in modern browsers block this kind of action. People will have to work around this by using Ctrl+click or whatever technique they normally use for launching links in new tabs/windows.
