### ISSUE TITLE
If item_author is empty, first try the source title then a default value.

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#883]
```
				if ( empty( $value ) ) {
					$site = $this->get_post_pf_meta( $id, 'source_title' );
					if ( empty( $site ) ) {
						$value = 'Author on source';
					} else {
						$value = $site;
					}
				}
```
Removing this from the meta application process to streamline post saves.

**Comment by jccatalano** [comment]
Currently posts originating from feeds without an author are correctly using the website name for author; but,  posts originating from the bookmarklet without an author are using the user's name.
