### ISSUE TITLE
Archive Function Deleting Nominations

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#889]
There is a bug with the archive function on 4.2.x. It appears to be deleting nominations. I nominated a post via the bookmarklet and then archived it. After doing so the post vanished altogether (not even included in the archived posts).  I repeated this several times. I also sent a post to draft before archiving it; this resulted in the post existing in drafts but vanishing from nominated. This was tested on WP 4.3. Posts that were previously archived in November have not vanished.

**Comment by regan008** [comment]
I don't think its actually deleting the nomination in the database but I think the archived filter might have gotten tweaked at somepoint

**Comment by AramZS** [comment]
@regan008 may be right there. I'll look deeper into this because improving the delete functions is def something we have done in this patch. How old were the nominations?

**Comment by jccatalano** [comment]
The nominations that disappeared after archiving were from today. The nominations that were archived before and did not vanish were from November 6.

**Comment by jccatalano** [comment]
Retested without an issue.

**Comment by jccatalano** [comment]
There appears to be an issue with where an archived post is being sent. If I archive a post that has not been drafted, it will appear to have been deleted (not visible in the archived only or by toggling visibility); but, if I archive a post that has been drafted and the filter is set to hide archived posts, only the archive button vanishes and the post remains. If the filter is switched to show archived, a drafted post that has been archived will display the orange archived button.

**Comment by AramZS** [comment]
Moving the handling of this to #923 as this appears to be the same issue.
