### ISSUE TITLE
Delete in "All Contents" not working

### ISSUE THREAD

**Issue by chrisaldrich** [PressForward/pressforward#890]
On the "All Content" view [/wp-admin/admin.php?page=pf-menu], clicking the "x" icon (delete) removes the article from the view, but doesn't actually remove the post from the database.

Refreshing the page later brings back all the deleted items.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/PressForward/pressforward/issues/890" class="u-in-reply-to"></a>Cross referencing #889 which may be related, 

The items that won't delete are from feeds from mid-December (the feeds of which have since been deleted). They not only exist in the database, but their `post status` is still marked as `publish` after being "deleted".

It appears that for currently extant/live feeds that the delete button "works" properly for them in that `post status` has been changed to `removed_pf_feed_item` and they don't re-appear in the interface upon refresh. I am surprised that the entire post wasn't deleted from the database however--is this a bug or a feature? I might expect that archiving a post would hide it while still keeping it in the database, but not delete.

Currently using v4.2.1 on WP 4.7.1.

**Comment by AramZS** [comment]
Hi @chrisaldrich Do they get deleted later? The system is meant to store those items and then delete them in a subsequent event.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/PressForward/pressforward/issues/890#issuecomment-278056275" class="u-in-reply-to"></a>Checking again it appears that they're all still there, so it's not the case that even if they were set to flush via a later chron job that that event got triggered (or certainly not within the last two weeks).

I'm tempted to cut the storage time for feeds back to one month which will put them well within the time frame to try to get rid of them that way instead.

Out of curiosity as I don't see it documented, when the system flushes items longer than the "Months to retrieve and retain feed items", does it delete everything that hasn't been drafted, or does it keep items on which actions (star, comment, nominated/drafted) have been initiated upon?  I ask this because for those using PressForward as a self-hosted version of webapps like Pocket/InstaPaper (which both you and @mAAdhaTTah appear to), this would be a very useful feature without needing to take the additional steps of nominating/drafting the particular post.  Further, does marking as "read" save the date/time as it may be useful to have this data? (I looked around and didn't see any fields which would have indicated this as a potential feature.)

**Comment by boonebgorges** [comment]
I've reviewed the functionality here, and I've found the following:

- Items that are removed from All Content are correctly placed into 'removed_feed_item' status. https://github.com/PressForward/pressforward/blob/e66d85ccbf367e4734d6db960c36c1181d5d4309/Core/AJAX/ItemsAJAX.php#L159 https://github.com/PressForward/pressforward/blob/e66d85ccbf367e4734d6db960c36c1181d5d4309/includes/functions.php#L1296
- 'removed_feed_item' items do not appear in All Content https://github.com/PressForward/pressforward/blob/e66d85ccbf367e4734d6db960c36c1181d5d4309/Controllers/PF_Loops.php#L206
- At the time that items are removed from All Content, they're also added to the delete queue: https://github.com/PressForward/pressforward/blob/e66d85ccbf367e4734d6db960c36c1181d5d4309/Controllers/PF_Loops.php#L206
- The delete queue is processed hourly https://github.com/PressForward/pressforward/blob/e66d85ccbf367e4734d6db960c36c1181d5d4309/Core/Utility/Retrieval.php#L28, https://github.com/PressForward/pressforward/blob/e66d85ccbf367e4734d6db960c36c1181d5d4309/Core/Utility/Retrieval.php#L66. When it runs, items in the delete queue are properly cleared out of the database https://github.com/PressForward/pressforward/blob/e66d85ccbf367e4734d6db960c36c1181d5d4309/Core/Schema/Feed_Items.php#L599

As such, things seem to be working as designed.
