### ISSUE TITLE
Drafts from Contributor can't be edited. The user is not listed in Edit Post as the author 

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#891]
@AramZS This is the issue I was mentioning in our meeting today. @asmorton found it when she was setting up the Toynbee site.

When a user is a contributor and a post is drafted from nominated they cannot edit the post because they do not appear as the author. The author listed in wordpress is the item author. I can see all the posts drafted by other users, but I'm not able to edit any of them -- not even the ones I drafted myself. An admin, however, is able to edit any of the posts.

However, it does appear to be working for the bookmarklet. Is there some difference in the way the author is assigned in posts that come from all content vs the bookmarklet? Below is a screenshot of what I see in "edit posts" when a post from all content is nominated and then drafted from contributor level. 

![screenshot 2017-01-24 13 07 27](https://cloud.githubusercontent.com/assets/4553057/22260599/cdbf5d9a-e237-11e6-944b-7aed6c0d8d7d.png)

**Comment by AramZS** [comment]
Resolved with https://github.com/PressForward/pressforward/commit/cad5b84b856211dc545e3b97d04026c69bc5c229
