### ISSUE TITLE
"Source" title and URL repeated within post

### ISSUE THREAD

**Issue by chrisaldrich** [PressForward/pressforward#892]
Using the bookmarklet whether using "nomination" or "draft" the source of the saved story is put into the_content twice, once with a URL linked title and a second time immediately following, but with the plain text "Source:" prepended.

Is it possible that Mercury is adding one and the javascript in the bookmarklet is adding the other thereby causing the duplication?

**Comment by AramZS** [comment]
@chrisaldrich Yeah, possible. Can you link us to the site where this is happening?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/PressForward/pressforward/issues/892#issuecomment-278059270" class="u-in-reply-to"></a>Here's a "test" site I've been using to play around with PressForward and an example post on which it happens: http://read.boffosocko.com/2017/02/09/why-republicans-are-still-struggling-with-repealing-and-replacing-obamacare-the-atlantic/

Here's what I'm noticing as I go through the process: 
I used the bookmarklet to nominate the post (and in the modal window prior to clicking "nominate", the first attribution with link appears at the bottom of the page, presumably being included via Mercury--it's possible it's in the bookmarklet JS, but I'm not seeing anything that looks like that's the case with my shaky JS skills, but you may want to double check), then checking within the database, post_content shows just the single original attribution (again presumably from Mercury).
It's only after moving the post to "draft" that PressForward adds the additional "Source: URL wrapped title" attribution (with paragraph tags) to post_content which results in the duplication.

**Comment by AramZS** [comment]
This will be resolved in the 4.2.x

**Comment by jccatalano** [comment]
Tested  (all content -> draft, all content -> nominated -> draft, bookmarklet -> draft, bookmarklet -> nomination -> draft) from multiple sites and multiple feeds. The source appeared only once at the bottom of the post.
