### ISSUE TITLE
RSS feed triggering glitch 

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#895]
Here is the bothersome feed: https://www.technologyreview.com/stories.rss 
Here is a bothersome article: https://www.technologyreview.com/s/603699/quantum-computers-finally-go-head-to-head/

All posts from this feed are triggering the issue. Sometimes in nominated, sometimes in all content. 

If the article is nominated via the bookmarklet there is no issue.

Issue with html? Issue with the way the rss feed is written?

**Comment by regan008** [comment]
@aramzs on the partner site items from this feed wouldn't nominate at all. The progress bar would just hang and the item would never nominate. I've included a screenshot below of errors that appeared in the console on their site.

**Comment by jccatalano** [comment]
So it appears that posts from the troublesome feed only affect posts that appear below it in the nominate this menu. Newer nominations are not affected. The only exception appears to be other posts from the troublesome feed. They are appearing without any issues.

**Comment by AramZS** [comment]
Additional security now on the feed should resolve this

**Comment by regan008** [comment]
Looks good
