### ISSUE TITLE
Duplicated nominations via different methods. 

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#896]
![screen shot 2017-02-22 at 12 48 39 pm](https://cloud.githubusercontent.com/assets/18265200/23224876/f36dd1f2-f8fd-11e6-8dca-ff2737ef7079.png)
 If I nominate a post from all content, and then nominate that same post from the bookmarklet, the post will duplicate in nominated. Duplication does not occur if the same method is used to nominate the same post multiple times (two bookmarklet nominations = a post with 2 nominations).

**Comment by AramZS** [comment]
Added to test and patch plan for 4.3

**Comment by AramZS** [comment]
#921

**Comment by AramZS** [comment]
Should be resolved in stats nomination fix branch.

**Comment by AramZS** [comment]
#985 is the final step resolving this.
