### ISSUE TITLE
OPML link not working

### ISSUE THREAD

**Issue by chrisaldrich** [PressForward/pressforward#898]
## What I tried/expected:
From the page `/wp-admin/admin.php?page=pf-tools` under the `OPML Link` tab, the instructions indicate:
You can share your subscription list as an OPML file by linking people to http://example.com/?pf=opml.

## What happened:
Visiting the indicated link throws the following error:
`Warning: Creating default object from empty value in /htdocs/example/wp-content/plugins/pressforward-4.2.2/includes/opml/object.php on line 48    
1`

## Additional information:
I've got a handful of feeds, so I should expect something to appear. Is there a setting I'm missing somewhere? I know that there's a setting for the /feedforward RSS functionality/plugin, is there a similar one for OPML that I'm missing?

Running GitHub version 4.2.2, WordPress 4.7.2

**Comment by AramZS** [comment]
This is related to another issue, but we will queue for repair of both.

**Comment by jccatalano** [comment]
Tested and successfully generated the OPML file. Note: There were several fields that were not populated. 

<expansionState></expansionState>
					<linkPublicUrl></linkPublicUrl>
					<lastCursor>1</lastCursor>
