### ISSUE TITLE
Old posts with no value set for `pf_forward_to_origin` are automatically forwarded

### ISSUE THREAD

**Issue by chrisaldrich** [PressForward/pressforward#899]
This has probably been present for a while, but I just noticed after turning on forwarding posts to the canonical URL by setting a time >0 in the forward settings: all the old posts in my database (prior to having PressForward) auto forward as a default back to their own URLs. This means that every X seconds (as set in the setting) pages on my site automatically reload (or are redirected to themselves) and this makes the site relatively useless to attempt to read. (This seems to be a follow on error not noticed in https://github.com/PressForward/pressforward/issues/878, but which persists after the upgrade to 4.2.2 which resolved the problem for posts set to `no-forward`.)

Users adding PressForward on preexisting sites are going to have a tremendous shock if this is the default.

A better option is that all old posts (prior to installation) should default to no-forward (or at least not forward if there is no value set for `pf_forward_to_origin` in the database. PressForward should, in my mind, ideally default to no-forward in all new future posts with the possible exception of posts generated specifically by PressForward's nomination/draft workflow to default to `forward`/`no-forward` based on a possible new setting option in addition to the time setting.

It would be nice if the portion for null/non-existent values of `pf_forward_to_origin` was fixed before 4.2.2 rolled out into the WordPress repository if it hasn't been pushed already.

Running 4.2.2 on WP 4.7.2

Congratulations again to everyone, as always, on what I think is surely one of the most valuable plug-ins in the entire WordPress repository.

**Comment by AramZS** [comment]
Please test @regan008

**Comment by regan008** [comment]
Confirmed.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/PressForward/pressforward/issues/899" class="u-in-reply-to"></a>Did this get rolled up into the 4.3.0 pre release?
 https://github.com/PressForward/pressforward/releases/tag/4.3.0-pr

If it did, it doesn't seem to have fixed the root issue after I just installed and tested it. I'm still finding that older posts (pre-PressForward) which have no value set for `pf_forward_to_origin` are attempting to forward (back to themselves) when setting a time >0 in the forward settings. Those which have a value of `forward` do forward properly and those with a value of `no-forward` don't. The problem is for posts which existed prior to installing PressForward which have no value set at all.

**Comment by AramZS** [comment]
@ChrisAldrich it should be in there. Your browser may have cached the old instructions?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/PressForward/pressforward/issues/899#issuecomment-303901210" class="u-in-reply-to"></a>@AramZS I've double-checked and had cleared caches previously (which if not done wouldn't have forwarded as I'd had the forward value set to 0 before.)

I've cleared everything out and reinstalled the new .org version from the repository and am finding the same issue seems to persist. (Even testing in a new browser install.)

One thing I am noticing is that a lot of my older posts were actually imported into my self-hosted install from either other non-WordPress sources or an older WordPress.com account. When editing these which don't have any values set for `pf_forward_to_origin`, I notice that the UI default for PF is for them to `Forward` rather than the typical default of `Don't Forward` which I get for new posts.

I'm also noticing that these older posts have the original site's GUID set in wp_posts which means that they're being forwarded to those URLs (some of which don't exist anymore). I'll try to circle around and make a caveat note in the documentation of this for others who may experience it (and not know why).

Perhaps there's some other glitch in my database causing this? Since @regan008 has tested it and confirmed on your side (and the code looks correct to me), I'll throw in the towel. Since I've got to make some of these additional GUID changes (along with some others) in my database anyway, I'll just go in and add values for all these older posts so they're "forced" to work anyway.

Thanks, as always, for such continued work on a fantastic tool!

**Comment by AramZS** [comment]
That's very odd. Hmmm. It sounds like some import issues, but perhaps we can fix it anyway. Can you link us to one of the malfunctioning posts?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/PressForward/pressforward/issues/899" class="u-in-reply-to"></a>@AramZS Here are links to two (I've fixed the bulk of the rest), though that I can tell, these were native posts (prior to installing PressForward and which continually autoredirect to themselves, and thus never render, though one can view source for them) and not ones which were imported:
http://boffosocko.com/2015/08/30/obituary-wes-craven/
http://boffosocko.com/2015/11/18/why-math-jhu-mathematician-on-teaching-theory-and-the-value-of-math-in-a-modern-world-hub/

Other than having native WP GUID's these two are otherwise completely similar in database/metadata to the other posts which had been imported from other systems.

Don't kill yourself trying to troubleshoot these as I've already fixed the hundreds of others, but do drop me  a note if you don't find anything so I can manually tweak them so that they no longer auto-forward and actually resolve to something.
