### ISSUE TITLE
Bookmarklet chopping out NYTimes text

### ISSUE THREAD

**Issue by chrisaldrich** [PressForward/pressforward#900]
When nominating/drafting from NYTimes stories, typically the first several graphs are excised or not copied over into the post.

Based on some quick experiments it appears that the portion of stories that appears before `</div><!-- close story-body -->` (typically followed by some advertising before the story resumes) are the ones being left out for some reason. From the bookmarklet's point of view NYT articles seem to begin with the portion `<p id="story-continues-2" class="story-body-text story-content"` rather than the true start of the article.

Given that the Mercury browser plugin doesn't exhibit this behavior, I suspect it's something to do with the bookmarklet's JS?

This is occurring in 4.2.2 and earlier versions of the bookmarklet. I'm seeing it in Chrome as well as Firefox, so it doesn't seem to be browser dependent.

If pre-highlighting text in the browser, one does get the typical blockquoted portion of a Press This bookmarklet output.

**Comment by AramZS** [comment]
We'll add these divs to our Readability checks

**Comment by regan008** [comment]
I'm still seeing this be an issue. 

Here is an example: https://www.nytimes.com/2017/05/22/briefing/donald-trump-ford-motor-twin-peaks.html?&hp&action=click&pgtype=Homepage&clickSource=story-heading&module=second-column-region&region=top-news&WT.nav=top-news&_r=0

The bookmarklet grabs the first part of the story and then stops where the ad is (halfway through the second bullet point).

**Comment by AramZS** [comment]
Should be resolved by the CNN-related changes.

**Comment by regan008** [comment]
@AramZS I'm still seeing this issue occur.

**Comment by AramZS** [comment]
This is unavoidable until we move to a fully JS bookmarklet. Just the nature of those particular articles.

**Comment by boonebgorges** [comment]
This is no longer happening after switching to Readability.js in Nominate This. See #1097.
