### ISSUE TITLE
UX/UI Suggestion: Meta box in the admin UI with PressForward metadata and comments

### ISSUE THREAD

**Issue by chrisaldrich** [PressForward/pressforward#902]
I'd suggest that it would be worthwhile and convenient to have a meta box in the admin UI for editing the final draft that contained all of the pre-existing PressForward metadata.

Bits and pieces of it appear in other portions of the PressForward UI throughout the vetting (reading, nominating) process (typically hidden under the "info" button which pops up the details), but having portions of it while actually editing the draft of the post would be very handy/useful.  In particular, it would be nice to have access to the comments which are added to the particular piece in the earlier parts of the process.

![meta box information](https://cloud.githubusercontent.com/assets/5882943/23576560/ac78ea2c-005d-11e7-86f0-5ff5fe8a3252.PNG)

Comments in particular, would presumably have ideas, thoughts, and editorial leanings that could help the writer/editors shape the final piece or notes on/around it, but as it stands, one needs to dig back into the PressForward interface, typically with search, to re-uncover the particular data and notes relevant to the original piece.

Ideally making it relatively small so that it could fit into the sidebar may be the most beneficial. If you want to go all-in on such a feature, I've seen a fantastic meta box in the [Academic Blogger's Toolkit plugin](https://github.com/dsifford/academic-bloggers-toolkit) labeled "Reference List" which is pinnable and maintains its position at the top of the UI while the rest of the page scrolls.

**Comment by regan008** [comment]
Hi @chrisaldrich thanks for the suggestion. This sounds like a useful feature. We'll look into it some more and discuss it with our team. Thanks!

**Comment by boonebgorges** [comment]
As we move toward first-class support for the Block Editor (see #1124 and related tickets), I've been introducing some of these features into the block editor sidebar. Here's a screenshot of how it looks when you've promoted a nominated item to Draft:

![Screenshot_2024-01-03_13-32-54](https://github.com/PressForward/pressforward/assets/246627/64e6862c-b684-4ca1-af27-ea0da8e80a9e)

This will ship with the 5.6.0 release. It is relatively straightforward to add more static items (like feed name) to this section of the page. A full display of all comments is more complicated, and even more so if we need it to be interactive (ie, you can post as well as view comments). Let's handle that in future releases.

**Comment by boonebgorges** [comment]
The publication name and URL were added to this metabox for 5.7.0. We can use this space to add more content in the future, but for now I think we can consider this item complete.
