### ISSUE TITLE
Delete queue hiding breaks Media Library JS

### ISSUE THREAD

**Issue by boonebgorges** [PressForward/pressforward#903]
When an attachment ID is in the `pf_delete_queue`, `pf_exclude_queued_items_from_query_results()` removes that item from `WP_Query` results. This has the effect of breaking the media modal at wp-admin/upload.php and elsewhere. The details are sorta gory, but the high-level synopsis is this:

1. Removing queued posts at `posts_request` messes up pagination, by returning (for example) 39 posts where WP thinks it found 40.
2. In addition, the `unset()` method used in `pf_exclude_queued_items_from_query_results()` leaves a `posts` array that is non-consecutive.
3. When WP encodes the posts for JSON in its AJAX callback https://core.trac.wordpress.org/browser/tags/4.7.3/src/wp-admin/includes/ajax-actions.php?marks=2422-2423#L2425, the broken numerical indexes cause the return value to be cast to a JSON-encoded object, rather than an array.
4. `wp.media` expects to receive an array. When it gets an object, it gets confused about the number (and format) of returned results, so that pagination and other rendering breaks. This results in an infinite loop of AJAX queries.

Resetting the array indexes using `array_values()` fixes the infinite regress, but it breaks infinite scroll, because when `wp.media` sees 39 posts instead of the expected 40, it assumes that there's nothing more to query for.

Ideally, you'd avoid using the `posts_results` filter altogether, since it's always going to cause pagination problems. I see that you've tried to use `pre_get_posts` but it's commented out. If possible, it's probably best to get `pre_get_posts` to work. Barring that, I'd suggest making the `pf_exclude_queued_items_from_query_results()` filtering much more fine-grained: it should only run on the Trash page (the docs say that this is the main target anyway), only on PF-supported post types, etc. Worst case scenario, it may be worth removing the function altogether - it seems better to have occasional delete-queue inconsistencies than to have broken core interfaces.

Sorry for the brain dump - this is a complex one :)

**Comment by lmrhody** [comment]
Hey, Aram. Thanks for looking into this. We're trying to use the PF plugin for our GCDI site, and this came up. Happy to talk through what the user side looks like if you're interested.

**Comment by AramZS** [comment]
Set to resolve in next release.

**Comment by AramZS** [comment]
So I'm going to approach this by limiting the places this function executes, we tried using `pre_get_posts` earlier but testing showed us that the query performance impact that was having on post queries it touched was significant.

**Comment by regan008** [comment]
@AramZS I think this is fixed -- so tentatively closed but I'll followup later when I talk with Lisa about it.

**Comment by regan008** [comment]
Ok, I _think_ this is resolved.

**Comment by AramZS** [comment]
@boonebgorges Can you confirm this is resolved in last release? If not we'll reopen.

**Comment by boonebgorges** [comment]
@AramZS Thanks for looking into it! At a glance, the 4.4.x branch looks like it's working properly.
