### ISSUE TITLE
Error When Attempting to Refresh Feed in Tools/Debug and Refresh

### ISSUE THREAD

**Issue by mrjarbenne** [PressForward/pressforward#904]
When attempting to refresh the feed retrieval process, I'm seeing this error on the debug bar. The refresh seems to then stall on the progress bar. 

```
SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data
https://domain.com/wp-content/plugins/pressforward/assets/js/tools-imp.js line 13
```
This is on a Multisite WP 4.7.3 
PressForward Version 4.2.2

**Comment by AramZS** [comment]
Hi, can you please give us a list of the other plugins you are running?

**Comment by mrjarbenne** [comment]
Hi AramZS. It's sizable list, many of which aren't on the org repo. Do you have a list of plugins that conflict with Press Forward, or specific things I can test for? 

Active Plugins:
Add User Autocomplete (v1.2) by Boone Gorges
Akismet Anti-Spam (v3.3) by Automattic
Amazon Web Services (v1.0.2) by Delicious Brains
BP DoppelMe (v2.0) by r-a-y
BP MPO Activity Filter (v1.2) by Boone Gorges
BP Reactions (v1.0.1) by imath
BP Site Moderation (v) by r-a-y
Blog Copier (v1.0.7) by Modern Tribe, Inc.
Blue Network Plugins! (v1.1) by r-a-y
BuddyPress (v2.8.2) by The BuddyPress Community
BuddyPress Follow (v1.3-alpha) by Andy Peatling, r-a-y
BuddyPress Hide Widgets (v1.0.5) by Aaron Edwards (Incsub)
BuddyPress Moderation (v0.1.8-dev) by Francesco Laffi
BuddyPress Notify Post Author on Blog Comment (v1.0.4) by BuddyDev
BuddyPress Username Changer (v1.1) by Brajesh Singh
BuddyPress Usernames Only (v0.6) by r-a-y
Comments Control (v1.0.1.1) by WPMU DEV
Fix Image Orientation (v1.0.0) by Tim Carr
Google Analytics +  by WPMU DEV
Google Docs Shortcode (v0.5-bleeding) by r-a-y
Gravity Forms (v2.1.3) by rocketgenius
Gravity Forms Polls Add-On (v3.1) by Rocketgenius
Gravity Forms Quiz Add-On (v3.1) by Rocketgenius
Gravity Forms Signature Add-On (v3.3) by Rocketgenius
Gravity Forms Survey Add-On (v3.2) by Rocketgenius
HWDSB Custom MIME Types (v1.0) by Bob Fowler
Jetpack by WordPress.com (v4.7.1) by Automattic
MEXP oAuth Credentials (v1.0) by John Blackbourn
Media Explorer (v1.2) by Code For The People Ltd, Automattic
Media Explorer - Google Drive (v0.1) by r-a-y
Media Explorer - Vimeo (v0.1-alpha) by r-a-y
More Privacy Options (v4.6) by D. Sader
Multisite Plugin Manager (v3.1.5) by Aaron Edwards
My Sites Search (v2014.07.30) by Kailey Lampert
Plugin Activation Status (v1.0.1) by Curtiss Grymala
Rebranded Meta Widget (v1.0.3) by Aaron Edwards (Incsub)
Shortcake (Shortcode UI) (v0.7.1) by Fusion Engineering and community
Shortcake Bakery (v0.1.0) by fusionengineering, davisshaver, danielbachhuber
ThreeWP Broadcast (v37) by edward_plainview
ThreeWP Broadcast Control Pack (v36.2) by edward_plainview
Unfiltered MU (v1.3.1) by Automattic
Unlisted Posts (v0.1-beta) by r-a-y
User Switching (v1.0.9) by John Blackbourn
WP Dashboard Notes (v1.0.8.2) by Jeroen Sormani
WP Offload S3 (v1.3.1) by Delicious Brains
WordPress Importer (v0.6.3) by wordpressdotorg
WordPress.com Theme Updates (v1.0) by Automattic
Writing Helper (v1.0-rc1) by Nikolay Bachiyski, Daniel Bachhuber, Prasath Nadarajah, Automattic
oEmbed in Comments (v1.1.2) by Evan Solomon

**Comment by jccatalano** [comment]
Tested the issue using the plugins available in the WP directory. This issue remains unresolved.

**Comment by mrjarbenne** [comment]
Are you saying you are able to reproduce the error with the plugins in the repo? I had neglected to further test but would love to be able to use Press Forward.

 I can try to do some further testing to narrow down the offending plugin(s).

**Comment by regan008** [comment]
@mrjarbenne We've been testing it internally today but we actually think this may be an issue that is unrelated to a plugin. We're working on it and will get back to you.

**Comment by regan008** [comment]
This appears to be resolved now.
