### ISSUE TITLE
Nominate This Error

### ISSUE THREAD

**Issue by slwestcott** [PressForward/pressforward#905]
From a partner: 

When I clicked the "nominate this" button, I got this:

Fatal error: Uncaught Error: Call to undefined function mb_detect_encoding() in /var/www/html/wordpress/wp-content/plugins/pressforward/Libraries/PFSimpleHtmlDom.php:958 Stack trace: #0 /var/www/html/wordpress/wp-content/plugins/pressforward/Libraries/PFSimpleHtmlDom.php(819): pf_simple_html_dom->parse_charset() #1 /var/www/html/wordpress/wp-content/plugins/pressforward/Libraries/PFSimpleHtmlDom.php(85): pf_simple_html_dom->load('\r\n<!DOCTYPE htm...', true, true) #2 /var/www/html/wordpress/wp-content/plugins/pressforward/Controllers/Metas.php(962): pf_file_get_html('http://www.core...') #3 /var/www/html/wordpress/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php(587): PressForward\Controllers\Metas->get_author_from_url('http://www.core...') #4 {main} thrown in /var/www/html/wordpress/wp-content/plugins/pressforward/Libraries/PFSimpleHtmlDom.php on line 958

Apparently the same error appears whenever they attempt to use the bookmarklet.

**Comment by regan008** [comment]
@slwestcott It might be useful to know if this is happening on one specific article (and if so, what the url is) or on everything they try to nominate?

**Comment by AramZS** [comment]
Hi @slwestcott - looks like mbstring is not installed for that user. That's a PHP library that should be installed for people who want to take full advantage of PF's features, but we'll create a check for it and bypass that use when the lib isn't available.
