### ISSUE TITLE
Nominate error message

### ISSUE THREAD

**Issue by kutlan** [PressForward/pressforward#906]
When I want to nominate a page I get the following error message;

"ERROR 403 - FORBIDDEN"

What is this? How to fix?

**Comment by regan008** [comment]
@AramZS suggestions on how to test this?

**Comment by AramZS** [comment]
Try on reclaim hosting

**Comment by regan008** [comment]
Ah ok -- @jccatalano you have a site spun up on your server right?

**Comment by jccatalano** [comment]
I was unable to trigger the 403 error on Reclaim.
