### ISSUE TITLE
Can't access tabs in tools WP 4.6 and earlier

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#908]
While testing for the OPML problem in issue 898, I discovered that the tabs in tools are not working. It appears that the functionality of the OPML is still working (checked by adding ?pf=opml). This issue is only occurring on WP versions 4.6 and earlier.

**Comment by regan008** [comment]
@jccatalano Retest

**Comment by jccatalano** [comment]
Working properly.
