### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by AleVenezia** [PressForward/pressforward#909]
when i use "nominate this", it gives me 403 error

**Comment by regan008** [comment]
Hi @AleVenezia -- can you provide some more details for us so we can attempt to diagnose your issue? What version of WordPress and PressForward are you using? Have you tried reinstalling the bookmarklet? Does this happen on every post you try to nominate or just certain posts? If you could include urls to both the sites that cause the 404 error as well as to your own site that would be useful.

**Comment by AleVenezia** [comment]
Hi Amanda, plugin version is 4.2.2. and wordpress is the last version.
You can see the problem is on the attachment.
I go in Hostgator, change the permission on the file .htaccess (777), but
nothing happen and i have the same problem :-(


Ale

2017-04-24 16:45 GMT+02:00 Amanda Regan <notifications@github.com>:

**Comment by regan008** [comment]
@AleVenezia Hmm, that attachment doesn't seem to be coming through. Can you try uploading the image again?

**Comment by AleVenezia** [comment]
[image: Immagine incorporata 1]
ok, this time i prefer to insert the image..
i hope it will help you to solve the problem


Ale

2017-04-24 23:27 GMT+02:00 Amanda Regan <notifications@github.com>:

**Comment by bomeara** [comment]
I am also on hostgator and have the same issue. 

PHP 5.4, PressForward 4.2.2, Wordpress 4.7.4. I'm logged into my Wordpress account, go to a new tab, click the Nominate This bookmarklet, and have a 403 Forbidden error. This happens on both Safari and Chrome on Mac. 

Note this is the first time I've installed PressForward, so it could be something dumb on my end. Given @AleVenezia has the same host, though, I wonder if it's a hostgator setting that's a problem.

**Comment by regan008** [comment]
@bomeara @AleVenezia Are both of your sites publicly accessible? You don't have a password or anything on the site do you?

**Comment by regan008** [comment]
@AleVenezia the screenshot has still not come through, could you email it to info@pressforward.org for us?

**Comment by regan008** [comment]
@jccatalano Same as the other, test on reclaim. We don't have a host gator site to test on but it should be roughly the same circumstances.

**Comment by jccatalano** [comment]
I was unable to trigger the 403 error using Reclaim.
