### ISSUE TITLE
ERROR: Are you sure you want to do this?

### ISSUE THREAD

**Issue by jeau** [PressForward/pressforward#910]
I plan to use PressForward. I'm trying to test it on a recent wordpress installation (wp v. 4.7.4) but I noticed a conflict with the plugin Maintenance (v. 3.4.1 by fruitfulcode). When I want to change the Maintenance settings, the "Are you sure you want to do this?" message appears and the new settings are not validated. If I disable PF everything works fine.

This bug has already been reported on the FP forum on WP support:
[https://wordpress.org/support/topic/error-are-you-sure-you-want-to-do-this-5/](https://wordpress.org/support/topic/error-are-you-sure-you-want-to-do-this-5/)

**Comment by AramZS** [comment]
Hi @jeau Not sure what the issue is here but I will look into it ASAP.

**Comment by regan008** [comment]
This is resolved.
