### ISSUE TITLE
Plugin Conflict Errors

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#911]
From the wp support forum: 

> When using the following plugins – Quotes Collection and Ultimate Multi Design Video Carousel – I have been getting errors. The errors are resolved when I DISABLE the PRESSFORWARD plugin.
When trying to use Quote Collection I get an “Are you sure you want to do this” error, and when using the Video Carousel plugin I get an error that I cannot access this page. Again, both errors are resolved by DISABLING PRESSFORWARD.

> Any ideas what about Pressforward is causing these problems?

**Comment by AramZS** [comment]
Should be resolved by #910 Please check.

**Comment by regan008** [comment]
Resolved.
