### ISSUE TITLE
On Update from 4.2 to 4.3 old bookmarklet displays notices

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#917]
The page still gets submitted but the following notices appear
On the edit post page of the bookmarklet: 
``` Notice: Undefined index: pf-nominate-this in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/pressforward/includes/nomthis/nominate-this-core.php on line 529 ```

After the post has been nominated: 

``` 
Notice: Undefined variable: post_thumbnail_url in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/pressforward/Core/Utility/Forward_Tools.php on line 336
Notice: Undefined index: pf-nominate-this in /srv/www/wordpress-develop/public_html/src/wp-content/plugins/pressforward/includes/nomthis/nominate-this-core.php on line 529 
```

**Comment by AramZS** [comment]
2nd should now be resolved. Looking at first.

**Comment by regan008** [comment]
Resolved.
