### ISSUE TITLE
Reclaim Bookmarklet Readability

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#919]
So I am not getting the 403 error of issue #906 but there are significant readability issues using the plugin from reclaim. 
One page (http://d9sports.com/brookville-girls-claim-d9-class-2a-track-field-title/) captured no information and gave this message:

Warning: DOMElement::setAttribute(): ID readability-content already defined in /home/joshuaca/testsite.joshuacatalano.org/blog/wp-content/plugins/pressforward-4.3.x/Libraries/FiveFiltersReadability/Readability.php on line 707

Warning: DOMElement::setAttribute(): ID already defined in /home/joshuaca/testsite.joshuacatalano.org/blog/wp-content/plugins/pressforward-4.3.x/Libraries/FiveFiltersReadability/Readability.php on line 759 

A post from CNN captured a mess in terms of readability (http://www.cnn.com/2017/05/22/politics/trump-israel-russia-intelligence/index.html).

**Comment by AramZS** [comment]
Should be resolved now

**Comment by jccatalano** [comment]
Readability is working but still triggering error messages.

**Comment by AramZS** [comment]
It should now only do so when in WP_DEBUG mode on the site.

**Comment by regan008** [comment]
@jccatalano Retest when you get in this morning!

**Comment by jccatalano** [comment]
Functioning as described.
