### ISSUE TITLE
Error in Bookmarklet 

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#920]
```
Notice: Uninitialized string offset: 0 in /srv/www/wordpress-default/public_html/wp-includes/Requests/Cookie.php on line 292
```
Appears above the nominate/send to draft items on this washington post article: 
https://www.washingtonpost.com/world/national-security/trump-asked-intelligence-chiefs-to-push-back-against-fbi-collusion-probe-after-comey-revealed-its-existence/2017/05/22/394933bc-3f10-11e7-9869-bac8b446820a_story.html?hpid=hp_hp-top-table-main_trumprussia-629pm%3Ahomepage%2Fstory&utm_term=.04d720bd5ea4

**Comment by AramZS** [comment]
This should no longer occur unless the site specified WP_DEBUG on.

**Comment by AramZS** [comment]
It's something odd and not really fixable about parsing the page so we just won't present that error to the users.

**Comment by regan008** [comment]
Ok, confirmed then. When I turn debug off the error disappears.
