### ISSUE TITLE
Nomination of the same post from all content and bookmarklet -- by the same user -- causes duplication in Nominated

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#921]
I found that the same user can duplicate a post. I nominated one item from all content and then, under the same user, nominated the same item from the bookmarklet. The post showed up in nominated two separate times. I then logged in as a contributor and nominated the same item with the bookmarklet. The nomination count increased on the first item nominated from all content.

**Comment by jccatalano** [comment]
This issue also throws off the nominations of a post.

**Comment by jccatalano** [comment]
This issue also makes it appear as if a post nominated from the bookmarklet is not nominated in all content because it is the duplicated post that is nominated not the all content post.

**Comment by regan008** [comment]
Since this appears to be related to all of our other nominating issues I'm going to move this to 5.0.

**Comment by AramZS** [comment]
Should be resolved in the stats nomination fix branch. Please test.

**Comment by regan008** [comment]
Confirmed
