### ISSUE TITLE
Facebook link appearing as author in bookmarklet

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#922]
On this Washington post article I'm seeing a facebook link appear in the author field: 
![screenshot 2017-05-23 10 09 42](https://cloud.githubusercontent.com/assets/4553057/26358270/000286fe-3fa0-11e7-9ed4-b728785ba7dd.png)

Possibly related to #920

**Comment by AramZS** [comment]
This is unavoidable. WaPo's HTML is mis-configured, not us.
