### ISSUE TITLE
Archived posts are not appearing in Nominated

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#923]
When a nominated post is archived, filter by archived does not return any results.

**Comment by regan008** [comment]
Related to #889

**Comment by yoannspace** [comment]
Should be modified to "removed_feed_item" instead of "draft"?
https://github.com/PressForward/pressforward/blob/4.4.x/includes/functions.php#L967

**Comment by AramZS** [comment]
@yoannspace Thank you for your contribution. We're engaging in testing it now, but it looks like this is definitely a bug and you've done a great job spotting the issue and fixing it!

**Comment by regan008** [comment]
@jccatalano I think this is ready to test

**Comment by jccatalano** [comment]
I am still experiencing a problem with issue #923. Archived only is still not displaying archived posts. The toggle visibility of archived is working though.

**Comment by AramZS** [comment]
Please try again with latest

**Comment by jccatalano** [comment]
I am still having an issue with this. Archived posts from February are showing up in archived only. But the posts that I brought in today and archived do not appear.

**Comment by yoannspace** [comment]
Would that be possible that's because it is in an other page? But you can't go to other pages (see https://github.com/PressForward/pressforward/pull/945)?
Some thing must have changed lately, but I experienced the same problem with new archived content, they would show up at the end (last page)... I modified this:
ORDER BY {$wpdb->postmeta}.meta_value DESC, {$wpdb->posts}.post_date DESC
on https://github.com/PressForward/pressforward/blob/4.4.x/includes/functions.php#L972 so that the archive objects appear with newest at top.
But that also means, that the waiting pull request be accepted (to have pagination in archived items).

**Comment by AramZS** [comment]
@yoannspace Thanks for the PR, we'll review it. 

@regan008 Can you please test this change on the branch `4.4.x-stats-nomination-add-archives-pagination` to see if it resolves this issue?

**Comment by jccatalano** [comment]
I am still having problems with this issue.
User 1: Nominates an item from all content (the item appears in nominated)
User 1: Archives the item from Nominated (the item vanishes from Nominated)
User 1: Filters by Archive Only (the archived item is not there)
User 1: Goes to All Content (the item is no longer in all content)

**Comment by AramZS** [comment]
@jccatalano Does the page refresh when you use the filter?

**Comment by yoannspace** [comment]
SQL_CALC_FOUND_ROWS disappeared on:
https://github.com/PressForward/pressforward/blob/4.4.x-stats-nomination-add-archives-pagination/includes/functions.php#L965

ORDER BY {$wpdb->postmeta}.meta_value DESC, {$wpdb->posts}.post_date DESC was not added on:
https://github.com/PressForward/pressforward/blob/4.4.x-stats-nomination-add-archives-pagination/includes/functions.php#L973

$page += 1; disappeared on:
https://github.com/PressForward/pressforward/blob/4.4.x-stats-nomination-add-archives-pagination/Core/Admin/Nominated.php#L290


@AramZS There might be reasons for those, and I would be happy to hear them and I will try to change it to something you would prefer.

**Comment by jccatalano** [comment]
Yes it refreshes.

**Comment by jccatalano** [comment]
From the console:

![screen shot 2017-12-05 at 11 12 20 am](https://user-images.githubusercontent.com/18265200/33617262-4be84a2a-d9ad-11e7-97dd-fb980d6a5a70.png)

**Comment by AramZS** [comment]
@yoannspace The `page += 1` issue had to do with a bug in how the infinite scroll JS works. In my testing, removing it seems to cause issues with that feature. I neglected to add the ordering at 973 and I was testing on the found rows issue, but it does look needed, so I am adding it back in.

**Comment by yoannspace** [comment]
I checked your last commit. It works for me, I can see my last archived items. But when I get on page 2, then the pagination is messed up. That's where the '$page +=1;' was helping out.

**Comment by AramZS** [comment]
@yoannspace What version of WordPress and Browser are you using? 

I'll test this now.

**Comment by AramZS** [comment]
@yoannspace I'm going to put it back in and we'll test it. I tried solving the issue by changing the numbers elsewhere and it didn't work, but changing it here doesn't seem to cause any issues.

**Comment by jccatalano** [comment]
It appears that this issue is resolved by clearing the cache.

**Comment by yoannspace** [comment]
@AramZS Definitely too late, but I use Firefox 57.0.1 / Wordpress 4.8.4

Thanks all!
