### ISSUE TITLE
Create a tracking opt in feature that writes to a google sheet (or something) upon plugin update 

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#927]

**Comment by jccatalano** [comment]
Does not work with older versions of Firefox (2.2.4 - version 38)

**Comment by jccatalano** [comment]
Users can opt in multiple times which leads to multiple timestamps for the same url on the spreadsheet.

**Comment by AramZS** [comment]
@jccatalano This is the nature of the DEBUG mode, if WP_DEBUG is turned off, it will not be possible.

**Comment by regan008** [comment]
@jccatalano let’s test this by turning wp_debug off in the wp-config.php file. You’ll Need to open the file in a txt editor or in vim to edit the option. I’m happy to walk you through it in the morning

**Comment by regan008** [comment]
We're good to go here.
