### ISSUE TITLE
Bookmarklet Upgrade Language

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#928]
Instructions should appear on the pressforward tools page, in the old bookmarklet, and in the first tile in All Content. 

On Old Bookmarklet: 
**Upgrade the Nominate This Bookmarklet**: PressForward has improved the Nominate This Bookmarklet to make it faster and more efficient. To use the new bookmarklet, first delete your current bookmarklet from your bookmark bar and reinstall the bookmarklet from the tools tab in PressForward. For help, see the [Bookmarklet documentation.](https://github.com/PressForward/pressforward/wiki/User-Manual#installing-and-using-the-nominate-this-bookmarklet)

On All Content Page: 
**Upgrade the Nominate This Bookmarklet**: PressForward has improved the Nominate This Bookmarklet to make it faster and more efficient. To use the new bookmarklet, first delete your current bookmarklet from your bookmark bar and reinstall the bookmarklet by dragging the button below to your bookmark bar. For help, see the [Bookmarklet documentation.](https://github.com/PressForward/pressforward/wiki/User-Manual#installing-and-using-the-nominate-this-bookmarklet)

On Tools Page: 
**Upgrade the Nominate This Bookmarklet**: PressForward has improved the Nominate This Bookmarklet to make it faster and more efficient. To use the new bookmarklet, first delete your current bookmarklet from your bookmark bar and reinstall the bookmarklet by dragging the button below to your bookmark bar. For help, see the [Bookmarklet documentation.](https://github.com/PressForward/pressforward/wiki/User-Manual#installing-and-using-the-nominate-this-bookmarklet)

**Comment by boonebgorges** [comment]
Enough time has passed that I don't think these changes are necessary anymore.

Moreover, the bookmarklet has been rewritten in such a way that most future improvements come from the block editor itself, rather than the bookmarklet script. So updates of this sort will become rare.
