### ISSUE TITLE
Posts from pressforward always show "aggregation" as author name.

### ISSUE THREAD

**Issue by astrung** [PressForward/pressforward#932]
When i nominated posts from pressforward and push it to draft posts, it show `aggregation` on author name, but link to author post is still corrent. How can i fix it ?. I tried to set posts to other authors, but it always show same name : `aggregation` . How can i fix it ?

**Comment by AramZS** [comment]
Feed versions of authors should not trump Bookmarklet authors.

**Comment by lcrossley** [comment]
When nominating a post through the bookmarklet that is also in All Content, editing the author field in the bookmarklet is not overriding the feed version's author (for feeds where the default author field usually kicks in, it's not overriding the default author either). It is saving any changes to the title, the body, and the tags, though.
