### ISSUE TITLE
Stats tab permissions selection needed 

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#933]

**Comment by AramZS** [comment]
Also place the alert on to the plugins page when the update happens. 
When version number changes emit a settings alert?

**Comment by boonebgorges** [comment]
This is now built:

![Screenshot_2024-03-04_11-01-19](https://github.com/PressForward/pressforward/assets/246627/c984d4ed-9695-4acf-bfc6-b95c853a0bce)

I'm not quite sure what's meant by the "alert" comment above, but I figure this is not directly related to the request in the current issue.

**Comment by boonebgorges** [comment]
Also, a note that I used this ticket as an excuse to do some miscellaneous cleanup for the Stats tab, as well as a bugfix a6cf7e7.
