### ISSUE TITLE
UI/UX: Publish default to Don't Forward unless PressForward functionality

### ISSUE THREAD

**Issue by chrisaldrich** [PressForward/pressforward#936]
## What happened
With PressForward installed/activated, the Site Options setting for "Seconds to redirect user to source. (0 means no redirect)" set to 1 or greater, and creating a new post (by almost any means including manually, API, micropub, and I suspect sources like the forthcoming Gutenberg interface) the drop down menu item in the Publish meta box to "Forward/Don't Forward" to item's original URL automatically defaults to "Forward".

## What I Expected
I would expect the Forward/Don't Forward setting to default to Forward _only_ when an item is created via the bookmarklet, through items entering the process via the RSS feeds, or from other PressForward specific functionality.  All other posts should default to Don't Forward unless manually switched in the Meta box.

For posts created either manually or other automatic means from other sources (API, micropub, etc.) they default to Forward meaning that their URLs never resolve to view the page as they continually forward back to themselves in a never ending loop.

## Additional notes
With the Seconds to redirect set to 0, all new posts seem to be set to the default "Don't Forward" as one would expect.

**Comment by boonebgorges** [comment]
I'll take a look at this in an upcoming release.

At the very least, forwarding should be disabled if no source URL is available, to avoid the kind of loop you've described.

**Comment by boonebgorges** [comment]
When items are created via the Block Editor, the Forward to Source interface doesn't appear in circumstances where a post is manually created. So the behavior can only be reproduced when creating via the Classic Editor.

I've put two fixes in place to address it:

1. When creating a post via post-new.php and the Classic Editor, always default to "Don't Forward"
2. Before forwarding any item to the source URL, double-check that the source URL is not the same as the PF permalink of the very post. This latter fix should fix redirect loops.
