### ISSUE TITLE
Notification for New Nominations

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#937]
Per our discussion last Tuesday, it would be nice to have the number of new nominations since last login (user specific) appear on the top bar of the wp dashboard.

**Comment by regan008** [comment]
@AramZS We can drop this to 5.1.x if you'd like.

**Comment by boonebgorges** [comment]
I rolled this into #1181:

![Screenshot_2024-07-25_11-43-35](https://github.com/user-attachments/assets/0b1c5c1a-03b8-43e1-bdb9-10b3d79c237c)
