### ISSUE TITLE
Tracking window Examples

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#938]
@AramZS Here are some plugins that do the type of tracking window I was imagining when we spoke last week: 
* NinjaForms 
* WPUser Front End

<img width="916" alt="screen shot 2017-09-19 at 1 43 20 pm" src="https://user-images.githubusercontent.com/4553057/30606938-5b5ed9ea-9d41-11e7-9d35-f098789573ff.png">
<img width="911" alt="screen shot 2017-09-19 at 1 46 52 pm" src="https://user-images.githubusercontent.com/4553057/30606941-5cc9e888-9d41-11e7-945e-98bd7bd611c5.png">

**Comment by regan008** [comment]
@AramZS I just realized I put a couple issues in 5.0.x but it seems like you are working in 4.4.x. Were these examples helpful at all?

**Comment by AramZS** [comment]
These are! Right now I've not got the UX working, but I wanted to setup the process to test the system in a more basic configuration. Adding these design elements will be the next step.

**Comment by AramZS** [comment]
Dismissing the alert should actually disappear the alert

**Comment by AramZS** [comment]
In 5.0 lets only present the basic tracking option.

**Comment by AramZS** [comment]
No checkboxes needed.

**Comment by jccatalano** [comment]
Opt-in language: "Opt-in to allow us to collect non-sensitive diagnostic information for plugin improvement"

**Comment by jccatalano** [comment]
Should the opt-in language also appear next to the allow basic tracking site option?

**Comment by AramZS** [comment]
I don't think it makes sense to have the thank you alert triggered, but we should add the opt-in language to the Preferences page.

**Comment by jccatalano** [comment]
See #955
