### ISSUE TITLE
Allow a default author to be set per-feed.

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#939]

**Comment by AramZS** [comment]
Provide hooks for plugins to build out other default metadata for things on-feed

**Comment by AramZS** [comment]
And allow for other feed level defaults.

**Comment by AramZS** [comment]
(Use meta structure)

**Comment by lcrossley** [comment]
Is this expected to work only for new items that appear in All Content after the default author has been set or to also apply to items that were in All Content before the default author was set?

**Comment by AramZS** [comment]
In All Content, only if the feed does not provide a author.
