### ISSUE TITLE
Language on Preferences Page

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#948]
I think we should update the language for the new diagnostics option on our preferences page too. 

Right now we have:  No/Yes "Allow Basic tracking" and then below that "Opt-in to allow us to collect non-sensitive diagnostic information for plugin improvement".

Can we lose the first part and have just No/Yes "Opt-in to allow us to collect non-sensitive diagnostic information for plugin improvement."

**Comment by jccatalano** [comment]
There is a related discussion in the comments for #938
