### ISSUE TITLE
Un-Nominate Removing other users nominations + Nomination Count Off

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#950]
If two users nominate the same post, the post appears in nominations with the correct count of two. However, if one user un-nominates that post, it disappears altogether from nominated. If that same user re-nominates the post, it reappears in nominated but only has a nomination count of 1.

**Comment by jccatalano** [comment]
If a user un-nominates a post, it is now correctly removing one nomination. However, once a post is sent to draft the nomination count is fixed. Therefore if a post is nominated 3 times and then sent to draft, users can un-nominate the post but it will still display a count of 3.

**Comment by AramZS** [comment]
Should be resolved in latest push to stats nomination fix.

**Comment by jccatalano** [comment]
Tested and working properly. However, un-nominating an item after it has been sent to draft does not reduce the nomination count. This is likely related to #960.
