### ISSUE TITLE
Query Arguments Not Working

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#951]
This is the syntax I'm using to try and query the overview endpoint: 
http://local.wordpress.test/index.php?rest_route=/pf/v1/stats/overview?filter[before_month]=10

Is that right?

**Comment by AramZS** [comment]
Should be good to go, it isn't passed the same way as other filters, instead passed like a traditional param `local.wordpress.test/wp-json/pf/v1/stats/overview/?before_year=2017`

**Comment by regan008** [comment]
@jccatalano Can you test this one? My local install was reset and I don't have anything prior to 2018.

**Comment by jccatalano** [comment]
I don't think this is working as intended. I used this filter in postman local.wordpress.test/wp-json/pf/v1/stats/overview/?before_year=2018 on an install with 16 published posts, 60 nominations, and 386 items. It resulted in counts of 0 for all three. This occurred regardless of the year. Are we sure that the param structure correct?

**Comment by AramZS** [comment]
@jccatalano That would be posts that are added to the system before the year 2018, so `<=2017` as their publishing year. Is that the expectation?

**Comment by jccatalano** [comment]
Correct. I have posts from 2017 and 2018 but cannot filter them. Tried before_year 2018 and before_year 2019. Both result in all 0 counts

**Comment by jccatalano** [comment]
However doing after_year 2017 correctly filtered the 1 published post.

**Comment by AramZS** [comment]
Ok, it should be working now.

**Comment by jccatalano** [comment]
Correct. before_year is working.  What other params should be working? year= does not

**Comment by AramZS** [comment]
Year is not specced to work.

The spec is described at `[site]/wp-json/pf/v1/`

```
                        "after_year": {
                            "required": false,
                            "description": "Limit query by year, use XXXX year notation."
                        },
                        "after_month": {
                            "required": false,
                            "description": "Limit query by month, use number of month."
                        },
                        "after_day": {
                            "required": false,
                            "description": "Limit query by day, use number of day."
                        },
                        "before_year": {
                            "required": false,
                            "description": "Limit query by year, use XXXX year notation."
                        },
                        "before_month": {
                            "required": false,
                            "description": "Limit query by month, use number of month."
                        },
                        "before_day": {
                            "required": false,
                            "description": "Limit query by month, use number of month."
                        }
```

**Comment by jccatalano** [comment]
Ok. So the after_month will automatically assume the current year? 

Would it be possible to know how many posts were published in November 2017? 

We will need to make some sort of documentation for how this works.

**Comment by AramZS** [comment]
If year is not passed the current year is assumed. But you can combine multiple properties `?before_year=2018&before_month=2` will give you everything before February 2018.

This can also be handled to be a limited set, so:

`?before_year=2018&before_month=2&after_year=2016` will give you all stats for the dates between Jan 01 2017-Jan 31 2018.

**Comment by jccatalano** [comment]
Ok. I can write up a cheat sheet for that to add to our documentation.
