### ISSUE TITLE
Remove Gender Api

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#952]
We need to remove the Gender API from the plugin.

**Comment by AramZS** [comment]
@regan008 I was thinking about this. As someone who has used it for the reasons described in the Medium article I wrote, I think it is useful with context. What about taking it and putting enabling it into an option that contextualizes what it is, what it provides and its limitations

**Comment by slwestcott** [comment]
Right now, the potential negatives outweigh the potential usefulness of this for us, even as an option, so we'd like remove it entirely.

**Comment by regan008** [comment]
We also need to remove the language from the stats UI on the tools page. 

https://www.dropbox.com/s/kh9th6gkiepgeqg/Screenshot%202017-11-28%2011.35.21.png?dl=0
