### ISSUE TITLE
Opt-in Windows not appearing in plugins WP 4.7 and back

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#955]
The boxes containing the opt-in language do not appear on WP 4.7 and back. Likewise, the PF icon in the bar at the top of the page is only visible within PressForward on 4.7 and back.

**Comment by AramZS** [comment]
I'm having trouble pinning this down. @jccatalano can you check the javascript console for errors?

**Comment by AramZS** [comment]
For me, the top bar is showing everywhere but plugins, and on the plugins page it isn't showing but neither is the alert. Everywhere else it seems to be showing as expected in <=4.7 versions. Can you double check?

**Comment by jccatalano** [comment]
As you noted, the top bar is showing everywhere except the plugins page. Nothing is occurring on the plugin page.


From the console:


```
jquery-migrate.js?ver=1.4.1:45 JQMIGRATE: jQuery.fn.load() is deprecated
migrateWarn @ jquery-migrate.js?ver=1.4.1:45
jQuery.fn.(anonymous function) @ jquery-migrate.js?ver=1.4.1:560
(anonymous) @ alert-handler.js?ver=4.7.8:1
jquery-migrate.js?ver=1.4.1:47 console.trace
migrateWarn @ jquery-migrate.js?ver=1.4.1:47
jQuery.fn.(anonymous function) @ jquery-migrate.js?ver=1.4.1:560
(anonymous) @ alert-handler.js?ver=4.7.8:1
plugins.php:405 Attaching prompt
plugins.php:259 PF Metrics Request
```

**Comment by AramZS** [comment]
Ok, please recheck on the stat-interface endpoint

**Comment by jccatalano** [comment]
It is now working on 4.7 on the stats-interface branch. I will check older version in the morning.

**Comment by jccatalano** [comment]
Tested with WP 4.0 and 4.8 and it is working there too.

**Comment by regan008** [comment]
Fantastic, lets close this.
