### ISSUE TITLE
Nominators array not displaying correct IDs

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#956]
On the stats branch, I nominated the same post using two different users and the following appeared on the stats/pf_posted endpoint.
```
"nominators": {
      "0": "",
      "": [
        "" 
```

Posts that were nominated while still on the 4.4.x branch provided the following:

```
"nominators": [
      1
    ]
```
and a different post:
```
"nominators": [
      2
    ]
```
both of those posts had multiple nominators as well.

**Comment by jccatalano** [comment]
Another post does pick up something:
```"nominators": {
      "0": "",
      "": [
        4
      ]
    }```

**Comment by jccatalano** [comment]
The following was nominated by user 4 and the the admin (1?)
```
"nominators": {
      "0": "",
      "": [
        ""
      ]
    }
```

**Comment by jccatalano** [comment]
Here is a post nominated by only that admin user 1? 
```
"nominators": [
      ""
    ]
  },
```

**Comment by jccatalano** [comment]
Here is a post nominated by only user 4

```"nominators": [
      ""
    ]
  },
```

**Comment by jccatalano** [comment]
Here is a post nominated by the admin and then by user 4:
```
"nominators": {
      "0": "",
      "": [
        ""
      ]
    }
  },
```

**Comment by jccatalano** [comment]
I figured out the anomaly above that contained the 4. That post was nominated via the bookmarklet.

**Comment by jccatalano** [comment]
On the 4.4.x-stats-nomination-fix branch:

The nomination array appears to be working correctly. 
```
"nominators": {
      "1": {
        "user_id": 1,
        "nomination_datetime": "2017-11-27 16:04:57",
        "nomination_unixtime": 1511798697
      },
      "4": {
        "user_id": 4,
        "nomination_datetime": "2017-11-27 16:09:29",
        "nomination_unixtime": 1511798969
      }
```

The array will also display nominations via the bookmarklet; however, posts nominated via the bookmarklet and all content are still not counted correctly.

**Comment by regan008** [comment]
As Josh said, I think this is mostly resolved. I've created a new issue for the bookmarklet & all content issue (#961) and am going to close this.
