### ISSUE TITLE
Info does not display nominator on stats branch

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#957]
The info icon on the nominated page does not display who nominated the post on the stats branch.
Here is a post nominated from 4.4.x:
![screen shot 2017-11-01 at 11 01 07 am](https://user-images.githubusercontent.com/18265200/32281059-13d1cd42-bef4-11e7-92bb-a7c8cead52e4.png)

Here is a post nominated from the stats branch:
![screen shot 2017-11-01 at 11 01 23 am](https://user-images.githubusercontent.com/18265200/32281083-2c5ce608-bef4-11e7-9a4a-ddbe6849632d.png)

This may be tied to the other issues with the incorrect pf_posted array #956.

**Comment by jccatalano** [comment]
This is still not working

**Comment by AramZS** [comment]
@jccatalano Please retest, just pushed fix to the branch

**Comment by jccatalano** [comment]
Tested and is working correctly.
