### ISSUE TITLE
Stats UI duplicates info if clicked multiple times

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#958]
If the assemble author stats and the assemble valid posts buttons are clicked multiple times, the output is duplicated.

**Comment by regan008** [comment]
The UI here is now broken entirely and nothing is being displayed when the buttons are clicked. See #968.

**Comment by AramZS** [comment]
Ok. Will take a look

**Comment by AramZS** [comment]
Should be resolved in the 4.4.x-stats-interface branch. Please double check.

**Comment by regan008** [comment]
Confirmed, this is fixed.
