### ISSUE TITLE
Nominating and then Sending to Draft from all content Creates a nomination count of zero

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#959]
If a post is nominated by a user and sent to draft, and another user then nominates the post, the second nomination will not be counted in the UI. The second nomination is included in the array.

**Comment by AramZS** [comment]
@jccatalano UI at which location? And does this only occur when sent to draft?

**Comment by jccatalano** [comment]
This occurs in the nominations tab. If something is nominated and sent to draft it has a count of zero on the nominations tab.

**Comment by AramZS** [comment]
@jccatalano A count of zero in the button on the nominations screen? Or the button on the item screen? Or both? Maybe screenshots would be useful here?

**Comment by jccatalano** [comment]
![screen shot 2017-11-27 at 12 37 34 pm](https://user-images.githubusercontent.com/18265200/33280401-f1042018-d36f-11e7-8e27-8eb957fca9a9.png)
 The nominations screen. The all content (item screen) only indicates that the user nominated the post.

**Comment by AramZS** [comment]
Ready to test

**Comment by jccatalano** [comment]
Note: A nomination count of zero also occurs when a post is nominated from all content AND the bookmarklet.

**Comment by jccatalano** [comment]
This appears to be working properly. However, if a post is nominated and then sent to draft, it does not appear as a drafted post.
