### ISSUE TITLE
Bookmarklet does not cause nomination count to increase

### ISSUE THREAD

**Issue by regan008** [PressForward/pressforward#961]
If I nominate an item with an existing nomination from all content using the bookmarklet the nomination count does not increase. However the count is correct when nominating an item that has not already been nominated.

**Comment by lcrossley** [comment]
When testing do not send to draft.

**Comment by regan008** [comment]
Just tried this again and here is what is happening: 

User 1 (admin): Nominates a post from all content. The post appears in nominations with the correct count. 

User 2 (contributor): Nominates the same post from the web using the bookmarklet. The nomination count does not increase and user 2 does not appear anywhere in the info metadata. 

I've tried a number of users and browsers and this is happening across the board for me so I think it may be a typo in the unit test?

**Comment by regan008** [comment]
This is still occurring @AramZS .

**Comment by regan008** [comment]
@AramZS Initial testing is showing that this is still occurring. It is now duplicating the nomination when a post that is already nominated from all content is nominated using the bookmarklet.

**Comment by AramZS** [comment]
Let's walk through what exactly the issue is on the call
