### ISSUE TITLE
Nomination Count Differs by Method

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#962]
If a post is sent to draft from all content, and then nominated by another user, there will be two nominations. However, if a post is nominated from all content and then sent to draft from Nominated, and another user nominated it, the count remains at one. (this is related to #960) 

This is also related to #959. If an item is nominated by a user then sent to draft from all content there is a count of 0.  

Something is funky with the send to draft vs the regular nomination process. 

Is there a way to pull the nomination count from the endpoint?

**Comment by AramZS** [comment]
Where are you looking at the count here?

**Comment by lcrossley** [comment]
Nominations

**Comment by lcrossley** [comment]
Double check the endpoint and make sure that the count is accurate.

**Comment by AramZS** [comment]
Hi, these two numbers are no longer different, even if they stop after being sent to draft?

**Comment by regan008** [comment]
We're checking

**Comment by jccatalano** [comment]
Correct.

User 1: Nominates a post
User 2: Nominates a post
User 2: Sends post to draft
User 3: Nominates the post (UI Nomination count remains at 2)
User 2: Publishes post (Endpoint nomination count at 2)

**Comment by AramZS** [comment]
Ok, I'm going to close this issue then, as it is no longer occurring and deal with the other issues in their threads. I know this sounds a little odd, but I think the underlying issue for this particular slice of Nomination bugs is now resolved.
