### ISSUE TITLE
Selected part of source loses my selection when sent to draft

### ISSUE THREAD

**Issue by yoannspace** [PressForward/pressforward#972]
Hi,

I have an issue and wondering what the use case is/should be, and if there is possible a bug in the tool. I will explain step by step with a real example:

- I arrive on article http://www.bbc.com/news/world-us-canada-42235052
- I believe it should be nominated with PressForward to a blog owned by someone I know
- I select a short portion of the text, like the second paragraph of the text "Nearly 8,000 homes were under mandatory evacuation in the cities of Ventura and Santa Paula, north of Los Angeles."
- I click on the bookmark "Nominate This"
- A new page opens and I see only my selected text within wordpress "quotes", I add some personal text right above this quotes text from the source
- I click on "Nominate" and close this extra window
- I log out and go on with my life
- The admin of the said blog logs in and sees the new nomination with my text + my selected text from the source
- The admin likes it and wants to publish it
- The admin clicks on the "Draft" button in the list of all nomination, at the right side of the screen
- The admin goes to the "posts" section of wordpress and:
 -> expects to see the post with the same original texts (text of user + some selected text from source) with the addition of the source link
 -> sees the whole original article (with HTML markups, etc...)

Am I expecting something wrong, is there a mistake in my idea of workflow or is there maybe a bug somewhere?

Thanks!

**Comment by regan008** [comment]
Hi @yoannspace. It is not currently possible to nominate part of a source and that isn’t in our future plans. The bookmarklet is designed to nominate the entire piece which can then be edited later inside of WordPress. Hope that helps!

**Comment by yoannspace** [comment]
Hi @regan008, thanks for the very quick reply.

Maybe I should have added some pictures to make it clearer. The problem I see is in the transition "Nomination" -> "Draft post".

## Here I selected the part I like to have + I added some personal text:
<img width="937" alt="pressforward_972_image1" src="https://user-images.githubusercontent.com/227793/33611414-98a56818-d9ce-11e7-95e1-c9f67dffa34c.png">

## Here is the view of the admin within WordPress PressForward Nominated page:
<img width="1259" alt="pressforward_972_image2" src="https://user-images.githubusercontent.com/227793/33611415-98bfe4ae-d9ce-11e7-800b-e06f5c924d44.png">

## Here is after clicking on "Draft" and viewing it in the Post section of WordPress:
<img width="1402" alt="pressforward_972_image3" src="https://user-images.githubusercontent.com/227793/33611416-98d99886-d9ce-11e7-9e49-143f64707213.png">

I have the feeling this was working "before"...

**Comment by regan008** [comment]
@yoannspace thanks for the extra details. I will look into this further and get back to you this week

**Comment by AramZS** [comment]
Hi @yoannspace - I think this may have been resolved by other stuff in 5.0. Can you tell me if it is still occurring after the most recent update?

**Comment by yoannspace** [comment]
Hi @AramZS, I have checked yesterday (using PF github master and also the 5.0 release) and unfortunately, it is still not working.

**Comment by yoannspace** [comment]
Hi @AramZS @regan008 ,

I identified the issue at https://github.com/PressForward/pressforward/blob/5.1.x/Core/Utility/Forward_Tools.php#L419

It shouldn't (or at least I would expect it shouldn't) reload the source page. Maybe it is important for other part of the code, this I can't say, but for my "use case" it shouldn't - or it should reach this function with a $make_readable at "false".

Any idea on how to go further with this? I can probably help if provided pointers where to look / be careful.
Thanks,
Yoann

**Comment by AramZS** [comment]
@yoannspace I'm unclear... are you editing the Nomination at the nomination level?

**Comment by yoannspace** [comment]
@AramZS Yes, I am editing it in the pop-up after clicking on "Nominate This" bookmark and before clicking on "Nominate" on this pop-up.

**Comment by AramZS** [comment]
@yoannspace Oh. I see it. Yeah, ok the logic there is that for it not to trigger a reload from source it needs to meet particular character count requirements. If it doesn't the system assumes it needs to do so. But that logic can and prob should be changed for the bookmarklet.

**Comment by yoannspace** [comment]
Oh waw! Great! So there is a workaround that actually works. I just checked and added a "long" text at the nomination part and it went well into my draft post, thanks!
It would be great to have it working in 5.2 for any character count but we will use it with "long" text until then.
Could you please let me know the character count requirement?
Thanks!

**Comment by AramZS** [comment]
@yoannspace 150 characters or less (after the HTML is stripped out)

**Comment by AramZS** [comment]
Further bookmarklet issues will be resolved in the new version of the bookmarklet.

**Comment by yoannspace** [comment]
@AramZS Hi, could you please point me to a document or something about the new bookmarklet if it already exists? Thanks.

**Comment by AramZS** [comment]
@yoannspace We're still building it out, but it will come out in the next release!
