### ISSUE TITLE
Change item_id to be handled by hashing the URL and not the URL+title

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#974]
MAJOR BREAKING CHANGE ALERT.

**Comment by AramZS** [comment]
PR #977 is pending on this item.

**Comment by jccatalano** [comment]
I am still having a duplication issue. It appears that the bookmarklet is not cutting down the title found in the page tab.

**Comment by jccatalano** [comment]
![screen shot 2017-12-05 at 1 32 00 pm](https://user-images.githubusercontent.com/18265200/33623963-c39ddfa4-d9c0-11e7-8cb0-ac451959ae72.png)

**Comment by regan008** [comment]
This appears to be working now. Will test further later this afternoon.

**Comment by jccatalano** [comment]
Still having the same issue. Using WP 4.7
![screen shot 2017-12-05 at 2 38 59 pm](https://user-images.githubusercontent.com/18265200/33627070-60ea381c-d9ca-11e7-9a34-5dc1bee58c7f.png)

**Comment by AramZS** [comment]
Are you sure the same URL is in the top of the browser? Also are you sure you are on `4.4.x-stats-nomination-fix-item-id` branch?

**Comment by lcrossley** [comment]
![screen shot 2017-12-05 at 3 12 43 pm](https://user-images.githubusercontent.com/25589089/33628471-d11bdeca-d9ce-11e7-8934-113e243f5dcf.png)

**Comment by regan008** [comment]
I can also confirm that this is happening on my machine too. Not sure why it worked the first time but hasn't worked since.

**Comment by regan008** [comment]
Are we sure that this is a bug related to the changes made in this issue and not in diagnosing/fixing #961? Because I swear it wasn't duplicating every since article when I was using it yesterday. I feel like it was a new behavior introduced since the changes for #961. I was even using the same websites yesterday and this was not happening.

**Comment by AramZS** [comment]
I thought we fixed #961. Can you check through this process on the 4.4.x branch which doesn't include this change? If it is still happening there then we have a problem outside of the scope of this issue.

**Comment by regan008** [comment]
So this is happening sporadically in 4.4.x like we saw when we were screen sharing earlier today. However it is still happening in this branch as well. It is happening more often and even when post urls are the same in the Nominated info window's metadata.

**Comment by regan008** [comment]
@aramzs My fresh install is still causing the problem. For example this story duplicates: http://appleinsider.com/articles/17/12/05/honors-new-view-10-phone-brings-iphone-x-animoji-to-android
And the link inside the meta window is exactly the same in both nominations.

**Comment by AramZS** [comment]
@regan008 on this branch and the 4.4.x or just this branch?

**Comment by regan008** [comment]
I've only tested this branch on my new install.

**Comment by AramZS** [comment]
Can you check 4.4.x to confirm it is only happening here?

**Comment by regan008** [comment]
Its working sporadically though and I can't quite figure out what the differences between the posts are.

**Comment by regan008** [comment]
Yeah will check 4.4.x next

**Comment by AramZS** [comment]
Can you show me some that work?

**Comment by regan008** [comment]
Yes, both of these work: 
https://www.wired.com/story/qualcomm-building-pcs-out-of-smartphone-parts/
https://www.washingtonpost.com/news/powerpost/wp/2017/12/05/dozens-of-republicans-now-clamoring-for-a-dreamers-fix-by-years-end/

**Comment by AramZS** [comment]
Resolution now applied on `4.4.x-stats-nomination-fix-item-id` branch. Please re-test.
