### ISSUE TITLE
Archive Function is Removing Items across users

### ISSUE THREAD

**Issue by jccatalano** [PressForward/pressforward#984]
User 1: Nominates the item
User 2: Nominates the item
User 3: Nominates the item

User 1: Archives the item (it disappears for all users)

**Comment by regan008** [comment]
@jccatalano where is it disappearing? from All content or nominated?

**Comment by jccatalano** [comment]
It is disappearing from both all content and nominated

**Comment by regan008** [comment]
I think that is expected functionality but I'm looking right now.

**Comment by jccatalano** [comment]
Across users through?

**Comment by regan008** [comment]
Yeah, archived is site wide. Theoretically if you have access to nominated you have permission to make that call. So this can be closed -- its working as expected as far as I can tell.
