### ISSUE TITLE
Check Feed Items during retreival for `isPermalink` in the GUID

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#985]

**Comment by AramZS** [comment]
Ready to test

**Comment by jccatalano** [comment]
This has resolved most issues of duplication; but, the nomination count (if nominations occurs via different methods) is zero and the nominated button is not blue. #998

**Comment by jccatalano** [comment]
The nomination account of zero is the result of the same user un-nominating the post with their second nomination. If different users nominate the same post via different methods the count is correct.
