### ISSUE TITLE
Email notifications for new nominations

### ISSUE THREAD

**Issue by yoannspace** [PressForward/pressforward#987]
Hi,
As an enhancement, we have added the possibility to send emails from WP/PF when a nomination is done. It helps our editors knowing when something is arriving.
I would like to propose it to you for a future version. It is a bit related to #937.
In order to propose it, I would like to know from which branch should I start with this? Will there be a 5.1 branch from which I could work?
Thanks,
Yoann

**Comment by AramZS** [comment]
@yoannspace Go ahead and declare it against the master branch and we can handle the merge do a different branch if we need to at a later date.

**Comment by yoannspace** [comment]
@AramZS I just changed the PR to be against the master branch:
https://github.com/PressForward/pressforward/pull/993
Thanks,
Yoann

**Comment by AramZS** [comment]
Ready to test on the 5.1.x branch

**Comment by regan008** [comment]
I am continuing to test this and it could be a result of my local installation but I have not received any emails about nominations from either all content or the bookmarklet so far.

**Comment by yoannspace** [comment]
@regan008 One way to find out if your local installation can send emails is to add a new user to Wordpress and checking the "Send the new user an email about their account" box. If you receive an email then your installation can send emails which means this issue is not resolved. If you don't receive an email, then something needs to be changed in your installation before you can test this issue.

PS: It would send emails only when using the bookmarklet, and only when clicking "Nominate", not "Send to draft".

**Comment by regan008** [comment]
Ok so this working on a server with email capabilities. Is there a reason for only having an email send when an item is nominated using the bookmarklet? 

Also we need to update the helper text if that is the case and the functionality we want. It would seem logical to me to get email notifications on all nominations rather than just nominations from the bookmarklet but that is something we can discuss. 

Lastly, there are two lines of helper text on the preferences page. They essentially say the same thing so we should condense down to one line. 
<img width="782" alt="screen shot 2018-02-26 at 9 58 38 am" src="https://user-images.githubusercontent.com/4553057/36677249-ae8a6658-1adb-11e8-98e1-82ef91e9e081.png">

**Comment by yoannspace** [comment]
@regan008 Our "use case" was that when someone nominates a content, our editors receive an email to let them know about that so they can go online and visit the nominated section. So they don't have to visit the website's nominated section if nothing has happened.
True that we didn't add in the "all content" and maybe should have done so, but I see that @AramZS might have already done that in his last commit referenced here, thanks.
About the text, of course, feel free to change anything you might want, I am not a native speaker and there might very well be mistakes there.

**Comment by jccatalano** [comment]
I am unable to get the email notifications for nominations to work for the bookmarklet and all content.  Can you recheck this Aram. How quickly should the notifications go out?

**Comment by jccatalano** [comment]
Nominations from all content are now sending notifications but the bookmarklet is not.

**Comment by yoannspace** [comment]
Indeed, it seems that when using the bookmarklet, the function `to_nomination( $post = array() )` from PF_Advancement.php is not being hit.

**Comment by jccatalano** [comment]
Tested and working
