### ISSUE TITLE
Unable to Activate Plug In

### ISSUE THREAD

**Issue by vnstrht** [PressForward/pressforward#989]
I was able to install the plug in but when I try to activate, I get the following error:

Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected T_STRING in / ... /wp-content/plugins/pressforward/Libraries/gender-checker/src/GenderEngine/Matchers/Traits/NameList.php on line 5

We are running WP 4.9.1

Thanks

**Comment by mAAdhaTTah** [comment]
@AramZS looks like that dependency is using PHP5.4 features.

**Comment by vnstrht** [comment]
Great.  Thank you very much.

**Comment by AramZS** [comment]
@mAAdhaTTah thanks for catching that. 

@vnstrht We'll endeavor to release a patch that turns that feature off for older versions of PHP, but I'd highly recommend you update your PHP version.
