### ISSUE TITLE
Plugin is request minified CSS even when Dev mode is active

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#997]

**Comment by mAAdhaTTah** [comment]
[Here's how we did it in WP-Gistpen](https://github.com/mAAdhaTTah/wp-gistpen/blob/develop/app/Providers/AssetsServiceProvider.php#L24).

**Comment by regan008** [comment]
@AramZS With some investigation we have determined that this was introduced by this commit: e09ee3ea673b8fd09982f14103344da8d773bfe6 

Specifically I think its related to ```Libraries/Jaxion/src/assets/register.php``` where scripts are being loaded with the .min extension. I see it on lines 208/212 where .css was replaced by .min. 

We believe it is breaking both .css and .js files.

**Comment by regan008** [comment]
This appears to be resolved. @jccatalano Could you confirm?

**Comment by jccatalano** [comment]
I am not having any issues either.
